### ISSUE TITLE
[ENHANCEMENT] Add to Packagist.org

### ISSUE THREAD

**Issue by hassankhan** [picocms/Pico#101]
All you need to do is go [here](https://packagist.org/) and signup and add the repo. Would make it a lot easier to install :smile:

**Comment by eschwartz** [comment]
Any update on this? This seems kind of critical for a php library...

**Comment by eschwartz** [comment]
FYI: If anyone is having trouble installing Pico with composer, add this to your `composer.json`:

```json
	"repositories": [
		{
			"url": "https://github.com/picocms/Pico.git",
			"type": "git"
		}
	]
```

That will tell composer to look at this github repo for the package (instead of just on packagist).
