### ISSUE TITLE
Sintax color in Pico

### ISSUE THREAD

**Issue by erufenix** [picocms/Pico#115]
In Pico can use syntax highlighting github style using ```language or type Pygments with :::language Or how I can highlight code in my post?
Sorry my bad english

En pico se puede usar el resalto de sintaxis al estilo github haciendo uso de ```lenguaje o tipo Pygments con :::leguaje ¿O como puedo resaltar código en mis post?

**Comment by theshka** [comment]
Plugin is featured in Wiki.
