### ISSUE TITLE
Regex went outside block comment

### ISSUE THREAD

**Issue by anonimus-programus** [picocms/Pico#166]
### Explanation

Pico uses informations from **a block comment** placed at the **top of files**, like this:
```
/*
Title: Hello World!
Description: This is a normal post, form hello-world.md
Author: User
Date: 2013/01/01
*/
```

Some plugins may use value from that block comment, ie: Plugin [Pagination](https://github.com/rewdy/Pico-Pagination) uses Date value for filter.

### Problem

The problem rises when a .md file is **supposed not containing** certain value, but somewhere within content **lies similar syntax**.
In this example, Date value:

```
/*
Title: About
Description: This is a page, from about.md
Author: User
*/

### Lorem
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua.

### Text File Markup

Text files are marked up using [Markdown](http://daringfireball.net/projects/markdown/syntax). They can also contain regular HTML.
At the top of text files you can place a block comment and specify certain attributes of the page. For example:

/ *
Title: Welcome
Description: This description will go in the meta description tag
Author: Joe Bloggs
Date: 2000/01/01
*/
```

Then, the Plugin **will count** this Page as Normal Post, because it finds the post containing Date value.

### Suspect

It's probably caused by regex in:
File : `Pico/lib/pico.php`
Function : `protected function read_file_meta($content)`
Code : 
```
    foreach ($headers as $field => $regex){
      if (preg_match('/^[ \t\/*#@]*' . preg_quote($regex, '/') . ':(.*)$/mi', $content, $match) && $match[1]){
        $headers[ $field ] = trim(preg_replace("/\s*(?:\*\/|\?>).*/", '', $match[1]));
      } else {
        $headers[ $field ] = '';
      }
    }
```

Please take a look at this. Thanks a lot.

Cheers.

**Comment by theshka** [comment]
#67, #130, #131, & 483334170f268f76a028bd6615f633760c855bb4
