### ISSUE TITLE
Is there a way to make one plugin require another?

### ISSUE THREAD

**Issue by khanduras** [picocms/Pico#171]
Or am I stuck with writing it all in one plugin?

**Comment by dav-m85** [comment]
In my opinion, since we got now composer in pico, we shall leverage its dependency capability to achieve plugin requiring one another.

(long time I haven't been around, pretty amazed by the work done here @theshka. Good job !)

**Comment by theshka** [comment]
Thanks, glad to see you back in the threads @dav-m85 :+1:
