### ISSUE TITLE
Pico & IIS .. 404 not found

### ISSUE THREAD

**Issue by iamdex** [picocms/Pico#175]
Hi, I've installed PICO under my IIS running in windows 8.1. 
The cms home page is displayed correctly, but I can't navigate under the sub page..
I'm getting a 404 Not Found error .. :(

Someone can help me?

PS: I'm getting the same error under my test site at http://www.davideespertini.it/pico/
But in this case the webserver is apache..

**Comment by ciolben** [comment]
If you have IIS 8 or >,
you can translate the .htaccess rewrite rules into web.config in your root folder like this:

.htaccess
```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d 
RewriteRule . index.php [L]
</IfModule>
Options -Indexes
```
into web.config
```xml
<configuration>
	<system.webServer>
		<!-- ... your config here ... -->
		<rewrite>
			<rules>
				<rule name="Imported Rule 1" stopProcessing="true">
					<match url="." ignoreCase="false" />
					<conditions>
						<add input="{REQUEST_FILENAME}" matchType="IsFile" ignoreCase="false" negate="true" />
						<add input="{REQUEST_FILENAME}" matchType="IsDirectory" ignoreCase="false" negate="true" />
					</conditions>
					<action type="Rewrite" url="index.php" appendQueryString="true" />
				</rule>
			</rules>
		</rewrite>
		<directoryBrowse enabled="false" />
		<!-- ... your config here ... -->
	</system.webServer>
</configuration>
```

If you have an older version of IIS, you need the specifiy the rewrite section as follow before ```<system.webServer>``` : 
```xml
<configSections>
	<sectionGroup name="system.webServer">
		<sectionGroup name="rewrite">
			<section name="rewriteMaps" overrideModeDefault="Allow" />
			<section name="rules" overrideModeDefault="Allow" />
		</sectionGroup>
	</sectionGroup>
</configSections>
```
You can find more help [here] (http://www.iis.net/learn/application-frameworks/install-and-configure-php-applications-on-iis/translate-htaccess-content-to-iis-webconfig).
