### ISSUE TITLE
Can't insert image to page

### ISSUE THREAD

**Issue by masfur** [picocms/Pico#181]
Can I insert a image to singular page?
Need a plugin for this?
Is correct: ![image](/content/image/img.jpg)?

**Comment by okkhoy** [comment]
@masfur  could you provide an example?
where have you placed the image(s)? is it in the content folder or elsewhere on the internet?
I have the images along with the markdown files, however the image is not displayed on the page.
i use ![image txt](image file name) format. doesn't seem to work.
