### ISSUE TITLE
I started a forum for picocms users on Google Groups

### ISSUE THREAD

**Issue by CaptainPackers** [picocms/Pico#188]
With 1600+ stars, there must be a community of picocms users out there who can help each other. I noticed people are using this Issues feature of Github as a forum. I thought it might be easier to use a real forum, so I created a Google Group called [picocms](https://groups.google.com/d/forum/picocms). Please feel free to go there and post your comments, concerns, or pleas for help and support.

**Comment by theshka** [comment]
Added to Wiki: [](https://github.com/picocms/Pico/wiki)
