### ISSUE TITLE
URLs relative to current page

### ISSUE THREAD

**Issue by gbell12** [picocms/Pico#197]
I have subdirs of content, so I access it this way:

`http://pico.localhost/energy/windows/`

In there there's an index.md:
`BASIX rates the U-value of various window types and assemblies [here](specs/basix.pdf)`

I want `basix.pdf` to reside in `content/energy/windows/specs`, and I want to refer to it as above for simplicity.  This makes my content relocatable.

Am I off in the weeds?  Is this a MD thing?  I can see `/specs/basix.pdf` being appropriate for a URL relative to the host, but seems `specs/basix.pdf` should/could be relative to the current URL.

**Comment by dav-m85** [comment]
It works pretty well for me. MD does not interpret what you put in the parenthesis and copy it as is in the href attribute of the hyperlink. Indeed ```specs/basix.pdf```si relative to your current URL.

**Comment by gbell12** [comment]
Hmm... well using my exact case:

http://pico.localhost/productive_property/energy/windows

with 

BASIX rates the U-value of various window types and assemblies [here](specs/windows_basix_specs.pdf)

Gives me a URL of http://pico.localhost/productive_property/energy/specs/windows_basix_specs.pdf

Missing the "windows" subdir.  If I put that in, then the content is not relocatable.

**Comment by gbell12** [comment]
For what it's worth, Kirby and Grav both take that same MD to be relative to the current page (the behaviour I hope from Pico).

**Comment by mydalon** [comment]
I assume, this is because in your URL http://pico.localhost/productive_property/energy/windows
"windows" is not a directory but the filename. So it gets removed.

**Comment by gbell12** [comment]
Yes, pico makes a relative URL like `<a href="specs/windows_basix_specs.pdf">`.  Which I would have seen if I had done my due diligence (sorry).

So somehow I was browsing to `http://pico.localhost/productive_property/energy/windows` rather than `http://pico.localhost/productive_property/energy/windows/` (trailing slash)

Grav heads this problem off at the pass by making the link like
`<a href="/energy/windows_basix_specs.pdf"></a>`

So I think that may make this issue status "yeah, but still".  Pico makes a relative link exactly as specified in the MD, but if it added the last path element, the link would work if the user did or didn't have a trailing slash on the URL.
