### ISSUE TITLE
any idea for a search engine?

### ISSUE THREAD

**Issue by berteh** [picocms/Pico#198]
Hello.
I'd like to integrate a search engine in pico, any hint where to look at to be more efficient than adding a full parsing of the pages tree content via php?

**Comment by dav-m85** [comment]
Regarding the philosophy of the project, I would stick with a flat-file storage search engine, like the one provided by http://framework.zend.com/manual/1.12/fr/zend.search.lucene.html

**Comment by berteh** [comment]
will have a look, thanks. 
In the meanwhile stumbled upon https://github.com/mwgg/Pico-Search too.
