### ISSUE TITLE
PicoCMS Development

### ISSUE THREAD

**Issue by ghost** [picocms/Pico#199]
Is pico no longer maintained ? Acording to changelog the last release was on 2013.10.23

**Comment by TuxLyn** [comment]
@gilbitron, Alright thanks for quick reply Gilbert.

@mydalon, Since this project is open-source you can just fork it. Because this new person who bought it is not maintain it anymore.

Can we have reply from the owner of this repo ? Thanks.

**Comment by mistergraphx** [comment]
So ? any news about the maintainer ?

Actually, everybody fork pico and work in his own version. Fork is useful when merging is possible, but actually not.
No roadmap or discussions about where this open-source project goes.

Finally the solution is maybe to make a **spork** and start a new community around this evolution.

**Comment by eschwartz** [comment]
Hey -- I'm starting up a new project inspired by Pico, which is backwards compatible with existing apps and plugins.

See my whole spiel in #208.
