### ISSUE TITLE
Step by Step Blogging Setup Guide

### ISSUE THREAD

**Issue by CaptainPackers** [picocms/Pico#204]
I can't get blogging to come anywhere near working. Can someone write a step by step setup guide? PLEASE????

**Comment by CaptainPackers** [comment]
I'm using Gilberts template and the index page shows by blog but the date is '70-0101', almost as though it doesn't recognize the date format and is returning the equivalent of zero (0) [January 1, 1970 is what is returned by a lot of program when 0 is stored as the date integer]. I am trying to use a 'YY-MMDD' date format. 

Also, no hyperlinks are being created to the blog, but I suspect that could change if I ever get this date issue figured out.

**Comment by theshka** [comment]
I haven't investigated why `{{ page.date_formatted }}` returns an improperly formatted date, but I just used the `{{ page.date }}`variable instead as a workaround for now... 

``` {% if is_front_page %} <!-- Front page lists all blog posts -->

				<div id="posts">
				{% for page in pages %}
					{% if page.date %} <!-- Note we check for Date field (posts) here -->
					<div class="post">
						<h3><a href="{{ page.url }}">{{ page.title }}</a></h3>
						<p class="meta">{{ page.date }}</p>
						<p class="excerpt">{{ page.excerpt }}</p>
					</div>
					{% endif %}
				{% endfor %}
				</div>
			
			{% else %} <!-- Single page shows individual blog post -->
			
				<div class="post">
					{% if meta.title %}<h2>{{ meta.title }}</h2>{% endif %}
					<p class="meta">{{ meta.date }}</p>
					{{ content }}
				</div>	
				
			{% endif %}
```
