### ISSUE TITLE
how does is_front_page work

### ISSUE THREAD

**Issue by CaptainPackers** [picocms/Pico#205]
How does it work? Where in the engine is it set? Does it only get set as true for the home page or is it also true for all index pages?

**Comment by theshka** [comment]
It's a Twig boolean, set in `Pico.php`, around Line: 102 ` 'is_front_page' => $url ? false : true `

Just before that, it tests if you are on the main index page, or not.                

```php
/// Get the file path
if($url) $file = $settings['content_dir'] . $url;
else $file = $settings['content_dir'] .'index';
```
