### ISSUE TITLE
content is now content_sample => doc adjustment?

### ISSUE THREAD

**Issue by MatthiasKauer** [picocms/Pico#213]
Hi,
the last pull-request relocated the content folder. This is all fine and I could just use that location. The docs all talk about a content subfolder that isn't there anymore (and that won't be recognized after creating it) which is quite confusing.

Cheers,
Matthias

**Comment by dmelo** [comment]
Makes perfect sense to me. I will go over the docs, to modify it where it sees fit.

**Comment by MatthiasKauer** [comment]
After getting the site up the index.md refers to a physical location content/index.md which isn't there anymore for instance. It is called content-sample now.

**Comment by theshka** [comment]
dfd2533805c008b8ddac732e5ae7f3f55cf91f20
