### ISSUE TITLE
Make 'default' theme responsive/mobile-friendly

### ISSUE THREAD

**Issue by theshka** [picocms/Pico#214]
It would be great if the default theme came mobile-friendly. Especially considering Google's move to penalize websites that are not. (http://googlewebmastercentral.blogspot.ca/2015/04/rolling-out-mobile-friendly-update.html) 

Thoughts?

**Comment by aidangarza** [comment]
I suggest adding [http://leejordan.github.io/reflex/docs/demo.html](reflex). I just made a really simple site using Pico and Reflex together, and it turned out quite nicely IMO --> [http://lyrics.aidangarza.com](demo)

**Comment by theshka** [comment]
@aidangarza, I think that looks great as well. Different than what I was expecting, but I can definitely see a case where that kind of navigation would be beneficial. 

I updated the navigation menu and submitted a PR. It retains it's current style/feel, but is responsive. Here's a demo: http://heshka.com/demo/Pico until the request is merged. :+1:
