### ISSUE TITLE
500 Internal Server error on non-index pages

### ISSUE THREAD

**Issue by tylershuster** [picocms/Pico#22]
After installing Pico on my server, the index works, but attempts to go to other pages result in a 500 Internal server error.

**Comment by pbloem** [comment]
Had this problem, and I couldn't get access to the error logs. For the people coming here from google, I found the problem by commenting out all the lines in the .htaccess. This removed the 500 error, and showed the homepage (but not other pages, obvs).

I then removed the comments line by line, and found that the offending line was 
'''
   RewriteRule ^(config|content|lib|vendor)/.* - [R=404,L]
'''
Removing the "=404" part worked. I suppose my host may have an outdated version of apache...
