### ISSUE TITLE
Fix for 404 Not Found errors on sub links (Mac OS X)

### ISSUE THREAD

**Issue by eattext** [picocms/Pico#227]
This post relates to a problem that has been touched on in the following threads:
[04 Not found #55](https://github.com/picocms/Pico/issues/55)
[sub-dirs don't work #3](https://github.com/picocms/Pico/issues/3)
Basically, Pico installs successfully&#42; (refer bottom of post for Timezone error fix), home page displays fine, sub pages are listed on the navigation bar on the home page, but **clicking a link to a sub page index or sub page throws a 404 error**.

I have managed to resolve the issue after some trial and error, and thought it would be useful to document my findings here. Note that this is for running Pico locally on the built-in Apache server on Mac OS 10.10 (Yosemite). Note also that I am not a programmer or developer (replace ‘hacker’ with ‘hack’), so your comments and corrections are welcome.

I am assuming that Apache server is already up and running locally. There are a number of guides for setting this up e.g. [Get Apache, MySQL, PHP and phpMyAdmin working on OSX 10.10 Yosemite](http://coolestguidesontheplanet.com/get-apache-mysql-php-phpmyadmin-working-osx-10-10-yosemite/).

My understanding is that `/etc/apache2/httpd.conf` applies to all users, and `/etc/apache2/users/yourusername.conf` applies to the current user only. On my setup, I want to have `myhomefolder/Sites/` as the root directory (i.e. `/Users/myusername/Sites/` as the equivalent of `/public_html/`), and `myhomefolder/Sites/pico` as my pico test folder (i.e. the equivalent of a subdomain on my online web server).

Noting the above setup and preferences, my edits are as follows:

In `/etc/apache2/httpd.conf`:
* Check that `LoadModule rewrite_module libexec/apache2/mod_rewrite.so` is active i.e. uncommented
* Leave `DocumentRoot "/Library/WebServer/Documents"` and `<Directory "/Library/WebServer/Documents">` as is (as opposed to changing the path to `/Users/myusername/Sites/`, which some would recommend) 

In `/etc/apache2/users/myusername.conf` (create this file if not present, making sure that it has .conf and not .txt etc as its file extension, and replacing ‘myusername’ with your username, of course):
* Enter the following code:

```ApacheConf
<Directory "/Users/myusername/Sites/">
    	Options Indexes MultiViews FollowSymLinks
    	AllowOverride All
    	Require all granted
</Directory>
```

This tells the server to apply the above settings to the Sites folder, which is all I am interested in.

In `myhomefolder/Sites/pico/.htaccess` (if you don’t see this file, make sure you have [made hidden files visible](http://blog.bertvanlangen.com/articles/toggle-hidden-files-finder-os-x-10-10-yosemite/)):
* Check that you have the following code (In particular, make sure that you have the `RewriteBase` line, and note that the example below is for a Pico installation in the `pico` subdirectory in the root folder):

```ApacheConf
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /~yourusername/pico
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d 
RewriteRule . index.php [L]
</IfModule>

# Prevent file browsing
Options -Indexes
```
I hope someone out there will find the above helpful (and spend less than two days figuring it out ...).

---
&#42; As an additional note, if you get a string of `Warning: strtotime(): It is not safe to rely on the system's timezone settings` errors, perform the following fix:

*In the root of your pico installation, make a copy of `config.php.template` in the same location, and rename it `config.php` (you can simply rename the original `config.php.template` to `config.php` and edit if you like. Leaving a copy of the original as backup is just my personal preference).
* Open `config.php` in Textedit or other text editor.
* Uncomment the line under `TIMEZONE` and replace `UTC` in `date_default_timezone_set('UTC');` with your timezone.<br />
Here is a [List of Supported Timezones](http://php.net/manual/en/timezones.php)

**Comment by theshka** [comment]
This has been discussed several times. The issue is always RewriteBase, and it's specific to your installation. #3, #22, #34, #55, #100, #109, #193, #226
