### ISSUE TITLE
 The use statement with non-compound name 'ParsedownExtra' has no effect

### ISSUE THREAD

**Issue by erikwittek** [picocms/Pico#228]
Pico CMS shows the warning:

Warning: The use statement with non-compound name 'ParsedownExtra' has no effect in /app/public/lib/pico.php on line 2

It can be fixed with commenting out or removing the second line in the pico.php file.
Is this statement really necessary?

**Comment by theshka** [comment]
Fixed in: 48e5c9e5003cd2b24bd3a972812e6ca4980aace9
