### ISSUE TITLE
The requested URL /sub/ was not found on this server

### ISSUE THREAD

**Issue by Endogen** [picocms/Pico#236]
I've tried version 0.8 and 0.9 and i can install it perfectly fine and opening the index page works also fine. But if i click "Sub Page Index" i get the error:  

Not Found
The requested URL /sub/ was not found on this server.

If i click "Sub Page", i get the error:  

Not Found
The requested URL /sub/page was not found on this server.

I'm on Mac and i also tried the master version. Any hint what i going wrong here?

**Comment by theshka** [comment]
Un-comment `RewriteBase` in the .htaccess. 

#226 , #100, #22
