### ISSUE TITLE
Call ParsedownExtra::processTag($elementMarkup) with empty string cause 500 error

### ISSUE THREAD

**Issue by hplc** [picocms/Pico#242]
CentOS 6
PHP 5.3.3

Try to debug 500 error while first installed, while ParsedownExtra::processTag($elementMarkup) being called twice and the second time empty $elementMarkup cause the 500 error.

Still don't konw why ParsedownExtra::processTag($elementMarkup) was called with empty $elementMarkup. But I can see the front page if add codes in the beginning of:

    vendor/erusev/parsedown-extra/ParsedownExtra.php
        Line 460: protected function processTag($elementMarkup) # recursive

with codes:

    if (empty($elementMarkup)) {
        return ‘’;
    }

**Comment by PhrozenByte** [comment]
I'm not able to reproduce this, it probably already got fixed in `ParsedownExtra`. If this is not the case don't hesitate to reopen this issue.
