### ISSUE TITLE
Allow PHP files as themes

### ISSUE THREAD

**Issue by Lesik** [picocms/Pico#245]
Currently, if I have theme foo in `/themes/foo/`, it has to be `index.html`. It would be nice to use some PHP functions in that file, but Pico doesn't recognize any PHP files in `/themes/foo/`, it searches only for `index.html`:

```
Fatal error: Uncaught exception 'Twig_Error_Loader' with message 'Unable to find template "index.html" (looked into: /homepages/htdocs/domain.tld/username/themes/foo).' in /homepages/htdocs/domain.tld/username/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:195

Stack trace: #0 /homepages/htdocs/domain.tld/username/vendor/twig/twig/lib/Twig/Loader/Filesystem.php(138):
Twig_Loader_Filesystem->findTemplate('index.html') #1 /homepages/htdocs/domain.tld/username/vendor/twig/twig/lib/Twig/Environment.php(266):
Twig_Loader_Filesystem->getCacheKey('index.html') #2 /homepages/htdocs/domain.tld/username/vendor/twig/twig/lib/Twig/Environment.php(324):
Twig_Environment->getTemplateClass('index.html', NULL) #3 /homepages/htdocs/domain.tld/username/vendor/twig/twig/lib/Twig/Environment.php(293):
Twig_Environment->loadTemplate('index.html') #4 /homepages/htdocs/domain.tld/username/lib/pico.php(107):
Twig_Environment->render('ind in /homepages/htdocs/domain.tld/username/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 195
```

**Comment by theshka** [comment]
You need to pass variables to and use Twig in the views, and plugins to include PHP logic in your pages. Kind of discussed in: #219 ... I can link you to my theme where I use the image plugin to generate an array of images that I access as Twig variables in my templates, if that will help any.

**Comment by Lesik** [comment]
I am aware of the "twig way", but was hoping for something simpler.
But if that is against the way Pico is supposed to run, I understand that. Thanks for your response :)
