### ISSUE TITLE
Issues with URLs and loading files

### ISSUE THREAD

**Issue by benjam1n** [picocms/Pico#251]
Hi there!

Just started playing with Pico and it is possible that my error is something really stupid but since I tried a lot of things and nothing is working I'm asking you for help.

The problem is that all pages except index are showing 
```The requested URL /services was not found on this server.```
and in console
```
File does not exist: /home/ubuntu/workspace/projects/, referer: https://symbolic-benjam7n.c9.io/?_c9_id=livepreview0&_c9_host=https://ide.c9.io
```

**Comment by benjam1n** [comment]
Solved. It didn't work because I didn't have htaccess file. Don't you think we could add it to repo?

**Comment by MuhPirat** [comment]
Hey benjam1n,
there is an htaccess file in the repo: https://github.com/picocms/Pico/blob/master/.htaccess

-mumu
