### ISSUE TITLE
Problem with HTTPS

### ISSUE THREAD

**Issue by fourtonfish** [picocms/Pico#253]
Hi,

[My site](https://github.com/botwiki/botwiki.org) wasn't working correctly with HTTPS. It looked like it was just ```get_protocol``` not returning the correct value, but it turned out [this](http://stackoverflow.com/questions/10951325/how-can-serverhttps-be-empty-when-accessing-over-https) was the problem.

I am not really sure if this was just my particular server setup, but I'm just letting you know about this.

**Comment by dav-m85** [comment]
This is unrelated to Pico @fourtonfish.

**Comment by fourtonfish** [comment]
@dav-m85 And yet it got [fixed](https://github.com/picocms/Pico/pull/252).

**Comment by PhrozenByte** [comment]
Actually #252 doesn't really "fix" this, it just contains a workaround for broken webservers by assuming requests through port 443 are HTTPS requests. You should still fix your webserver configuration.

**Comment by fourtonfish** [comment]
@PhrozenByte Ah, can you elaborate on that? Isn't 443 *the* HTTPS port?

**Comment by PhrozenByte** [comment]
It's the *default* HTTPS port, not the *only* HTTPS port.

**Comment by fourtonfish** [comment]
Ah, I think I know what's going on now, it's CloudFlare. Thanks a lot!
