### ISSUE TITLE
Multiple Pico installations on same server?

### ISSUE THREAD

**Issue by adamselby** [picocms/Pico#254]
This may be a dumb question, but I'm not sure how to get multiple Pico installations to run on the same server. Should they be initiated on different ports, and then specified via .htaccess? I can't find any documentation regarding the best way to do this. Thanks!

**Comment by dav-m85** [comment]
Your problem is not related to Pico but to your webserver configuration (apache or nginx or something else). Google for "virtualhosts <name of your webserver>". Sorry for not being more specific.

**Comment by phillbailey** [comment]
Bit late I realise, but I solved the same problem slightly differently. I have a main config file (config.php) and site specific configs (config.example.com.php and config.0.0.0.0.php for local testing). They're all running on Nginx in production.

In the config.php file, set the base URL and then require the site specific config with all the usual settings.

```php
$config['base_url'] = 'http://' . $_SERVER['HTTP_HOST'];
require_once('config.' . $_SERVER['SERVER_NAME'] . '.php');
```

Neither of the sites receive that much traffic, so I've not seen particular performance issues doing it this way. The benefit of 1.0 is that you can enable plugins on a site by site basis, in 0.8/0.9 obviously that's not possible without editing the plugin.

**Comment by PhrozenByte** [comment]
Just let this be said, we don't support @phillbailey's multi-domain solution, however there are (as of Pico 1.0.0-beta.2) no (known) side-effects when doing something like this.

Anyway, it could lead to problems in the future, so I recommend you to use Pico's official multi-domain solution by changing Pico's config dir (see [`Pico::__construct()`](http://picocms.org/phpDoc/master/classes/Pico.html#method___construct)) in your `index.php`. When also changing Pico's plugins dir dynamically, you can even use old plugins on a per-domain basis.

Simply change [line 17 of your `index.php`](https://github.com/picocms/Pico/blob/master/index.php#L17) to e.g. `"config/" . $SERVER['SERVER_NAME'] . "/"` and create a `config/example.com/config.php`.

Another example of how you could use Pico's multi-domain solution is described in #301.
