### ISSUE TITLE
Detect symbolic links to md files

### ISSUE THREAD

**Issue by dmelo** [picocms/Pico#255]
Hi,

I'm migrating from Drupal. Everything is fine, except that in Drupal it is possible to have many links pointing to the same page.

I have created different symbolic links to the same md file, in order to preserve the links I had before. The problem is that on the main blog page, that lists all my posts, it is listing duplicates. It is considering both the real file and the symlink. Is there a way to detect symbolic links, in order to avoid duplicates?

**Comment by theshka** [comment]
Can this be merged with #252? @PhrozenByte

**Comment by PhrozenByte** [comment]
No @theshka, unfortunately this isn't that easy. The referenced commit only detects that the file is a symlink, @dmelo probably then hides this page in his own theme. This is no generic solution. One could use symlinks for different reasons, e.g. providing contents that are stored in a users home directory. We must validate that the symlink really is a duplicate (symlinks can cascade, it's not just a single `in_array()`) and then provide a way to exclude this page safely (we can't just remove it from `$pages`, this would break `Pico::discoverCurrentPage()`). Imho the use case doesn't justify the added complexity. Anyway, it's still possible to implement this as a plugin...

**Comment by theshka** [comment]
Okay, thanks for the clarification.

**Comment by dmelo** [comment]
Thank you for the efforts.

I have changed my Pico to inform when a page is a symlink. Then on my theme I only list the pages that are not.

But I agree with @PhrozenByte when he says this is better suited to be on a Plugin. I will transform this change into a plugin.

**Comment by dmelo** [comment]
Modify Pico to inform if a page is a link is easy. I have added something like 

    $data['symlink'] = is_link($page);

Inside get_pages method. It works fine. The problem is. I can't find an easy way to implement this as a plugin. The hook `get_page_data` don't have the $page. To use the `get_pages` hook seems like an overkill, since I would have to recalculate the key for `$sorted_pages` and that require rebuild $page_meta
