### ISSUE TITLE
PHP Built-in web server start command

### ISSUE THREAD

**Issue by RuZniki** [picocms/Pico#257]
Then I use 
```bash
php -S 0.0.0.0:8080 ./
````
And after I try to access http://localhost:8080/ and receive 500 status.
I get in my console:
```bash
[Wed Sep 30 00:23:06 2015] PHP Warning:  Unknown: failed to open stream: Inappropriate ioctl for device in Unknown on line 0
[Wed Sep 30 00:23:06 2015] PHP Fatal error:  Unknown: Failed opening required './' (include_path='.:/usr/share/php:/usr/share/pear') in Unknown on line 0
```
But if use 
```bash
php -S 0.0.0.0:8080 -t ./
```
everything works fine.
I'm using Ubuntu 14.04 and php 5.5.9-1ubuntu4.12 (cli)

**Comment by theshka** [comment]
Have you tried issuing just `php -S localhost:8080` without the `./` or `-t` operator? Then accessing it from the same `http://localhost:8080/`

> URI requests are served from the current working directory where PHP was started, unless the -t option is used to specify an explicit document root. If a URI request does not specify a file, then either index.php or index.html in the given directory are returned. If neither file exists, the lookup for index.php and index.html will be continued in the parent directory and so on until one is found or the document root has been reached. http://php.net/manual/en/features.commandline.webserver.php

**Comment by RuZniki** [comment]
Yes I tried, it works fine.
```php -S localhost:8080```
But in README ```php -S 0.0.0.0:8080 ./```, maybe it need to be changed.

**Comment by theshka** [comment]
Noted for #252, thanks.
