### ISSUE TITLE
Accessing files directly is possible?

### ISSUE THREAD

**Issue by marciotoledo** [picocms/Pico#259]
Hi,

I'm working on my first project with PicoCMS, so we have a folder in root (/signature) with some images there. I want access those files directly but I think Pico is blocking it.

**Comment by theshka** [comment]
How are you trying to access them within Pico? I cannot replicate this issue. 

1) Placed a `test` folder in the root Pico directory, 
2) Placed several test `.jpg` images in the directory, 
3) Created a `test.md` markdown file in the `contents-sample` folder,
4) Placed an image tag pointing to the above test folder/file `![AltName](http://localhost/test/test.jpg)`
5) Viewed the page at `http://localhost/test`
6) Works as expected. 

The `.htaccess` file (https://github.com/picocms/Pico/blob/master/.htaccess/) has exceptions for files and directories on Lines 5&6, so Pico shouldn't be blocking it @marciotoledo

**Comment by marciotoledo** [comment]
I think I had problem with file permission. Sorry, it's working fine now.
