### ISSUE TITLE
packagist

### ISSUE THREAD

**Issue by dav-m85** [picocms/Pico#261]
I needed it to include Pico as a dep in another project., thus created the packagist job for this repo, https://packagist.org/packages/picocms/pico.

@theshka, I will gladly add you as a maintainer for it, I just need your packagist username in order to do this. I'll submit a PR with the badge if you find it usefull.

**Comment by theshka** [comment]
As @gilbitron no longer owns this repository and had a listing here: https://packagist.org/packages/gilbitron/pico, I would say that this new https://packagist.org/packages/picocms/pico listing can be used going forward. Does @picocms have a packagist account? My username is the same there as here @dav-m85

**Comment by dav-m85** [comment]
You're in @theshka. Plugging auto-update could be cool. @picocms does not seem to have a packagist account. Closing the issue until further notice.

**Comment by theshka** [comment]
@dav-m85 I've spoke with and added the @picocms owner to the packagist account https://packagist.org/users/picocms/, and have requested that they initialize the auto-update web hook. :+1:
