### ISSUE TITLE
Relative file paths

### ISSUE THREAD

**Issue by Crispy24** [picocms/Pico#262]
Just like many other Pico users, I'm looking for relative file paths. I'd like to know what you have planned, and maybe also what progress you've achieved.

I searched Google, GitHub, and Pico for any information regarding relative file paths in Pico, and the only hits I got were issues in this repository.

In the handful of issues I read, I saw that issue #229 was closed about 4 months ago; labeled low priority and in-progress. Lack of support for relative file paths may not be deal-breaking, but to support my own choice of file structure, this is my desired implementation.

I just want to abstract content from code as best as I can. That's why I ended up using a flat-file CMS. I want my images to be located in the same directory as the page to which they belong. Without relative file paths, I don't have the abstraction required to freely move my pages around. Now, I don't know how much attention an issue merits

So I'm asking for a bit more transparency: I'd like some follow-up information not addressed in previously closed issues: What are your plans for relative file paths? Clarifying what you're doing with relative file paths will help users come to their conclusions more readily, and help them decide if they can live with it, or without it.

Thanks, and on a side note, I'm very impressed with Pico. Dead-simple interface. Great work!

**Comment by PhrozenByte** [comment]
It's good practice to separate contents and assets, you even shouldn't make your content dir accessible from outside. Anyway, this is not related to Pico, its something about your webserver config. If you're using Apache, you can add the following rules to the beginning of the existing rewrite rules in your `.htaccess`:
```
RewriteCond %{DOCUMENT_ROOT}/pico/content/$1 -f
RewriteRule ^(.+)$ content/$1 [END]
```

To put this very clear: **We don't support this!** Pico is highly extensible and we already know access control plugins, which are completely useless if the raw content dir is accessible from outside.

**Comment by Crispy24** [comment]
@PhrozenByte Thanks for the insight. I'll definitely have to work on my mod_rewrite rules. I was still using the same rules supplied in ```.htaccess```, which I'm sure isn't good practice. I'm good with regexps, but mod_rewrite still managed to scare me off :confused:...
