### ISSUE TITLE
vendor/autoload.php

### ISSUE THREAD

**Issue by julindra** [picocms/Pico#265]
A few days ago, I search for flat file CMS and i found Pico. So i download it, upload it to my hosting, and open my website. But i got a problem, when i open my website, it's all blank, just a white page. I open the error log file, and i found that there is no vendor/autoload.php file, which is required by Pico. It is just me or what?

**Comment by Wisnaeme** [comment]
Nope. It's me too. Fresh download. :-(

**Comment by bricebou** [comment]
Yes it is normal but there were debates about having a complete version of
Pico.

After downloading Pico you have to run

composer install

But i think it is said in the readme

Le vendredi 9 octobre 2015, Wisnaeme <notifications@github.com> a écrit :

> Nope. It's me too. Fresh download. :-(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/picocms/Pico/issues/265#issuecomment-146973151>.
>


-- 
Brice Boucard

**Comment by Wisnaeme** [comment]
Thanks Bricebou

As I can't use commands on my remote server I guess Pico is no use to me then.

Oh well.

**Comment by jstamant** [comment]
I don't suppose you can just run `$ php composer.phar install` locally, and upload everything to the remote server?

**Comment by Wisnaeme** [comment]
Hmm. Maybe. I'll need to think about this. 
Quite disappointed with the "Not working at download" state of the project.

Currently looking elsewhere for a flat CMS. Only have very simple needs and need a solution within next 4 hours. Can't really be bothered chasing up this project as I'd need to build a local server.

Clock's'a'tickin'

**Comment by bricebou** [comment]
You can download Pico localy then run composer before uploading on your
remote server

I remember debates about having a ready to install version of Pico.

I think we should call @theshka <https://github.com/theshka> on this

Le vendredi 9 octobre 2015, Justin R. St-Amant <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> a écrit :

> I don't suppose you can just run $ php composer.phar install locally, and
> upload everything to the remote server?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/picocms/Pico/issues/265#issuecomment-146976087>.
>


-- 
Brice Boucard

**Comment by PhrozenByte** [comment]
We'll have a solution with the upcoming Pico 1.0 release. Until then, here you go: http://daniel-rudolf.de/files/pico0.9-vendor.tar.gz

**Comment by Wisnaeme** [comment]
Thanks for that. I've got it installed and will play around now.
