### ISSUE TITLE
Anchor Links

### ISSUE THREAD

**Issue by smcdougall** [picocms/Pico#272]
This isn't an issue so much as an unintended, undocumented "feature".  I've discovered a neat url trick you can perform using Pico and HTML Anchors.  I haven't tried Pico 1.0 yet, so I'm only assuming it will still work with the new version.

Create a markdown file with no content, only metadata.  Give it a file name that contains a "#" followed by the name of an anchor on an existing page, for example "#anchor.md" or "page#anchor.md".

This file will show up in the navigation as a page on your site and it will use the name you specified in it's metadata.  However, when you click on this link, rather than bringing you to this blank page you created, it will bring you to the "anchor" in the "page" you specified.

You can see this in action on my [NotePaper Theme](http://development.sjmcdougall.com/pico-themes/NotePaper/) site. I'll be updating the theme soon for Pico 1.0, and I guess I'll find out for myself if this still works.

Given that this is kind of a neat trick / URL hack, I feel like it should be mentioned somewhere in the documentation.  I've found it really useful, and I feel like others would too.

**Comment by theshka** [comment]
This behaviour is confirmed to happen in `Pico 1.0.0-beta.1` as well. Perhaps this discovery can be included in the `Creating Content` section of the docs? 

The theme looks great, btw @smcdougall :smile:

**Comment by PhrozenByte** [comment]
Nice hack. Same for the theme, looks great! :+1:

Unfortunately this reveals a practically relevant bug: The missing `urlencode()` in `Pico::getPageUrl()` (note to myself: It should be `rawurlencode()`...). Whereas the anchor sign (`#`) has the described, not so bad side-effect, ampersand (`&`) and question mark (`?`) break Pico - which one depends on enabled URL rewriting. Both are commonly used characters for page titles.

Therefore @smcdougall, I've to tell you that we have to fix (remove) this with the final Pico 1.0.0 :unamused:

Besides the possibility of writing a (unnecessary complex and very slow) plugin, I suggest you to use a `toc` meta header to implement TOCs. That's a pretty common solution for Markdown files. We're using the same technique on our website.

Example:
```yaml
---
toc:
    item-on-level-1:
        _title: Item on Level 1
        item-on-level-2a: Item on Level 2 (a)
        item-on-level-2b: Item on Level 2 (b)
    another-level-1-item: Another Item on Level 1
---
```
```twig
<ul>
    {% for sectionKey, section in meta.toc %}
        <li>
            {% if section._title %}
                <a href="#{{ sectionKey }}">{{ section._title }}</a>
                <ul>
                    {% for subSectionKey, subSection in section if subSectionKey != "_title" %}
                        <li><a href="#{{ subSectionKey }}">{{ subSection }}</a></li>
                    {% endfor %}
                </ul>
            {% else %}
                <a href="#{{ sectionKey }}">{{ section }}</a>
            {% endif %}
        </li>
    {% endfor %}
</ul>
```

**Comment by PhrozenByte** [comment]
By the way: When a `toc` meta header is no suitable solution for you, please don't hesitate to tell us what you're trying to achieve, we'll find a solution :smiley:

**Comment by smcdougall** [comment]
@PhrozenByte It's okay, I sort of figured this would happen.  Your solution sounds really robust though.  I looked over the sources of the Pico site and I'm pretty intrigued by the concept (especially by the "collection" folders).  Is there a resource you could link to that goes into more detail?

**Comment by PhrozenByte** [comment]
Our website is unfortunately not realized with Pico, but with Jekyll (quite similar software, just worse... The reason why I'm saying this is not because I'm a Pico developer...). This is a compromise we had to make: our project has no server, so we're relying on GitHub Pages, what either supports static HTML pages or Jekyll. We decided to use Jekyll, even with its downsides it's better than maintaining static HTML pages.

Pico doesn't have something similar to Jekylls "collections" concept, as far as I can tell their only reason to exist is that you can't get the rendered contents of a arbitrary page with Jekyll. With Pico you have this ability (e.g. `{{ "sub/page"|content }}`). With Pico you can simply use any folder to realize what a collection does in Jekyll. Actually you're already doing it with your great widget system :smiley:

**Comment by smcdougall** [comment]
Okay, I figured out what I wasn't understanding in your example.  I went back and looked at the 1.0 changelog again and noticed that you can now make *any* meta headers that you want without needing to write a plugin to parse them.  Nice Work.

Glad you like my widget system. :smile:  At some point, I'll probably rework it to use custom meta headers instead of dedicated folders.  "if meta.widget" seems a little more elegant than "if "/widgets/" in page.url".

Back to the point though, glad to have squashed a last-minute bug before 1.0.  I'll see if I can work in your solution for TOCs into my theme.  Going forward it'll be a better solution than a URL hack anyway.

Congratulations on 1.0.  Glad to see development on Pico continuing.  Keep up the good work! :+1:

**Comment by PhrozenByte** [comment]
Thank you! If you have any question which is not answered in our docs, please don't hesitate to open a new Issue :smiley:

**Comment by smcdougall** [comment]
@PhrozenByte Thanks again for that example code.  I was able to get it working and customized a bit.  It'll be a feature included in the next update of my theme.  This new ability to use custom meta headers together with your example of using a meta *array* has got me thinking of a *ton* of potential customization ideas!

**Comment by smcdougall** [comment]
@PhrozenByte I made it recursive! :laughing: 

```
{% import _self as macros %}
{% macro rnav(toc) %}
  {% import _self as macros %}
  <ul>
    {% for sectionKey, section in toc %}
      <li>
        {% if section._title %}
          <a href="#{{ sectionKey }}">{{ section._title }}</a>
          <ul>
            {{ macros.rnav(section) }}
          </ul>
        {% else %}
          <a href="#{{ sectionKey }}">{{ section }}</a>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
{% endmacro %}
```

Thought I'd share.  If you'd like, one of us can put it in the cookbook whenever that gets done. :smiley:

**Comment by PhrozenByte** [comment]
[Done](http://picocms.org/cookbook), thank you @smcdougall!

**Comment by smcdougall** [comment]
Well, that was quick.  Glad I updated my comment before you looked at it.  It originally had two bugs I hadn't caught yet.
