### ISSUE TITLE
page.url generates "domain//page-url"

### ISSUE THREAD

**Issue by smcdougall** [picocms/Pico#274]
Ever since I started testing Pico 1.0, my url's (meta.url, page.url) have been generating double slashes between the domain and the page url.  I can't quite narrow down the problem.  There are no rewrite rules in my apache config (for this domain anyway), and the issue occurs with or without the provided .htaccess file.  With .htaccess I get "domain//page-url", and without it I get "domain//?page-url".  The issue also occurs with the .htaccess file from 0.9, so I think .htaccess can be safely ruled out as the cause.

I haven't made any changes to my apache config since updating to 1.0, and my existing 0.9 sites don't have this issue.  Also, if I correct the url in my browser's address bar, it loads the page correctly and doesn't rewrite the url to "//" (urls on the page however still have the "//").  If I manually write a url (hard-coded or using %base_url%), it both works correctly and doesn't have a "//".

Also, while subfolders also have this issue, only the slash between the domain and the first directory has the "//", any further slashes in the url do not.

%base_url% / {{ base_url }} print correctly, with no trailing slash, however, if I set the "base_url" in config.php it resolves this issue, despite %base_url% / {{ base_url }} showing the same (no trailing slash) either way.

Something, somewhere is adding in a trailing slash where there shouldn't be.  Hope this isn't to confusing, I've tried to include as much information as I could.

**Comment by theshka** [comment]
Make sure you set a completely-formed 'base_url' in your 'config/config.php' (e.g http://localhost:8080) ... That solved the extra slash for me.

**Comment by PhrozenByte** [comment]
Do you specify `base_url` and/or `content_dir` in your `config/config.php`? If yes, which are the concrete values (you can replace your domain by example.com)? Is it `config/config.php` or just `config.php` in Picos root dir?

**Comment by smcdougall** [comment]
@theshka Yes, I mentioned that in my post.  It's fine if that's what has to be done, but the comment next to base_url suggests that it should be an override, not a required setting.

@PhrozenByte I've got my content_dir set to "content/", but base_url is undefined.  Config.php is in the config folder.  Here's the debug output.  There's a lot of custom config variables for my theme.  Also, my Pico folder is symlinked to /var/www/testing, but for some reason in the debug output php is reporting the original location.

	array(27) { ["site_title"]=> string(27) "Testing @ McDougallhome.net" ["theme"]=> string(9) "NotePaper" ["pages_order_by"]=> string(4) "date" ["pages_order"]=> string(3) "asc" ["content_dir"]=> string(63) "/home/mcdougall/sync/Simon/files/Documents/Web/testing/content/" ["timezone"]=> string(5) "UTC-5" ["site_logo"]=> string(22) "/content/site_logo.png" ["front_page_mode"]=> string(1) "y" ["front_page_limit"]=> int(10) ["toc"]=> string(17) "Table of Contents" ["copyright"]=> string(0) "" ["disqus"]=> string(5) "front" ["disqus_shortname"]=> string(15) "development-***" ["css_override"]=> string(25) "/content/css-override.css" ["og_image"]=> string(25) "/content/site_logo_og.png" ["bottom_links"]=> string(3) "Yes" ["bottom_links_first_text"]=> string(14) "<< First" ["bottom_links_prev_text"]=> string(9) "< Prev" ["bottom_links_next_text"]=> string(9) "Next >" ["bottom_links_last_text"]=> string(13) "Last >>" ["bottom_links_top_text"]=> string(11) "Back to Top" ["bottom_links_separator"]=> string(1) "|" ["base_url"]=> string(34) "http://testing.mcdougallhome.net//" ["rewrite_url"]=> NULL ["date_format"]=> string(5) "%D %T" ["twig_config"]=> array(3) { ["cache"]=> bool(false) ["autoescape"]=> bool(false) ["debug"]=> bool(false) } ["content_ext"]=> string(3) ".md" } string(16) "//DA/chapter-two" string(14) "DA/chapter-two" string(1) "/" string(14) "DA/chapter-two" string(48) "http://testing.mcdougallhome.net//DA/chapter-two" string(48) "http://testing.mcdougallhome.net//DA/chapter-two"

**Comment by PhrozenByte** [comment]
Thank you @smcdougall for providing the debug information, the problem will be fixed in the next release! :smiley:

**Comment by smcdougall** [comment]
Cool! :+1: I don't mean to point out all your bugs, really.  I'm just bringing things up as I come across them while I get my theme ready for 1.0 (and it's own new feature set). :sweat_smile:

**Comment by PhrozenByte** [comment]
Don't worry about it, it's a developers daily business to fix bugs, so please keep pointing out any problem or question you come across! :smile: We are always very glad to receive feedback, it's highly appreciated and we love to see people using our work :smiley:
