### ISSUE TITLE
Uncaught exception 'RuntimeException'

### ISSUE THREAD

**Issue by abr4xas** [picocms/Pico#279]
Hi there,

I'm testing pico Version 1.0.0-beta.1 and:

```php
Fatal error: Uncaught exception 'RuntimeException' with message 'Required "404.md" not found' in /var/www/pico/lib/Pico.php:670 Stack trace: #0 /var/www/pico/lib/Pico.php(293): Pico->load404Content('/var/www/pico/c...') #1 /var/www/pico/index.php(17): Pico->run() #2 {main} thrown in /var/www/pico/lib/Pico.php on line 670
```

My config.php

```php
/*
 * CONTENT
 */
 $config['date_format'] = '%D %T';            // Set the PHP date format as described here: http://php.net/manual/en/function.strftime.php
 $config['pages_order_by'] = 'alpha';         // Order pages by "alpha" or "date"
 $config['pages_order'] = 'asc';              // Order pages "asc" or "desc"
 $config['content_dir'] = 'content/';  // Content directory
 $config['content_ext'] = '.md';              // File extension of content files to serve
```

**Comment by theshka** [comment]
Do you have a file called `404.md` in your `content/` directory @abr4xas?

**Comment by abr4xas** [comment]
@theshka yes sir

**Comment by theshka** [comment]
I do not receive this error unless I delete my `404.md` from the `content-sample` directory, so I'm not sure why if you have the file there that it would be throwing the exception. 

Can you double-check these things: 
- Do you have a `base_url` set in `config/config.php`, or is what you posted the only portion of your config you have customized?
- Do you have the right permissions set on your custom `content/` directory? (i.e. `755`)
- Do you have a YAML header in the `404.md` file?
- Do you have URL rewriting enabled or disabled?

**Comment by abr4xas** [comment]
* Do you have a base_url set in config/config.php, or is what you posted the only portion of your config you have customized?

  * My `base_url` is `tma.local/pico`

* Do you have the right permissions set on your custom content/ directory? (i.e. 755)

  * Yes

* Do you have a YAML header in the 404.md file?
This is my `404.md`
```
---
Title: Error 404
Robots: noindex,nofollow
---
```
* Do you have URL rewriting enabled or disabled?
  * enabled


![captura de pantalla 2015-11-18 a la s 20 43 40](https://cloud.githubusercontent.com/assets/405484/11259604/1f9b1dbe-8e35-11e5-8072-cc10325aa36e.png)

**Comment by PhrozenByte** [comment]
Pico isn't able to find the content dir you specified. Is your `config.php` located in Picos root dir or in `config/config.php`?

**Comment by abr4xas** [comment]
@PhrozenByte in `config/`

**Comment by PhrozenByte** [comment]
Can you please give me the output of the page when adding
<p><code>var_dump($this->config, file_exists($this->getConfig('content_dir') . '404.md')); die();</code></p>
   to a new line **before** [line 354 of `lib/Pico.php`](https://github.com/picocms/Pico/blob/7b4ad7f23466bd54627154a888c9da3352e96a6c/lib/Pico.php#L352)? Please don't forget to remove the line afterwards.

**Comment by abr4xas** [comment]
Output:

```php
Warning: file_get_contents(/var/www/pico/content/404.md): failed to open stream: No such file or directory in /var/www/pico/lib/Pico.php on line 649

Warning: scandir(/var/www/pico/content): failed to open dir: No such file or directory in /var/www/pico/lib/Pico.php on line 1213

Warning: scandir(): (errno 2): No such file or directory in /var/www/pico/lib/Pico.php on line 1213
```

**Comment by PhrozenByte** [comment]
The content directory `/var/www/pico/content/` doesn't exist. Please check your installation directory.

**Comment by abr4xas** [comment]
The content directory exist

![captura de pantalla 2015-11-18 a la s 20 43 40](https://cloud.githubusercontent.com/assets/405484/11259604/1f9b1dbe-8e35-11e5-8072-cc10325aa36e.png)

https://github.com/picocms/Pico/issues/279#issuecomment-157915148

**Comment by PhrozenByte** [comment]
PHP unmistakable states that the directory `/var/www/pico/content/` either doesn't exist (<code>scandir(**/var/www/pico/content**): failed to open dir: **No such file or directory**</code> - i.e. your screenshot doesn't show `/var/www/pico`) or isn't visible to the PHP process.

This is a misconfiguration of your webserver. Please check your webserver configuration (this issue is *completely independent* of Pico) and make sure that the directory is accessible by your webserver/PHP process. Unfortunately the configuration of webservers is out of our scope.

**Comment by abr4xas** [comment]
thanks, folder permissions were changed.

**Comment by dav-m85** [comment]
@theshka @PhrozenByte A goot point here, we maybe should dispatch a message when the permissions are wrong but the directory exists.

Want a PR on this ?

**Comment by PhrozenByte** [comment]
The problem weren't wrong permissions of the content dir, but of Pico's root dir - otherwise the message would have been `Permission denied`, not `No such file or diectory`.

**Comment by dav-m85** [comment]
My bad. You're right.
