### ISSUE TITLE
parsedown-extra removes placeholder attribute from markdown content

### ISSUE THREAD

**Issue by edDimensi** [picocms/Pico#280]
Hi, I finally began to try to create a theme for pico and met a strange problem. All placeholder in the htm forms are removed...
My content in .md format
````
<form method="post" action="#">
	<div class="row uniform 50%">
		<div class="6u 12u(mobilep)">
			<input type="text" name="name" id="name" value="" placeholder="Name" />
		</div>
		<div class="6u 12u(mobilep)">
			<input type="email" name="email" id="email" value="" placeholder="Email" />
		</div>
	</div>
	<div class="row uniform 50%">
		<div class="12u">
			<input type="text" name="subject" id="subject" value="" placeholder="Subject" />
		</div>
	</div>
	<div class="row uniform 50%">
		<div class="12u">
			<textarea name="message" id="message" placeholder="Enter your message" rows="6"></textarea>
		</div>
	</div>
	<div class="row uniform">
		<div class="12u">
			<ul class="actions align-center">
				<li><input type="submit" value="Send Message" /></li>
			</ul>
		</div>
	</div>
</form>
````
![Image of problem](https://cloclo19.datacloudmail.ru/weblink/view/3nnASejZcCZg/img-2015-11-19-16-28-31.png?etag=33A18F819213F279C638607D36DBC7BCDA800946)
![Image of problem2](https://cloclo16.datacloudmail.ru/weblink/view/2R7UoV7quLmn/img-2015-11-19-16-32-14.png?etag=91CB813A019F05979CB2F813831477823DC17140)

**Comment by PhrozenByte** [comment]
Works just fine for me. Double-check your template, it's very likely that there's a typo or syntax error in your Twig template causing this.

![bildschirmfoto von 2015-11-19 15 22 11](https://cloud.githubusercontent.com/assets/920356/11273042/5e3fdc02-8ed1-11e5-9d3d-f715d67baec4.png)

**Comment by edDimensi** [comment]
I'll use the standard theme and the problem persists! I do not know what the problem is, help me! Somehow the word placeholder always deleted! If you write p1aceholder, the word remains. Deletes the whole word is placeholder !!
![Image of placeholder](https://cloclo20.datacloudmail.ru/weblink/view/2mYPqn2Ws6hS/img-2015-11-19-19-59-47.png?etag=9654FD7181FF4569BFE4E43BBF8E57156309319C)

**Comment by theshka** [comment]
I am able to replicate this issue @PhrozenByte. 
It appears to be solved in the latest `master` of erusev/parsedown-extra as per https://github.com/erusev/parsedown-extra/issues/53 and https://github.com/erusev/parsedown-extra/commit/cbd74e2e1fc8985f5bcafc5066bfa960caa60800

**Comment by edDimensi** [comment]
What me do? Wait ? I can fix it with something like guide "How to fix parsedown" ??

**Comment by PhrozenByte** [comment]
Ah, I see, I completely overlooked the "in .md format" part. My bad, sorry.

@theshka: [erusev/parsedown-extra](https://github.com/erusev/parsedown-extra) unfortunately seems to be a little bit abandoned regarding the deployment of new releases. We can either switch back to `dev-master` in our `composer.json` or draw attention of @erusev to this, a new release definitely makes things easier and more reliable (\*beckon @erusev\* :wink:)

**Comment by theshka** [comment]
Hopefully @erusev can release a `0.7.1` update before we release Pico `1.0.0` @PhrozenByte, otherwise it's probably best to use the `dev-master` and have this bug resolved? I guess we will wait and see which happens first :watch:

**Comment by edDimensi** [comment]
PhrozenByte thx you very much. I do what u me say and it now work great. Thx and sorry for my english. I must close this issue?

**Comment by PhrozenByte** [comment]
No, we'll close this as soon as we have a "real" (non-temporary) fix :smiley:

**Comment by erusev** [comment]
i released `0.7.1` - it should include the fix for this issue

**Comment by theshka** [comment]
Thanks for resolving that so quickly @erusev :+1:

**Comment by erusev** [comment]
@theshka it's been resolved for a long time, i should have tagged it in a release a long time ago

**Comment by PhrozenByte** [comment]
@erusev: Thank you! :smiley:
