### ISSUE TITLE
Pico/Wiki Image Assets

### ISSUE THREAD

**Issue by theshka** [picocms/Pico#287]
This issue contains the image assets for Pico's Wiki. 

![pico_wiki](https://cloud.githubusercontent.com/assets/640217/11355145/5293edea-9218-11e5-84eb-0c5d26777c6a.jpg)

**Comment by theshka** [comment]
Showcase
![rmvo nl](https://cloud.githubusercontent.com/assets/640217/11447873/86ed0b32-9513-11e5-9d8e-2d1049ad37a4.png)
![eoy ee](https://cloud.githubusercontent.com/assets/640217/11447872/86e95816-9513-11e5-8726-020184d3ef1f.png)
![botwiki org](https://cloud.githubusercontent.com/assets/640217/11447875/86ef0ea0-9513-11e5-8fb8-1e9c75541659.png)
![pjrvs com](https://cloud.githubusercontent.com/assets/640217/11447871/86e8a13c-9513-11e5-9dd1-99fce6881dd4.png)
![whitesand gapt vn](https://cloud.githubusercontent.com/assets/640217/11447874/86ee87e6-9513-11e5-8752-ee01bf6fad8a.png)
![neocrey com](https://cloud.githubusercontent.com/assets/640217/11447876/8701f254-9513-11e5-82f8-df9aa30208ff.png)

**Comment by theshka** [comment]
![Tweet Button](https://cloud.githubusercontent.com/assets/640217/11483728/b0842918-976f-11e5-9185-d53261b3125b.png)

**Comment by theshka** [comment]
![picoscreenshot](https://cloud.githubusercontent.com/assets/640217/11484528/1cba1878-9774-11e5-8f37-b139392c83fb.png)

**Comment by PhrozenByte** [comment]
![pico-1 1](https://cloud.githubusercontent.com/assets/920356/17342119/f5a85ee8-58f7-11e6-856e-cd72f76cec61.png)
