### ISSUE TITLE
[Feature Idea] Internal 404 document

### ISSUE THREAD

**Issue by smcdougall** [picocms/Pico#299]
Now that my theme is complete, I've spent today rolling out `Pico 1.0.0-beta.2` onto my server.  I encountered two small issues during this, so I figured I'd open some Issues with my thoughts. :wink: 

I noticed that if there is no `404.md`, and your page 404's, Pico will throw an exception.  There's no mention of this in the Docs, it's purely suggested that `404.md` is an optional item.

I don't know about you, but I don't ever really modify `404.md`, because if I've done my job right, it will almost never show up.  I just use the default `404.md` provided in Pico's `content-sample`.

To me, `404.md` feels unnecessary.  I was thinking, why not bundle this page (or generate it) internally if it's not found in the content folder?  This way if someone wants to modify their 404 page, they can just like always, but if they don't include one, there's no ill effects.

**Comment by PhrozenByte** [comment]
This feature will be shipped with Pico 1.1, see 00603f6 for implementation details. For feedback about this feature, please refer to #334. Thanks @smcdougall for bringing this up!
