### ISSUE TITLE
Conflicting "content-sample" and "content" in Docs

### ISSUE THREAD

**Issue by smcdougall** [picocms/Pico#300]
This has bugged me for awhile.  Since `Pico 0.9`, the Docs have referenced the `content-sample` folder as if it's the place you should put your content.  There's only a little tiny note after many paragraphs of `content-sample` that reads "you should create your own `content` directory".

I really feel this should be reworked.  The first paragraph should be "create your own `content` directory" and from there all the following information should say `content` not `content-sample`.

The `content-sample` directory shouldn't really be changed.  It's a *sample*.  It should stay unmodified as a reference, be copied and renamed to `content`, or just deleted altogether by the user.  This is especially true with `Pico 1.0` since it will automatically use the `content` directory instead if it exists.

I'd be willing to make these changes if you guys are in agreement with me.

**Comment by Lomanic** [comment]
:+1: even delete the `content-sample` dir after `content` dir is created.

**Comment by smcdougall** [comment]
If you mean Pico should delete `content-sample` by itself I'd have to disagree.  Something about letting it delete it's own (or any) files would be a little worrying to me.  Also, it should really be up to the user.  They may want to keep it as reference after all.

**Comment by Lomanic** [comment]
Excuse me, no, I wanted to write that it should say in the documentation that once user has created the `content` dir he can (and should?) delete `content-sample`.

**Comment by smcdougall** [comment]
Oh.  Yeah, I agree then, lol. :sweat_smile:

**Comment by PhrozenByte** [comment]
It neither has any advantage nor disadvantage to delete the `content-sample` folder, it's just usually re-created when updating Pico. However, your suggestions sound reasonable, we're looking forward to your PR :+1: :smiley:

**Comment by smcdougall** [comment]
Acknowledged, Captain. :wink:  :+1:

**Comment by smcdougall** [comment]
PR #303 & #304 :smiley:
