### ISSUE TITLE
Pico executes from real location of "index.php" when symlinked.

### ISSUE THREAD

**Issue by smcdougall** [picocms/Pico#301]
Now that my theme is complete, I've spent today rolling out Pico 1.0.0-beta.2 onto my server. I encountered two small issues during this, so I figured I'd open some Issues with my thoughts. :wink:

On my server I have one `pico` folder, but many Pico sites.  I've symlinked the relevant files into each respective site's directory.  This way, I can have one, easy to update, instance of Pico (and NotePaper), but individual content, assets, and config for each site.  If Pico were eventually package for a Linux distro, I imagine it would work similar to this (with the real Pico files residing in `/usr/share/` for example).

This works great, but has one flaw.  Pico executes in whatever location the *real* `index.php` exists.  Even though I have symlinked `index.php` into a different folder, it still executes (and uses the content, assets, config, etc) in the original folder.  This is a little weird as, under Linux anyway, symlinks are usually treated as if they *are* located at the symlink, inheriting the path of the link, not the original file.

I'm not sure if this is an issue with Pico (such as the way directories / locations are handled internally), or an issue with PHP (or my webserver configuration).  I *do* know that PHP can see right through my symlinks, I just don't know if the issue is PHP itself or how Pico is obtaining the directory structure from PHP.

Anyway, I thought I'd bring this up here because it's a little peculiar.  I've worked around the issue by *hard* linking the file instead, but this isn't really how I wanted to have it set up.

**Comment by PhrozenByte** [comment]
This is intended behavior. However, with Pico 1.0 we completely overhauled initialization, therefore it's very easy for you to realize such a shared Pico instance by yourself. Simply create a custom `index.php` by copying Pico's original one and changing [line 16](https://github.com/picocms/Pico/blob/2e6ce893e4bf1291018f116ecbaec382367b8f43/index.php#L16) to something like `dirname($_SERVER['SCRIPT_FILENAME'])`.

**Comment by smcdougall** [comment]
Okay, cool, I'll have to try that later. :smile: 

I figured it might be something that simple since `index.php` is so streamlined (not that I knew the PHP to do it).

Slightly related, but what *about* packaging.  Is having Pico packaged for a distro something that would ever be on the agenda?  I'd probably be able to create an [Arch](https://www.archlinux.org) package for the [AUR](https://aur.archlinux.org/) easily enough.  I know it isn't something that's really *necessary* due to Pico's simplicity, but sometimes people just like having updates handled by their package manager. :wink:

**Comment by smcdougall** [comment]
Hmm... changing the root directory in `index.php`, but *not* changing the `autoload.php` seems to have another benefit too... I no longer need to symlink the `vendor` or `lib` folders since they'll still execute from their original locations. :smiley: 

(I assume this was the reason you didn't mention the autoload line, I just happened to notice it also had a seperate `__DIR__` declaration.) :wink:

Now if only I could do the same for the `themes` folder. :laughing: The external resources like css and images are loaded through apache though, so that would never work.
