### ISSUE TITLE
Page Title Issues

### ISSUE THREAD

**Issue by chinanoahli** [picocms/Pico#302]
Does every pages need to have a title?
I create some pages without title, but on the top right corner of the page, they still took some place, if I create too much pages, it will have an invisible long long list on the top right corner, how can I fix it?

**Comment by smcdougall** [comment]
To answer your initial question, no, every page doesn't *need* a title.  How a page without a title will display however depends on your theme.  The default theme **does** expect you to have a title for each page though.  It uses the title to generate the text for the navigation links, but nothing else.  Other themes may use the page title more prominently though.

If your desire is to not have these pages show up in the navigation *at all*, you could modify your theme to omit pages without titles.  You'd do this by wrapping the section that generates your navigation in:

`{% if page.title %}...{{ page.title }}...{% endif %}`

In the default Pico theme, you could simplify this by adding a condition to the for loop that generates your navigation.  The modified section of `index.twig` would look like this:
```twig
                    {% for page in pages if page.title %}
                        <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                    {% endfor %}
```

Hope this helps. :wink:

**Comment by chinanoahli** [comment]
It help a lot! Thx!
I'm not familiar with php at all :+1:

**Comment by smcdougall** [comment]
Glad to hear it. :+1: 

Although Pico is written in PHP, your theme templates are actually written in a template engine called Twig.  If you're interested in learning more about Twig, you can read it's Documentation at http://twig.sensiolabs.org/.  And of course you can learn more about how it applies to Pico in Pico's own [Documentation](http://picocms.org/docs.html).

You can also check out my [NotePaper Theme](https://github.com/smcdougall/NotePaper) here on GitHub ([Demo Website](http://development.sjmcdougall.com/pico-themes/NotePaper/)) for a more intermediate example of coding in Twig.
