### ISSUE TITLE
Running on a Windows localhost

### ISSUE THREAD

**Issue by bpgs** [picocms/Pico#307]
I'm testing pico 1.0.0 on a Windows localhost and see in the HTML-sourcecode

     <script src="http://bursch.localhost\/themes/default/scripts/modernizr-2.6.1.min.js"></script>

obvouisly there is something wrong with the bachslashes.

**Comment by PhrozenByte** [comment]
Fixed in v1.0.0 (will be released tomorrow). Thank you for reporting this! :+1:
