### ISSUE TITLE
PicoEditor - no proper logout, if "$config[ 'PicoEditor' ]['url']" not set to default (admin)

### ISSUE THREAD

**Issue by ufgum** [picocms/Pico#319]
public function onRequestUrl(&$url)
 {...
 // are we looking for admin/logout?
        if ($url == 'admin/logout') {
            $this->is_logout = true;
        }
    }

should look like this:

public function onRequestUrl(&$url)
 {...
 // are we looking for admin/logout?
        if ($url == $this->adminUrl . '/logout') {
            $this->is_logout = true;
        }
    }

**Comment by PhrozenByte** [comment]
Thank you for your bug report! Starting with Pico 1.1 we'll ship a brand-new, official admin plugin developed from scratch, so please stay in touch. Please don't be confused that I'll close and label this issue as *Invalid* - it doesn't affect Pico's core. However, as said, we'll address this in our upcoming new admin plugin. :smiley:
