### ISSUE TITLE
How to provide plugins?

### ISSUE THREAD

**Issue by ufgum** [picocms/Pico#320]
hi there,

im not used with github. I made some plugins and put it [here](https://github.com/ufgum)
How to show them in the [plugin section?](https://github.com/picocms/Pico/wiki/Pico-Plugins)

There will come some more pluings...

**Comment by PhrozenByte** [comment]
Any GitHub user can [edit our Wiki](https://github.com/picocms/Pico/wiki/Pico-Plugins/_edit) - if you have something to share, please go ahead and add it to the plugins/themes list! :smiley:

**Comment by ufgum** [comment]
Ok. i did it...and did not messed up the wiki :-)
Thank you!
