### ISSUE TITLE
Markdown Info

### ISSUE THREAD

**Issue by ufgum** [picocms/Pico#321]
I was thinking about develop a plugin, to better handle the div block elements with markdown, because I use bootstrap an there is lot of need for it. 

So on your website you point the user to that page for the pico markdown: [DARING FIREBALL](http://daringfireball.net/projects/markdown/syntax)

I thougt you use the markdown from this site, and they says:
`Note that Markdown formatting syntax is not processed within block-level HTML tags. E.g., you can’t use Markdown-style *emphasis* inside an HTML block.`

But I did now found another information on this page:
[PHP Markdown Extra](https://michelf.ca/projects/php-markdown/extra/)

He tells, to just put `markdown="1"` inside the div element and it will be processed. Surprisingly that just works. So you might point the users who read on your website to the right page, where your markdown processor is documented. To get all the information, what's possible with it.

**Comment by PhrozenByte** [comment]
Thank you for reporting this! :+1:

**Comment by smcdougall** [comment]
Wow, there's a lot of neat stuff in there.  I had no idea that "Markdown Extra" had all those features, I've only read the original "Daring Fireball" documentation.  `markdown="1"` seems especially helpful, so thanks for the heads up!
