### ISSUE TITLE
PHP Server Doesn't Honour .htaccess or Friendly URLs

### ISSUE THREAD

**Issue by coofercat** [picocms/Pico#325]
It's great to see Pico 1.0 :-)

I just tried to use it with the PHP built in server (which is my usual way to use Pico on my laptop). I notice that it doesn't seem to be able to handle 'friendly URLs', and it doesn't honor the new .htaccess security settings.

This all matters if you've put images or downloadable files in the content directory. These days, those files become inaccessible in you run your site with Apache, but isn't apparent if you're using the PHP server.

Thankfully, you can 'simulate' Apache with the PHP server using a 'router'. I can't claim this is especially well tested, bit it seems to work:
```
<?php

# .htaccess denies a bunch of directories
if(preg_match('/^\/(config|content|content-sample|lib|vendor)\//', $_SERVER['REQUEST_URI'])) {
        # Return 404
        $_SERVER['QUERY_STRING'] = '404';
} else {
        # .htaccess allows direct access to any files
        # (as long as they're not in the directories denied above)
        if (file_exists(__DIR__ . '/' . $_SERVER['REQUEST_URI'])) {
                return false; // serve the requested resource as-is.
        }
        $_SERVER['PICO_URL_REWRITING'] = 1;
        $_SERVER['QUERY_STRING'] = urlencode($_SERVER['REQUEST_URI']);
}
include __DIR__ . '/index.php';
```
Save this file out as "routing.php" in the root of your Pico install, and then run the PHP server like this:

`php -S localhost:8080 routing.php`

**Comment by PhrozenByte** [comment]
Thank you for pointing this out @coofercat!

Just to re-emphasize this: Please don't forget that "PHPs built-in web server is for development and testing purposes only" (see Pico's `README.md`/user docs). The [PHP manual](https://secure.php.net/manual/en/features.commandline.webserver.php) additionally says:

> This web server was designed to aid application development. It may also be useful for testing purposes or for application demonstrations that are run in controlled environments. It is not intended to be a full-featured web server. It should not be used on a public network.
