### ISSUE TITLE
Update for pico-navigation plugin

### ISSUE THREAD

**Issue by khartahk** [picocms/Pico#326]
I've updated [pico-navigation](https://github.com/ahmet2106/pico-navigation) in a [fork](https://github.com/khartahk/pico-navigation) to work with 1.0 without the deprecated plug-ins and sent a pull request to the author. But I don't think he is active any more. Can someone tell me if this plug-in is even needed in the 1.0 Pico or does Pico now have something similar built in?

**Comment by PhrozenByte** [comment]
A plugin was never required to do something like this :wink:

You can implement arbitrary deep tree navigations completely without a plugin using [Twig](http://twig.sensiolabs.org/documentation). You could either use recursion (refer to [Twig's `macro` feature](http://twig.sensiolabs.org/doc/tags/macro.html) or simply use includes; for an example see our "Recursive table of contents" [cookbook entry](http://picocms.org/cookbook/); basically you just have to port the plugins sourcecode to Twig) or an iterative algorithm (any recursive algorithm can be implemented using just iterations :smile:).

However, usually you don't want arbitrary deep tree navigations anyway. You're probably searching for a navigation that supports child items (i.e. two levels max). This is pretty easy to implement:
```twig
<ul>
    {% set parent_page = null %}
    {% for page in pages if page.title %}
        {% if parent_page and (not (page.id starts with parent_page)) %}
            {% set parent_page = null %}
            </ul></li>
        {% endif %}

        <li{% if page.id == current_page.id %} class="active"{% endif %}>
            <a href="{{ page.url }}">{{ page.title }}</a>

            {% if (not parent_page) and (page.id ends with '/index') %}
                {% set parent_page = page.id|slice(0, -6) %}
                <ul>
            {% else %}
                </li>
            {% endif %}
    {% endfor %}
    {% if parent_page %}</ul></li>{% endif %}
</ul>
```

**Comment by khartahk** [comment]
Thank you for this. I'll try it this way. Just one more question - not directly related but just an extension of this - how can I include multiple template files in one file so that I don't have to have this menu code duplicated in all different templates but just stored in one file that when changed is then reflected in all the templates that are using it.

**Comment by PhrozenByte** [comment]
You mean [Twig's `include`](http://twig.sensiolabs.org/doc/tags/include.html)?

**Comment by khartahk** [comment]
[Twig's `include`](http://twig.sensiolabs.org/doc/tags/include.html) works nicely. The tree navigation puts all the pages on the same level so I'll have to dig into that a little bit more to understand how it should work but thanks for the direction.
