### ISSUE TITLE
Missing Tag in Meta Header

### ISSUE THREAD

**Issue by 3schade** [picocms/Pico#328]
I am missing a tag in specify certain meta attributes of the "*.md markdown" pages.

From time to time i wanna work on a page but if i create a new *.md content file. It will be published just right in that moment. I prefer to have a new tag "Published" as you can see bellow

---
Title: Welcome
Description: This description will go in the meta description tag
Author: Joe Bloggs
Date: 2013/01/01
Robots: noindex,nofollow
Template: index
Published: NO|YES|(on date)|(from date to date)
---

**Comment by PhrozenByte** [comment]
This is nothing for Pico's core, but can easily be implemented using a plugin. As far as I can tell there's no plugin for this at the moment. Below is some (untested!) example code realizing a `Published: NO|YES` meta header. You can use it as a starting point to extend it to your own needs.

```php
class PicoPageDrafts
{
    public function onMetaHeaders(array &$headers)
    {
        $headers['published'] = 'Published';
    }

    public function onPagesLoaded(
        array &$pages,
        array &$currentPage = null,
        array &$previousPage = null,
        array &$nextPage = null
    ) {
        // TODO: also check $currentPage, $previousPage, $nextPage; support dates and date ranges
        foreach ($pages as $pageId => $page) {
            if (isset($page['meta']['published']) && (strtolower($page['meta']['published']) === 'no')) {
                unset($pages[$pageId]);
            }
        }
    }
}
```
