### ISSUE TITLE
Clicking the page title leads to 404 not found

### ISSUE THREAD

**Issue by sonst-was** [picocms/Pico#329]
Hi there,

so I just downloaded and installed pico for a friend (its amazingly simple!) and ran into the first strange thing.

I've made a `content` folder and placed a custom `index.md` file in it. It works fone so far, except when I click the page title, I'll get an 404 page not found error. The URL change from `pico/` to `pico/index`.

So, my question is, what am I doing wrong?

**Comment by PhrozenByte** [comment]
Do you get Pico's 404 page or your webserver's 404 page?

**Comment by sonst-was** [comment]
It looks like my webservers 404:

> Not Found
> 
> The requested URL /pico/index was not found on this server.
> 
> Apache Server at domain.de Port 80

**Comment by PhrozenByte** [comment]
URL Rewriting isn't working. Make sure Apache's `mod_rewrite` module is enabled. What are the contents of your `config/config.php`? I assume you forced URL rewriting to be enabled.

**Comment by sonst-was** [comment]
I had URL rewriting forced to be enabled once, but currently it is not set (commented out). Had to change the file extension, because .md is not allowed.
[config.txt](https://github.com/picocms/Pico/files/145471/config.txt)

When using the sample content mod rewriting works, it shows e.g. `/pico/sub/index` as URL

**Comment by PhrozenByte** [comment]
So, the page title currently links to `/pico/index`, whereas Welcome links to `/pico/?index`, Sub Page Index to `/pico/?sub/index` and Sub Page to `/pico/?sub/page`? Try `Strg` + `F5`.

**Comment by sonst-was** [comment]
No, basicly everything links to mod rewritten URLs, the page title and Welcome to `/pico/index`, the Sub Page Index to `/pico/sub/index` and the Sub Page to `/pico/sub/page`.

With the exeption of links to `/pico/index` all other links work.

**Comment by PhrozenByte** [comment]
Hmmm... You tried a force reload with `Ctrl` + `F5` when viewing the 404 page, right?

Because only `index` is affected, it's maybe a side effect with Apache's strange `MultiViews` feature... Please try replacing `Options -Indexes` in your `.htaccess` with `Options -Indexes -MultiViews`.

**Comment by sonst-was** [comment]
Yes, tried force-reloading (and another browser, which shouldnt be affected by old cache stuff neither).

But adding -MultiViews to the htacces worked ;) Thanks for the really fast help!

**Comment by PhrozenByte** [comment]
Apache's `MultiViews` "feature" really is a curse... Actually not a bug of Pico, but it's probably a good idea to make sure `MultiViews` are disabled. I'll update Pico's `.htaccess`. Thank you for reporting this!
