### ISSUE TITLE
combined bug fix

### ISSUE THREAD

**Issue by JazzMaster** [picocms/Pico#331]
Im noticing some "IRL doesnt match what the cereal box sez" situation. So, Ive setup a demo site. (this is kick arse...) I have a 'page' and a 'blog' to mimic wordpress setup. I have a custom (small) logo header and some ipsums. Ive made some changes to the CSS.
I am however, noticing some minor glitches.

Nav-menu is mistakenly a YUUGE header.[I moved this to the content area]
When setting up a blog, all subfolders and local files get skipped. You have to add the blog link by hand(the 

blog by itself will function ok).
There is no way when perusing the blog list to skip the index page in the list of blog posts.

This may help some folks out there. Documentation? Try here: 
http://www.w3schools.com
Use the basics. Then learn or use or adapt to markdown. This is easier than making bread people! So far I dont have extra themes, but minor css shouldnt be that difficult to navigate.

And I think there are live editors online somewhere...
Most of your issues may be misunderstanding of the code.

**Comment by JazzMaster** [comment]
I cant attach a ZIP?

**Comment by JazzMaster** [comment]
ANYHoo..there are some advantages to owning domains and websrvers.... Ive linked the file on my main page. CSS might need some tweaks. southernhedgehogs.org The WWW will not redirect due to a cert issue glitch with LE when I had the cert made. Should be fixed in a few months.

**Comment by smcdougall** [comment]
Okay, so taking a look at https://southernhedgehogs.org/pico/, I'm guessing that you're trying to build your site off of the default Pico theme.  While this is okay, please note that the default theme is older, barebones, and really just meant to get you started.  We're even discussing replacing it in a future release (https://github.com/picocms/Pico/issues/270).

The default theme is really meant to be a simplistic sample for you to look at to get a quick idea of how Pico and Twig work.  The real power of using Pico comes from leveraging Twig templates (Pico "Themes") to customize Pico to your liking.  Obviously you've messed with this a little with the changes you've made so far.

You'll also notice in the [Pico Documentation](http://picocms.org/docs/), the very first line under [Blogging](http://picocms.org/docs/#blogging) reads: "Pico is not blogging software".  That being said, that doesn't mean that it *can't* be used for blogging, but as you're discovering, it just takes a little extra effort.  No part of Pico is pre-configured for blogging, and the examples provided in the docs are just that, examples.  They should get you started, but you'll have to invest a little more time to refine the behavior of your site to your liking.  Personally, I find this to be Pico's biggest advantage over Wordpress and other solutions.  With a little effort, you can customize *everything* to meet your needs.

Me or @PhrozenByte would be happy to help you solve individual problems and Twig conundrums, but we cannot write your entire site for you. :wink: You should check out http://twig.sensiolabs.org/ for quite literally *all* the knowledge you could ever need about writing Twig templates.  Their documentation is very good.  You can use what you learn there together with the [Pico Docs](http://picocms.org/docs/) to figure out how the two work together.

Finally, you can check out the [Customization Section](http://picocms.org/customization/) of the website, as well as the [Plugins](https://github.com/picocms/Pico/wiki/Pico-Plugins) and [Themes](https://github.com/picocms/Pico/wiki/Pico-Themes) sections of the wiki for some more "ready-to-go" options.

Personally, I write the [NotePaper Theme](https://github.com/smcdougall/NotePaper) ([Example Site](http://development.sjmcdougall.com/pico-themes/NotePaper/)), which has some basic blog-like functions.  I've got a new `1.5` release coming out this week (possible later today if I get it together), so you can check back for that soon.

Ultimately, if you find Pico doesn't suit you needs or is too much work for you right now, come check us out again when we reach version 1.1.  We've got some dedicated blogging features [planned](https://github.com/picocms/Pico/issues/270) for that release.

I hope this helps get you going in the right direction.  Again, we're happy to help as long as you are willing to keep the discussion kind and courteous.
