### ISSUE TITLE
compozer

### ISSUE THREAD

**Issue by JazzMaster** [picocms/Pico#333]
you ask us to run or build this. most hosts dont allow it.(phar extension not installed at server level)

[christopher]$ composer update
-bash: composer: command not found

you package it in such a case(or aim to) but theres no way to reload it.
even simple comment forms need to reload this. So how are we supposed to do it?

anchorCMS depends on composer too so this would be nice to fix.

**Comment by PhrozenByte** [comment]
Using `composer` is completely optional, please refer to the "Install" and "Upgrade" sections in our `README.md`, download page and/or user docs.
