### ISSUE TITLE
How to create multilingual web site?

### ISSUE THREAD

**Issue by desvu** [picocms/Pico#335]
How to create multilingual web site?

**Comment by PhrozenByte** [comment]
This depends on how you want to create a multilingual website :wink:

The easiest solution might be to create corresponding subdirectories in your `content` directory (e.g. `content/en`, `content/de`, `content/jp`...) and duplicate the contents. With a simple Pico plugin or a appropriate `.htaccess` `RewriteRule`, you can redirect requests to your index page (i.e. http://example.com/pico/) to the appropriate language subdirectory (e.g. http://example.com/pico/en/). In addition, you should extend your theme to provide a language selector. Pico has no built-in `i18n` capabilities, but we're planning to create a official plugin for this with Pico 1.1.

**Comment by desvu** [comment]
do not forget meta tags
rel="alternate" hreflang=""
:)
