### ISSUE TITLE
ISO8601 formatted date doesn't work properly

### ISSUE THREAD

**Issue by csholmq** [picocms/Pico#336]
I have used the ISO8601 format for all my YAML headers (e.g. 2016-03-15, rather than 2016/03/15) and am facing issues where most, but not all, of my pages are sorted according to date.

I also saw issues where `page.date_formatted` translated to 1970-01-01 even though  `page.date` was correctly timestamped and `page.date|date("Y-m-d")` works fine.

This used to work in 0.8. Anyone else experiencing this?

**Comment by PhrozenByte** [comment]
Pico 1.0 should work just fine with ISO-8601 dates. Can you please provide some concrete examples of dates with which you experience problems and provide the respective outputs of
- `{{ page.date }}`,
- `{{ page.date_formatted }}`,
- `{{ page.date|date("Y-m-d") }}`,
- `{{ page.time }}` and
- `{{ page.time|date("Y-m-d") }}`

Can you please also provide the value of your `date_format` config variable (i.e. the `$config['date_format']` line in your `config/config.php`)?

**Comment by csholmq** [comment]
`$config['date_format'] = '%Y-%m-%d';`

This is my YAML for the current page:
```
---
Title: VSCode packages
Description: As a follow up to my Atom packages...
Author: Sebastian Holmqvist
Date: 2016-03-10
---
```

And this is the output:

> date: 1457539200
> date_formatted: 1970-01-01
> date|date: 2016-03-10
> time: 
> time|date: 2016-03-16

**Comment by PhrozenByte** [comment]
Fixed with [Pico 1.0.2](https://github.com/picocms/Pico/releases/latest). Thank you for reporting this @csholmq! :+1:

**Comment by csholmq** [comment]
Thank you for patching! :+1:

**Comment by csholmq** [comment]
@PhrozenByte Actually, this fixed the parsing, but my pages are still sorted funky.

**Comment by PhrozenByte** [comment]
What does "funky" exactly mean?

Can you please provide the `pages_order_by` and `pages_order` config variables (i.e. the line with `$config['pages_order_by']` and `$config['pages_order']` in your `config/config.php`)? What exact `Date` meta header values result in the unexpected behavior and what's the behavior you expect (i.e. the actual order and the expected order of the pages)? Please also provide the above date outputs of all affected pages (`{{ page.date }}`, `{{ page.date_formatted }}`, and so on); don't just include the wrongly ordered pages, but also the respective previous and next page (or: simply include all pages).

**Comment by csholmq** [comment]
Apologies. During my debugging I reconfigured to `$config['pages_order_by'] = 'date';` which just happened to sort my pages **almost** chronologically due my naming. This was a false alarm!
