### ISSUE TITLE
error and hearder reloading

### ISSUE THREAD

**Issue by JazzMaster** [picocms/Pico#337]
this obviously breaks plugins but isnt per se a plugin issue.
the issue is with pico refactoring(or attempting to) the header already in flight.

for example 404:
obviously load the 404 error page if present(or allow htaccess to do this for you)
the server has already set the error, no need to do this in any other way.

minify works as a drop-in plugin but as a direct result line 306 must be "remmed out" because of the already inflight header.

other plugins break due to similar manners.
This is due to how php is running on the server and most people CANT change it.
RAM is faster than disk anyhoo.

**Comment by PhrozenByte** [comment]
:confused: :question:

Sorry, but your English is really hard to understand and I've absolutely no idea what you're talking about right now. Please rephrase your issue.

Regarding your comment in \#323: Please don't comment on random issues which aren't relevant for your problem. I've deleted your comment there. We don't ignore you, quite the opposite is the case.
