### ISSUE TITLE
excluding blog articles from navigation

### ISSUE THREAD

**Issue by marctilman** [picocms/Pico#338]
Hello Pico!

I'm having trouble excluding blog articles from my navigation.

The documentation suggests to do it like this:
`{% for page in pages if page.title %}`
**&nbsp;&nbsp;&nbsp;`{% if not page starts with "blog/" %}`**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<li{% if page.id == current_page.id %} class="active"{% endif %}>`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<a href="{{ page.url }}">{{ page.title }}</a>`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`</li>`
**&nbsp;&nbsp;&nbsp;`{% endif %}`**
`{% endfor %}`

I tried both `{% if not page starts with "blog/" %}` and `{% if not page.id starts with "blog/" %}`, but either way the menu disappears.

Doing it this way works, but it is messy:
`{% for page in pages if page.title %}`
**&nbsp;&nbsp;&nbsp;`{% if page.id starts with "blog/" %}`**
**&nbsp;&nbsp;&nbsp;`{% else %}`**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<li{% if page.id == current_page.id %} class="active"{% endif %}>`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<a href="{{ page.url }}">{{ page.title }}</a>`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`</li>`
**&nbsp;&nbsp;&nbsp;`{% endif %}`**
`{% endfor %}`

Did I misinterpret the documentation or is this a bug?

Kind regards,
Marc

**Comment by PhrozenByte** [comment]
This is a bug in our documentation. Thank you for reporting this! :smiley:
Please try `{% if not (page.id starts with "blog/") %}...{% endif %}`.

**Comment by marctilman** [comment]
This works, thank you!
