### ISSUE TITLE
Bad nativ CSS for <dt><dd>

### ISSUE THREAD

**Issue by Marcussacapuces91** [picocms/Pico#339]
Hi,

I use definition list in markdown following the syntax : 
> title
> : description
> : description again

but the style is "un-nice" with a mis-alignment.

Sorry, I have no proposition for that, I suggest something wrong in css.

- Pico version : 1.0.2
- No plugins

**Comment by PhrozenByte** [comment]
Pico's default theme didn't support definition lists, i.e. they weren't styled at all. I've now added a very basic CSS rule (will be released with Pico 1.0.3), but please keep in mind that Pico's default theme actually isn't intended to be used for a productive website, it's more a starting point for your own theme. Thank you for reporting this anyway @Marcussacapuces91! :+1:
