### ISSUE TITLE
Reverse proxy over https protocol and base URL building

### ISSUE THREAD

**Issue by Robby-** [picocms/Pico#344]
I'm using/testing Pico behind an nginx reverse proxy.

The setup is as follows:
nginx server A, which is doing all the proxying.
nginx server B, which has Pico on it.

The problem is the following:
nginx server A accepts both `http` and `https` client requests, but when server A is proxying requests to server B, they are internally using `https` among themselves. This seems to break with Pico due to how it tries to build the base URL, and causes `https` URLs to be returned to the client, even if they requested an `http` URL.

This problem became apparent because the certificate is currently self-signed and the theme won't load because Pico is returning `https` URLs for it.

**Comment by Robby-** [comment]
I just had the of trying `$config['base_url'] = '/';` and that seems to work around the issue.

**Comment by PhrozenByte** [comment]
Thank you @Robby- for reporting this! :+1:
