### ISSUE TITLE
No "/index" in links in html code to index.md files

### ISSUE THREAD

**Issue by Robby-** [picocms/Pico#347]
It would be nice if links to `index.md` files that are generated automatically by Pico would not have `/index` appended to them in the html code. Since manually accessing the links like `http://site/sub` and `http://site/sub/` work fine too, it would make the URL a bit shorter to not include those, and also make it more uniform/consistent across the site if the site maintainer/owner has pages on it that provides links to other pages (but does not include the `/index` part in the links), which in turn probably also provides less clutter in search engines when they index the site and users look for content, as now they may get URLs ending with `/index` and URLs without it, both going to the same page anyway.

**Comment by PhrozenByte** [comment]
Thank you @Robby- for sharing your idea! :+1:

@all, feedback is appreciated

**Comment by smcdougall** [comment]
I agree.  Although I don't notice it a lot, that `/index` does bug me when it occasionally shows up.  I've never really thought about it too much, but now it's going to bother me, lol

**Comment by PhrozenByte** [comment]
This feature will be shipped with Pico 1.1, see 1b3ef75 for implementation details. For feedback about this feature, please refer to #334. Thanks @Robby- for bringing this up!

**Comment by Robby-** [comment]
@PhrozenByte and thank you for fixing it so fast. :)
