### ISSUE TITLE
Eliminate redundant calls to fonts.gstatic.com

### ISSUE THREAD

**Issue by nydame** [picocms/Pico#348]
I don't understand why this is happening, but my nascent Pico site (still in development at http://162.243.137.30) makes 4 - 6 calls to fonts.gstatic.com when it is loaded. (See screenshot of Firefox inspector.
![screen shot 2016-04-24 at 9 33 31 pm](https://cloud.githubusercontent.com/assets/1393027/14774154/bb052430-0a67-11e6-9f1f-e5d51000c758.png)
) Is this necessary?

Again, I have no idea why this is happening, so I don't have any recommendations as to how to stop this from happening. Thanks for advance to anyone who can fix this!

**Comment by PhrozenByte** [comment]
Sort of. Pico's default theme uses the "Open Sans" font by default, which is [loaded](https://github.com/picocms/Pico/blob/v1.0.2/themes/default/index.twig#L13) via [Google Fonts](https://fonts.googleapis.com/css?family=Open+Sans:400,700). You can use another font or provide a local copy of the `.woff2` file (provided the license allows that, I don't know that) with your theme. Please keep in mind that Pico's default theme actually isn't intended to be used for a productive website, it's more a starting point for your own theme.

**Comment by nydame** [comment]
Got it. Thanks for your response.
