### ISSUE TITLE
How to implement a contact form?

### ISSUE THREAD

**Issue by marciotoledo** [picocms/Pico#356]
I'm learning about Pico and I'd like know if have some article or docs about Contact Forms in Pico.

Thank you.

**Comment by PhrozenByte** [comment]
You can find two plugins in our [Wiki](https://github.com/picocms/Pico/wiki/Pico-Plugins) from third-party developers implementing a contact form for Pico. Alternatively you can use one of the (free or paid) contact form services out there (just google for it), for which you often just have to include a HTML and/or JavaScript snippet.

**Comment by marciotoledo** [comment]
Ok, great. I will try the plugins.
Thank you.
