### ISSUE TITLE
Markdown extra Special Attribute doesn't seems to be supported

### ISSUE THREAD

**Issue by Narann** [picocms/Pico#361]
This in markdown:

```markdown
[QT](http://qt.nokia.com/){lang=en}
```

Is generated as this:

```html
<a href="http://qt.nokia.com/">QT</a>{lang=en}
```

So the `{lang=en}` is a visible text.

Pico page states [PHP Markdown extra](https://michelf.ca/projects/php-markdown/extra/#spe-attr) is supported. So I was expecting something like this:

```html
<a href="http://qt.nokia.com/" lang="en">QT</a>
```

Am I wrong somewhere?

Thanks in advance!

EDIT: Pico version 1.0.3, no plugins

**Comment by PhrozenByte** [comment]
Unfortunately this isn't supported by [erusev/parsedown-extra](https://github.com/erusev/parsedown-extra) at the moment. There's a pending PR, see erusev/parsedown-extra#86. However, even the original PHP Markdown Extra Parser doesn't support this (even though the docs claim so; try http://parsedown.org/extra/). Please note that [erusev/parsedown-extra](https://github.com/erusev/parsedown-extra) is an upstream project.

In the meantime you can use HTML.

**Comment by Narann** [comment]
Thanks for the fast answer!

I'm very sad to hear that... I guess I will have to write a custom plugin for this.
