### ISSUE TITLE
Use MobileDetectBundle with Pico

### ISSUE THREAD

**Issue by 1adrianb** [picocms/Pico#366]
Hi all,

Is there any way I can use MobileDetectBundle inside pico? Any tips&help is welcomed!

Thanks!

**Comment by PhrozenByte** [comment]
Personally I neither know what MobileDetectBundle is nor what you're trying to achieve with it. Can you please elaborate?

**Comment by smcdougall** [comment]
@PhrozenByte Seems to be a Symphony thing for detecting a mobile device and redirecting them.

https://github.com/suncat2000/MobileDetectBundle

**Comment by PhrozenByte** [comment]
I'm still neither sure what he's trying to achieve nor what the actual question is. Do we support this piece of software in particular? No. Do we support doing something like what this piece of software does? Sure, why not. Is it possible to make this particular piece of software work with Pico? Maybe. Do I think that it is meaningful to do something like what this software does? Very likely not, there are probably better solutions, depends on what he's trying to achieve.

**Comment by 1adrianb** [comment]
@PhrozenByte , thanks a lot for your answer. What I am trying to achieve is to serve a different template/page based on the device(ex mobile or pc)/browser. If you have other suggestion about how this can be achieved let me know

**Comment by PhrozenByte** [comment]
As far as I understand the `README.md` of MobileDetectBundle right, the project is (mostly) a Symfony wrapper for https://github.com/serbanghita/Mobile-Detect. Thus you can use this library straight to do your checks and change Pico's `$config['theme']` variable during the `onConfigLoaded` event.

However, I don't think that server-side, UA-based detections are a good idea in general, you should use a theme that works great on both desktop and mobile devices instead. This ultimately depends on what particular problem you're trying to solve with this detection. However, if you really want to use it, sure, that's possible.
