### ISSUE TITLE
Markdown for paragraphs

### ISSUE THREAD

**Issue by zittergritte** [picocms/Pico#371]
My usecase is to add a css class to the `<p>` tag generated by markdown for a standard paragraph.

According to the markdown extra documentation this should be possible with adding `markdown="1"` to the tag. Unfortunately this does not work.

Usecase:
Add the following to your default example page content-sample/index.md i.e. right after 

`## Creating Content`

```
<p markdown="1" class="myclass">
This is a second *test*
</p>
```
Unfortunately this results in a nested `<p>` tag construct which is not valid and results in three paragraphs, the fist with the class added, the second with the content and an empty at the end.

Testing the same on https://michelf.ca/projects/php-markdown/dingus/ seems to work.

Maybe this is a bug as with the usecase above there should no additional nested `<p>` tag be added...

**Comment by PhrozenByte** [comment]
Pico uses [Parsedown](http://parsedown.org/) (resp. [Parsedown Extra](https://github.com/erusev/parsedown-extra/)) to parse Markdown contents - it's way faster than the original Markdown parser. Unfortunately Markdown (the markup language) never was fully standardized and the specs are pretty ambiguous. As a result, all Markdown parsers behave more or less differently (the original Markdown parser e.g. violates its own specs pretty often). I'm not sure whether this is really a *bug*, however, you can report this behavior to [Parsedown Extra](https://github.com/erusev/parsedown-extra/issues), maybe they decide to change/fix it. Unfortunately this is out of Pico's control, Parsedown is a upstream project.

As far as I know, the markup you're trying to achieve isn't possible with Parsedown. However, depending on what you're actually trying to achieve, there might be alternative solutions, e.g. by using a nesting `<div>`:
```html
<div markdown="1" class="myclass">
This is a second *test*
</div>
```

**Comment by zittergritte** [comment]
Thanks @PhrozenByte for your comment, seems this issue is already known for Parsedown Extra, see [`<p markdown="1"> shows unexpected behavior #68`](https://github.com/erusev/parsedown-extra/issues/68)
