### ISSUE TITLE
Cannot install 1.0.4

### ISSUE THREAD

**Issue by lliss** [picocms/Pico#377]
downloading version 1.0.4 and running `composer install` fails with the following error:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Failed to decode response: zlib_decode(): data error
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info


  [ErrorException]
  zlib_decode(): data error
```

**Comment by PhrozenByte** [comment]
Looks like an issue with your composer installation to me. Did you try https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode? If this doesn't help, please refer to [`composer/composer`](https://github.com/composer/composer#community), join composer's IRC channel and/or open a new Issue there. Alternatively you can simply use one of Pico's pre-bundled release packages instead.
