### ISSUE TITLE
Question: How to add download links to a page

### ISSUE THREAD

**Issue by jstamant** [picocms/Pico#379]
I'm trying to add a download link on one of my pages that directs to a `.pdf` file download (also on my website), and I'm having trouble implementing it.

I'm under the suspicion that Pico might be at fault: either because the evaluate/discover request code  won't serve anything other than `.md`, or because the default `.htaccess` is redirecting non-`.md` requests to 404.

Part of the problem is that I've never implemented a download link in the past, so I don't have a known-working example to deduce from. But If I'm not mistaken, adding a download link should be as easy as adding an anchor tag to the `.pdf`, and letting the browser deal with opening it, such as:

`<a href="{{ base_url }}/file.pdf">`

I've tried looking for similar issues in the Issues tracker under "pdf", "download", "link", "htaccess", and "md". I've also searched google for simple ways to add download links in HTML, and none of the 1-line solutions are working for me (I'm not being lazy, I'm sure that this IS doable with 1 line of code).

I found issue #259, which I tried replicating, but with a `.pdf` file, but to no success. I have no problem embedding image files through markdown. I've tried regular making regular links in markdown, as well as simple anchor tags in the theme `.twig/.html` files, but they all redirect to 404.

Any ideas? Is this achieveable out-of-the-box with Pico, or with a tiny config change? Is Pico getting in the way of serving `.pdf` files?

**Comment by PhrozenByte** [comment]
Pico denys access to the `content` folder for security reasons, see https://github.com/picocms/Pico/pull/368#issuecomment-243231769 for a detailed explanation (starting with the 5th paragraph).

Please also refer to http://picocms.org/docs/:

> As a common practice, we recommend you to separate your contents and assets (like images, downloads, etc.). We even deny access to your `content` directory by default. If you want to use some assets (e.g. a image) in one of your content files, you should create an `assets` folder in Pico’s root directory and upload your assets there. You can then access them in your markdown using `%base_url%/assets/` for example: `![Image Title](%base_url%/assets/image.png)`

Simply create a `assets` folder, upload your `.pdf` to this folder and add a link to it in either one of your content/Markdown files (e.g. ``[Download `test.pdf`](%base_url%/assets/test.pdf)``) or one of your Twig templates.

**Comment by jstamant** [comment]
By adding an `assets` folder in Pico's root directory, like you suggested, I managed to serve the `.pdf` file out of it. I read the comment in [#368](https://github.com/picocms/Pico/pull/368#issuecomment-243231769), and creating a seperate `assets` folder remains convenient for both my small-scale websites.

Thanks, @PhrozenByte.
