### ISSUE TITLE
I uploaded to server but it says "Cannot find `vendor/autoload.php`"

### ISSUE THREAD

**Issue by philipca** [picocms/Pico#380]
I am not a developer (**_or skilled in such matters, so please don't shout at me!_**) so I chose to download the ".zip" file.
I unzipped it and ftp'd it to my shared server at www.personality.co.uk/pico1
But when I visit that URL I get:
Cannot find `vendor/autoload.php`. Run `composer install`.
Where is 'vendor/autoload.php' supposed to be, and/or why isn't it in the correct place in my .zip's contents? Or what have I done wrong?

**Comment by PhrozenByte** [comment]
You've downloaded a source code archive rather than a release archive. Simply use https://github.com/picocms/Pico/releases/download/v1.0.4/pico-release-v1.0.4.tar.gz instead 😃

**Comment by philipca** [comment]
Many thanks for the prompt answer PhrozenByte. 

Now that I've uploaded the *_correct_* file-contents, I see the content-sample/index.md 'welcome' page. So all looks good for me to get started....

But one small problem:at the foot of the page it says:

>      For more help have a look at the Pico documentation at http://picocms.org/docs


But when I visit http://picocms.org/docs I get a 404 ErrorPage, with the address bar of my browser showing: http://picocms.org/[object%20Object]

Is this a mistake of yours, or another one of mine???  <smile>

**Comment by PhrozenByte** [comment]
It's a mistake of GitHub Pages silently changing things and doing some crazy shit - again... 😒 

It's fixed now. Your browser might cache the wrong redirection, if it is doing so, simply directly navigate to http://picocms.org/docs/. Sorry for the inconvenience.

**Comment by philipca** [comment]
Thanks. I now have the docs. I want to try different themes, and I've uploaded one to the /themes/ folder, but I am told to edit 'config.php' file to point to it.

But I can't find 'config.php'  --  there's a folder in my upload called 'config' where I thought I would find it, but in that folder is only one file called 'config.php.template' and I can't seem to open or edit that.

More help please!!!!

**Comment by PhrozenByte** [comment]
http://picocms.org/docs/#config:

> You can override the default Pico settings (and add your own custom settings) by editing `config/config.php` in the Pico directory. For a brief overview of the available settings and their defaults see [`config/config.php.template`](https://github.com/picocms/Pico/blob/master/config/config.php.template). To override a setting, copy `config/config.php.template` to `config/config.php`, uncomment the setting and set your custom value.

**Comment by Zanatoo** [comment]
> You've downloaded a source code archive rather than a release archive. Simply use https://github.com/picocms/Pico/releases/download/v1.0.4/pico-release-v1.0.4.tar.gz instead

I've just downloaded https://github.com/picocms/Pico/releases/download/v2.0.4/pico-release-v2.0.4.tar.gz and I'm getting the same error. Maybe it's because I'm on localhost? What's more confusing is there is a vendor/autoload.php there. 

(I'm not a developer either.  Just looking for a very light CMS)

**Comment by PhrozenByte** [comment]
@Zanatoo: Check your file permissions, PHP/your webserver likely isn't able to access the files.
