### ISSUE TITLE
Wiki showcase: A pico website with actualy more than 2,000 pages

### ISSUE THREAD

**Issue by Prolegomenes** [picocms/Pico#382]
Good day!

I hope i am at the right place to post my message...

Is it interesting for the pico community to see a website (100% pico) running with more than 2,000 pages with no problems ?

If yes, maybe it can be added to the wiki showcase ? (French website)

Thanks a lot for your great job anyway

The site adress is www.prolegomenes.com

Eric MEAUX
eric.meaux@hotmail.com

**Comment by PhrozenByte** [comment]
Great to hear that @Prolegomenes, thanks for your feedback! Our wiki is editable for everyone, you can add your website to the Showcase yourself if you want to :smiley: :+1:

**Comment by Prolegomenes** [comment]
@PhrozenByte 
Great!, This is done !
Thank you
