### ISSUE TITLE
Creating nested submenu

### ISSUE THREAD

**Issue by sajidmc** [picocms/Pico#383]
Hi,

I was trying to create a web page with Pico. In the menu, is it possible to have only the root level pages, and each subpage as a submenu of each root pages ?

Directory structure:
index.md
about\index.md
about\mypeople.md
pictures\index.md
pictures\2016.md
pictures\2015.md
contact.md

Menu items:
Home
About
     - My People
Pictures
     - 2016
     - 2015
Contact

**Comment by PhrozenByte** [comment]
I've answered this question in [#picocms on Freenode](https://webchat.freenode.net/?channels=%23picocms). Just for the record, this is the final solution @sajidmc was asking for:

```twig
<ul>
    {% for page in pages if page.title %}
        {% if parentPage and not (page.id starts with parentPage) %}
            {% set parentPage = null %}
                </ul>
            </li>
        {% endif %}

        {% set pageDepth = page.id|split('/')|length %}
        {% if pageDepth == 1 %}
            <li><a href="{{ page.url }}">{{ page.title }}</a></li>
        {% elseif (pageDepth == 2) and (page.id ends with "/index") %}
            {% set parentPage = page.id|slice(0, -5) %}
            <li>
                <a href="{{ page.url }}">{{ page.title }}</a>
                <ul>
        {% elseif (pageDepth == 2) and parentPage %}
            <li><a href="{{ page.url }}">{{ page.title }}</a></li>
        {% endif %}
    {% endfor %}
</ul>

{% if parentPage %}
    {% set parentPage = null %}
        </ul>
    </li>
{% endif %}
```
