### ISSUE TITLE
Infinite scroll - auto preload recent posts

### ISSUE THREAD

**Issue by sambuev** [picocms/Pico#385]
Hello, I have a website with many posts, I want to preload each 10 posts while user scrolling down the entire website. Please help me with advice.
Thank you.

**Comment by PhrozenByte** [comment]
Nothing special to consider here, simply create a plugin for Pico that handles the AJAX requests to load the next few posts when the user reaches the bottom of the page. AFAIK there's no plugin for something like this yet, i.e. you'll have to develop it on your own.

Pico uses a event-based system that allows you to hook into Pico's processing. Have a look at Pico's [`plugins/DummyPlugin.php`](https://github.com/picocms/Pico/blob/master/plugins/DummyPlugin.php) and the [developer docs](http://picocms.org/development/) (still WIP).
