### ISSUE TITLE
Numbers in meta data with leading '0'

### ISSUE THREAD

**Issue by icro** [picocms/Pico#388]
Hi,
I've an issue with zip codes starting with '0'.

The example below shows you a meta data block for the company address (for rich snippets).
I'm not sure what happens here, but it looks like a conversion from decimal to octal or something like that.
The zip code '09111' will be converted to '73', '09112' will be '74', '01099' to '8', and '01097' to '71'

Dump:
```
  ["test"]=>
  array(10) {
    ["id"]=>
    string(8) "test"

    [...snip...]

    ["raw_content"]=>
    string(905) "---
Title: Test
Description: seo description
Author: icro
Date: 2017/06/08
Robots: noindex, nofollow
Template: index
Position: 20
__companyStreetAddress: Foostreet 123
__companyPostalCode: 09111
---

#Hello World

"
    ["meta"]=>
    array(23) {

      [...snip...]

      ["__companypostalcode"]=>
      int(73)

      [...snip...]

    }
  }
```

Kind regards,
icro

**Comment by PhrozenByte** [comment]
Pico uses [Symfony YAML](https://github.com/symfony/yaml) to parse the YAML frontmatter and follows the [YAML standard](http://www.yaml.org/) pretty strictly. Numeric values might get interpreted as octal. Postal codes are numeric strings, so you should explicitly tell Symfony YAML to interpret it as string to avoid false assumptions by the YAML parser:

```yaml
__companyPostalCode: "09111"
```

**Comment by icro** [comment]
Thanks for your reply. I've changed it.
