### ISSUE TITLE
Improved backend

### ISSUE THREAD

**Issue by AndiLeni** [picocms/Pico#390]
Hello,

I just wanted to post a link to my new repository.
[pico_edit](https://github.com/AndiLeni/pico_edit)

It's a fork of [pico_edit](https://github.com/blocknotes/pico_edit).

I changed the UI to make it mobile friendly. Also I added and removed some features. 
Feel free to have a look at it.

**Comment by PhrozenByte** [comment]
Thank you for letting us know @AndiLeni, great work! 👍 

You can add your fork to the [plugins page of our Wiki](https://github.com/picocms/Pico/wiki/Pico-Plugins) to promote it. Optionally you can also take look at the [Submission Guidelines](http://picocms.org/in-depth/submission_guidelines/) of our website.

**Comment by PhrozenByte** [comment]
I've added your plugin to https://github.com/picocms/Pico/wiki/Pico-Plugins. Thanks again @AndiLeni!
