### ISSUE TITLE
How can I offer my Downloads on a Page in Pico CMS?

### ISSUE THREAD

**Issue by AlexL777** [picocms/Pico#393]
Hello Developers and Community,

I work with the latest Pico-CMS version and would like to create a new page for dowloads.

I hovered the directory `/downloads` and I would then have to upload the ZIP Files somewhere via FTP.

How can I do it best or is there such a Pico plugin?

Thanks in advance.

**Comment by PhrozenByte** [comment]
AFAIK there's no "download manager" plugin or something like that yet. A very simple solution is to upload the ZIP files (like any other asset file) to your `assets/` folder, create a `content/download.md` and list all files to download there.

Please also refer to our [User Docs](http://picocms.org/docs/):

> As a common practice, we recommend you to separate your contents and assets (like images, downloads, etc.). We even deny access to your `content` directory by default. If you want to use some assets (e.g. a image) in one of your content files, you should create an `assets` folder in Pico’s root directory and upload your assets there. You can then access them in your markdown using `%base_url%/assets/` for example: `![Image Title](%base_url%/assets/image.png)`

**Comment by AlexL777** [comment]
OK, Thanks! 

Have it now under http://picocms.wpzweinull.ch/sub/downloads realized.

Pico CMS is very complicated for me because everything is based on directories and I do not get a bit clear.

I wanted to create categories, but after several attempts I gave up.

A question: DropDown-Mavigation is not possible or?

**Comment by PhrozenByte** [comment]
This is up to the theme you use. You can either use one of our many community-developed themes (there are some [featured themes](http://picocms.org/themes/) on our website, and even more on [our wiki](https://github.com/picocms/Pico/wiki/Pico-Themes)), or develop a custom theme on your own (see [our docs](http://picocms.org/docs/#themes), Pico uses [Twig](http://twig.sensiolabs.org/documentation) as template engine). Categories (or tags) are pretty easy to realize with pure Twig, however, there are also some plugins out there carrying everything out theme-independent. Again, please refer to [our docs](http://picocms.org/docs/#plugins); you can find plugins on both [our website](http://picocms.org/plugins/#entry-tags) and [our Wiki](https://github.com/picocms/Pico/wiki/Pico-Plugins).
