### ISSUE TITLE
integrating Pico in Nextcloud

### ISSUE THREAD

**Issue by daita** [picocms/Pico#395]
Hey, had a talk with PhrozenByte yesterday about this, and he thought that it might be interesting for some other people.

https://github.com/nextcloud/cms_pico/
The app is also available for download in here: https://proser.artificial-owl.com/index.php/s/ye6JYMaR0vnSnPM

I made an app for Nextcloud so users can create their own website using Pico CMS. The main challenge is to keep the cloud secure, meaning that no malicious script/code could be implemented in a page by a user.

And this is the list of things the app is doing to avoid that:
- config.php is out of reach of users, so they can't write PHP.
- themes are out of reach of users, so they can't add random javascript to a page.
- plugins are out of reach of users, so they can't add random PHP Code to a page.

Some links for anyone curious on how I manage to fill those requirements:
- https://github.com/nextcloud/cms_pico/blob/master/lib/Service/PicoService.php#L82  
This is where the app will generate the Pico object.

- https://github.com/nextcloud/cms_pico/blob/master/Pico/plugins/Nextcloud.php  
A plugin that remove all scripts on the content of the page before including the theme. remove all script from the meta, and force the theme_url.

Regards,

**Comment by Ricardosgeral** [comment]
it is possible to use themes and plugins in the nextcloud integration?

**Comment by PhrozenByte** [comment]
Please refer to [`nextcloud/cms_pico` on GitHub](https://github.com/nextcloud/cms_pico) for questions about how to use Nextcloud's Pico integration.

As an exception: Yes, sure. You can find Pico's `plugins` and `themes` dirs in the `apps/cms_pico/Pico` dir. When uploading a plugin, it is immediately available to all websites. When uploading a theme, you first have to add it to your NC instance using the Pico configuration page in NC. See [`cms_pico`'s Wiki page](https://github.com/nextcloud/cms_pico/wiki/Admin-Settings#customizing) for more info. If you have any further questions about Nextcloud's Pico integration, please refer to [`nextcloud/cms_pico`](https://github.com/nextcloud/cms_pico) - this makes it easier for others to find solutions to already answered questions.
