### ISSUE TITLE
Resizing images

### ISSUE THREAD

**Issue by pjotrek-b** [picocms/Pico#396]
Searching the website documentation of Pico, I couldn't find any information about how to resize images. Is this possible and is it documented anywhere?

Thank you very much in advance.

**Comment by PhrozenByte** [comment]
What do you mean by "resizing images"? Choosing the right zoom factor to properly display the image on your website is up to the theme you use (and your browser, of course). If you rather mean "physically" resizing the image (i.e. changing the dimensions of the image itself and reducing the file size of the `.jpg`/`.png`/...): Pico neither supports auto-resizing images (however, as always, you can still write a plugin if you want to), nor does it include any kind of "asset handling". You should always upload images roughly in the sizes you need (to get a good file-size-to-image-quality-ratio), the rest is choosing the right zoom factor (see above).

**Comment by pjotrek-b** [comment]
Thanks for your reply :smile:

I'm using some images in a resolution higher than the one I want to display it in (on purpose).
Therefore I was wondering if it was possible to add size information to the Markdown image-link to scale it dynamically in the browser.
e.g.: width=70% or width=400px, etc.

Currently, I'm embedding these images using plain HTML:
`<img src... width="...">`

**Comment by PadseGaming** [comment]
> 
sorry that i have to reopen this. But ![](http://example.com/my_image.png) {.float-right} this isn't working for me. 

My css File with css, e.g.  .float-right { float: right; width: 40%; } code is in the Themes assets/css folder. If i use the code above in my .mk files, the code doesnt work. It seems that the .mk File doenst have a connection to the css File in Picos Theme Folder. I tryed html code else, but i cant find a solution to size my images to percentage, only to a specific size e.g. hight"50" width"20"

Can i get some help?
