### ISSUE TITLE
Need help with our installation of Pico

### ISSUE THREAD

**Issue by rsjowell** [picocms/Pico#397]
Hello, I am the webmaster for a non-profit group in Arlington, VA. We got an installation of Pico on our server in 2012. I have a question about it but the corp that installed it seems to be out of business. Is there someone who can help us address some issues? My e-mail is rjowell@wrapcompliance.org

**Comment by PhrozenByte** [comment]
Pico is a open source project, there's no official commercial support, installation service or suchlike. However, if you need help you can take a look at [our docs](http://picocms.org/docs/), open a new Issue with a concrete question right here on GitHub or join us on [#picocms on Freenode IRC](https://webchat.freenode.net/?channels=%23picocms). See http://picocms.org/docs/#getting-help

**Comment by rsjowell** [comment]
Thanks, my question is this. We are a global non-profit group so we asked that our site be able to support different languages. They set Pico up so that each page we created would have a different URL directory according to the language (for instance, www.wrapcompliance.org/en/certification or wrapcompliance.org/zh/certification). We need to know how to add another one of these language codes to the system.

**Comment by PhrozenByte** [comment]
This is a feature tailor-made for your website, this is no feature of Pico itself.

The natural solution is that you've a `content/en/certification.md` file representing the contents of www.wrapcompliance.org/en/certification and a `content/zh/certification.md` file representing  www.wrapcompliance.org/zh/certification. If this is true - and this is just guessing from my side! - you'll have to create a `content/XX/certification.md` with contents of the certification page in language `XX`. Depending on how i18n is realized in your website's theme, you might also have to add the `XX` language somewhere (might be a config value in your `config/config.php` or just `config.php`, depending on the Pico version you're using). Again, I'm just guessing, this feature was made explicitly for you by the company that made the website.
