### ISSUE TITLE
3 abandoned packages in composer installation

### ISSUE THREAD

**Issue by haheute** [picocms/Pico#398]
Hello, 
I am trying pico and when installing with `composer install` from inside the git clone folder, composer reports 3 abandoned packages:

```
Package kherge/version is abandoned, you should avoid using it. No replacement was suggested.
Package herrera-io/json is abandoned, you should avoid using it. Use kherge/json instead.
Package herrera-io/phar-update is abandoned, you should avoid using it. No replacement was suggested.
```

I will try on and see if it works, just wanted to inform..

**Comment by PhrozenByte** [comment]
Thanks for letting us know @haheute! 👍

These packages are used by upstream packages, not by Pico itself. We unfortunately don't have any influence on this. Furthermore they are only installed when installing Pico with development dependencies. You don't need them if you don't want to contribute code to Pico's core, so you can safely remove them by running `composer update --no-dev`.

**Comment by haheute** [comment]
Ok.. and thanks for the explanation
