### ISSUE TITLE
🎉 First beta release of Pico 2.0

### ISSUE THREAD

**Issue by PhrozenByte** [picocms/Pico#401]
After 21 months and 157 commits, we're happy to announce the release of the **first beta of Pico's second major release!** 🎉 

Click here to download *Pico v2.0.0-beta.1*: [`pico-release-v2.0.0-beta.1.tar.gz`](https://github.com/picocms/Pico/releases/tag/v2.0.0-beta.1)

[![Screenshot of Pico 2.0](https://picocms.github.io/screenshots/pico-20.png)](https://github.com/picocms/Pico/releases/tag/v2.0.0-beta.1)

Pico 2.0 introduces some major new features, but unfortunately also comes with some BC-breaking changes. However, as always, we tried to maintain BC whenever possible using Pico's official [`PicoDeprecated` plugin](https://github.com/picocms/pico-deprecated). If you've spared to use features, that are deprecated since Pico 1.0, you should be fine. Since we wanted to finally release the first beta, we unfortunately didn't have time to write a changelog or upgrade instructions yet. We'll publish them with the second beta. Nevertheless, the upgrade process should be pretty straight-forward and is basically the same as with Pico 1.0.

Even though the changes are pretty immense, we are aware of the fact that developing Pico 2.0 took a pretty long time. In the future we'll try to release Pico more often and in smaller pieces.

**For a complete list of changes, please refer to Pico 2.0's main pull request #334.** You can find Pico 2.0's source code in the [`pico-1.1` branch](https://github.com/picocms/Pico/tree/pico-1.1). Please note that you can now find both Pico's official [`PicoDeprecated` plugin](https://github.com/picocms/pico-deprecated) and Pico's official [default theme](https://github.com/picocms/pico-theme) in separate repos.

As always, **feedback is highly appreciated!** ❤️

**Comment by nitrix** [comment]
I can tell a lot of work went into this.

I, myself, was even working on a better admin panel and doing improvements on your CMS on my side. Seems like you're always ahead of the curve.

I really like the project, the decisions it made, the vision it has, how receptive it is to feedbacks and the continuous love its getting. @PhrozenByte hats off (:

**Comment by nliautaud** [comment]
Congrats !
Everything works fine here, and I confirm the compatibility of my plugins.
[PicoUsers](https://github.com/nliautaud/pico-users), [PicoPagesList](https://github.com/nliautaud/pico-pages-list), [PicoPagesImages](https://github.com/nliautaud/pico-pages-images), [PicoOutput](https://github.com/nliautaud/pico-output), [PicoContentEditor](https://github.com/nliautaud/pico-content-editor) and [P01contact](https://github.com/nliautaud/p01contact).

**Comment by clausbertels** [comment]
These are wonderful improvements! Thank you for taking so much of your time to provide us with such a great and lightweight cms. I'd love to make a full tutorial on setting Pico 2 up and creating templates once it's released. Maybe even in-depth documentation about that (like Pico's Twig filters and data structure, ...)

But I was wondering if full support for subdirectories would be on the feature list soon? So I can access only pages (and the dir's metadata in a separate .yml) in a certain directory in my templates. The current CategorizedPages plugin does this job, poorly, by reading and exploding the url but this doesn't seem like a very robust method.

**Comment by PhrozenByte** [comment]
> I'd love to make a full tutorial on setting Pico 2 up and creating templates once it's released. Maybe even in-depth documentation about that (like Pico's Twig filters and data structure, ...)

I'd love to see that! 👍 Pico's documentation definitely needs improvements, @smcdougall had some great ideas and is currently working on a rewrite of the docs with a completely different approach. See picocms/picocms.github.io#6

> But I was wondering if full support for subdirectories would be on the feature list soon?

I'm not sure what you mean by that, can you please elaborate a little bit more? If it's basically about making the pages array accessibly through a tree structure: We're planning to release a official plugin for that with Pico 2.0. I was even thinking about adding it to Pico's core lately. It's a quite essential feature for theme developers and not really possible with pure Twig (actually, it *is* possible, but not very robust...).

**Comment by clausbertels** [comment]
> I'm not sure what you mean by that, can you please elaborate a little bit more?
It's basically about what you said. But for others that might read this;
Let's say my site looks like this:

<img width="651" alt="schermafbeelding 2017-11-12 om 17 25 23" src="https://user-images.githubusercontent.com/25482509/32701027-e7433ed0-c7ce-11e7-93c3-008e73384591.png">

I'd like to be able to set a template on ./portfolio/index.md in which I can access all of it's folders and those folders' pages' yaml headers and content. This way I can easily create a landing page for all of portfolio's content by using i.e. {{ for p in current_dir }} {{ current_dir.icon }} {{ p.title }} {{ endfor }}. But this is, I think, very difficult to program because you have to account for all the possible use cases:
- accessing ALL pages in a directory
- accessing only direct pages or dir(s) in a directory
- accessing a page's directory's metadata
- etc..

I think it's quite essential too, but others might not need this. I'd be very happy with an official plugin!

I'll definitely have a good look at @smcdougall's PR!

(good thing we're in the same time zone @PhrozenByte. Love the fast responses.)

**Comment by nliautaud** [comment]
@clausbertels the [PicoPagesList](https://github.com/nliautaud/pico-pages-list) plugin should provide what you're looking for.

Ex. getting pages of a given directory : 
```twig
{% set filteredpages = pages | only('portfolio/') %}
{% for p in filteredpages %}
...
```
Or of the current directory :
```twig
{% set currentpath = current_page.id | replace({'/index': ''}) %}
{% set filteredpages = pages | only(currentpath) %}
{% for p in filteredpages %}
...
```

**Comment by PhrozenByte** [comment]
Yeah, that's exactly what a page tree does. There are already some plugins out there implementing this, but always with some additional features (like @nliautaud's [PicoPagesList](https://github.com/nliautaud/pico-pages-list)).

However, I don't think that we'll implement the "accessing ALL pages in a directory" (i.e. all decadents of a page, not just children) use case, because this would conflict with our plans to overhaul Pico's page discovery in Pico 3.0 (the far, far future... 😆 see #317). Anyway, this shouldn't be a problem because leveling out a tree structure is very easy (no plugin necessary, just pure Twig).

I believe that page trees are pretty common stuff, that's the reason why I was thinking about adding this to Pico's core lately rather than using a plugin (like Pico's official [PicoHttpParams](https://github.com/PhrozenByte/pico-http-params) plugin).

Having a separate meta-data-only `.yml` file in a directory is another topic, that's currently not planned (see the "Data files plugin" in #317).

**Comment by PhrozenByte** [comment]
I made the decision to add a page tree to Pico's core rather than creating a official plugin. I think a pretty high percentage of our users need something like that and it's such a basic thing to do, that many theme developers will use the new possibilities to build even more powerful themes.

Please refer to 28d2648 for implementation details and the [`Pico::buildPageTree` class docs](http://picocms.org/phpDoc/pico-1.1/classes/Pico.html#method_buildPageTree).

@clausbertels @nliautaud

**Comment by PhrozenByte** [comment]
[**Pico's second beta release is out now!**](https://github.com/picocms/Pico/releases/tag/v2.0.0-beta.2) (`v2.0.0-beta.2`)

The second beta primarily includes the new page tree (see https://github.com/picocms/Pico/issues/401#issuecomment-345458255) and the full changelog for Pico 2.0 (see [`CHANGELOG.md`](https://github.com/picocms/Pico/blob/pico-1.1/CHANGELOG.md)).

**Pico 2.0 is basically ready for release!** However, we really need some support to update our docs and website for Pico 2.0 - this is the only thing missing before we can release Pico 2.0! We have to update our docs (especially the install instructions) and write upgrade instructions similar to http://picocms.org/in-depth/upgrade/ including a "What's new" section targeting our users. Help is highly appreciated! See picocms/picocms.github.io#18 and partially picocms/picocms.github.io#7

@smcdougall @picocms

**Comment by ILDaviz** [comment]
thx man 💃

**Comment by PhrozenByte** [comment]
@nitrix: It says "second beta", not "second major release" 😄

However, as I was trying to point out, the code itself is ready to release. The only reason why this is just the second beta and not the final release are the missing docs and website updates - help is appreciated btw. I'm using Pico 2.0 in production for months now.

**Comment by clausbertels** [comment]
I second the motion that the whole projects structure is getting very confusing with development seemingly split between issues, branches, pull requests and a pre-release. Then again I don't have quite a lot of experience on Github.

If someone could write a very rough and quick guide for me to upgrade my own site to Pico 2 I can get started on writing a novice guide for installing as well as upgrading. (collaborating with @smcdougall probably)

**Comment by PhrozenByte** [comment]
> I second the motion that the whole projects structure is getting very confusing with development seemingly split between issues, branches, pull requests and a pre-release. Then again I don't have quite a lot of experience on Github.

Actually it's quite simple. Pico's development happens in the `pico-1.1` branch, #334 is just the pull request for this branch. Our website can be found in the [`picocms/picocms.github.io` repo](https://github.com/picocms/picocms.github.io). Since Pico 2.0 wasn't released yet we use the `pico-2.0` branch to prepare the website for the release. picocms/picocms.github.io#18 is the pull request for this branch.

> If someone could write a very rough and quick guide for me to upgrade my own site to Pico 2 I can get started on writing a novice guide for installing as well as upgrading. (collaborating with @smcdougall probably)

I appreciate it! 😄 I wrote the updated general install & upgrade instructions yesterday (see https://github.com/picocms/Pico/blob/pico-1.1/README.md#install) and started (i.e. it's incomplete and still work in progress) writing the Pico 1.0 to Pico 2.0 upgrade tutorial today (live demo: http://phrozenbyte.github.io/Pico/in-depth/upgrade-pico-20/).

**You can use this tutorial to test Pico 2.0!**

Since Pico 2.0 introduces various BC-breaking changes we need detailed instructions on how to solve issues resulting from updating to Pico 2.0. However, users should not just solve the issues from BC-breaking changes, but should also stop using now deprecated features. This unfortunately requires some knowledge about the actual code changes... 😞

However, we additionally need a "What's new" section for all major changes, including those which don't necessarily lead to a change in existing installations. This doesn't require knowledge about Pico's source code, reading through Pico's [`CHANGELOG.md`](https://github.com/picocms/Pico/blob/pico-1.1/CHANGELOG.md) should be sufficient to write it. 😄

**Comment by clausbertels** [comment]
Reading up right now, saw that "download the latest Pico release" links to v1.0.6 ;)

**Comment by iagovar** [comment]
Mmm, how do I configure the 404 error?

**Comment by PhrozenByte** [comment]
@iagovar: Please refer to [Pico's user docs](http://picocms.org/docs/):

> If a file cannot be found, the file `content/404.md` will be shown. You can add `404.md` files to any directory. So, for example, if you wanted to use a special error page for your blog, you could simply create `content/blog/404.md`.

**Comment by iagovar** [comment]
Is there any possibility to implement the ability to put PHP includes inside .md files? I'm doing it through jquery and it's a bit messy to be honest

**Comment by PhrozenByte** [comment]
I'm not sure why you are asking the same question a second time. This has been answered already, see https://github.com/picocms/Pico/issues/414#issuecomment-363395284

**Comment by PhrozenByte** [comment]
[:tada: **Pico's second major release `v2.0.0` is out now!**](https://github.com/picocms/Pico/releases/tag/v2.0.0)
(yes, Pico 2.0 is officially stable now!)

It took a long time, but I think the waiting was worth it! :smiley: I think I don't need to make a long speech about it (especially because it was stable since `v2.0.0-beta.3` anyway), so it only remains for me to say a big and heartfelt "thank you" to everyone who helped making this possible.

Please refer to Pico's new [upgrade docs](http://picocms.org/in-depth/upgrade-pico-20/) to find out what has changed and how to upgrade your Pico 1.0 installation to Pico 2.0. The docs target the average Pico user, not just developers and also includes a complete list of all **new features** (and we're not talking about a few minor changes here, it's a major release for a reason :laughing:).

As always, **feedback is highly appreciated!**

Have fun with Pico's second major release! :heart: 

@theshka @smcdougall @picocms

**Comment by omniperspective** [comment]
Gefeliciteerd !!🙏

**Comment by bricebou** [comment]
Thanks for your amazing work !

**Comment by bricebou** [comment]
I've installed the release through composer and I was wondering if it's normal that the `config/` dir is empty ?

**Comment by PhrozenByte** [comment]
Sort of... I didn't want to create a copy of `config/config.yml.template` in `picocms/pico-composer`. Anyway, since we're referring to it in the user docs, I guess it's better to add it, even though it requires us to update the file there when we upgrade the config template in the main repo. Fixed in https://github.com/picocms/pico-composer/commit/40b146f75d7ccb8200ca4570da4e8b408ce7581d. Thank you for bringing this up @bricebou :+1:

**Comment by bricebou** [comment]
You're welcome @PhrozenByte :-) 
I was looking for the doc regarding accessing HTTP parameters (https://phrozenbyte.github.io/Pico/in-depth/features/http-params/) but I can't find it on picocms.org. Is it normal? or maybe you're working on it and I'm too fast... 
I wanted to make a link in a post I wrote about Twig pagination (update in https://github.com/picocms/Pico/issues/443).

**Comment by PhrozenByte** [comment]
@bricebou http://picocms.org/in-depth/features/http-params/

**Comment by bricebou** [comment]
Ok ! But I don't find any link to it from the left-side menu or from the main page content :-/

**Comment by gilbitron** [comment]
Congrats on the release of Pico 2.0.0 guys 🎉
