### ISSUE TITLE
Pagination issues for blog use

### ISSUE THREAD

**Issue by kkarthik23** [picocms/Pico#404]
I tried to use clean blog,default and just pico themes but unable to get pagination working.
I am using the Pico Pagination plugin and set $config['pagination_limit'] in config file, I get the older posts link but when I click on it, it doesn't go to the next page and show the other posts for a blog.

Appreciate if someone can help with this

Thanks

**Comment by PhrozenByte** [comment]
Works just fine for me. Make sure to strictly follow the theme's and [`rewdy/Pico-Pagination`'s](https://github.com/rewdy/Pico-Pagination) installation instructions (`rewdy/Pico-Pagination` e.g. only considers pages with a `Date` meta value). Please note that themes (like [`BesrourMS/clean-blog`](https://github.com/BesrourMS/clean-blog)) must know about the pagination plugin, i.e. neither the default theme nor [`blocknotes/just-pico`](https://github.com/blocknotes/just-pico) won't ever show a pagination until you actually modify the theme accordingly.

If you still can't make it working, please refer to the 3rd party theme and/or plugin developers:

- @rewdy's [`Pico-Pagination` plugin](https://github.com/rewdy/Pico-Pagination)
- @BesrourMS's [`clean-blog` theme](https://github.com/BesrourMS/clean-blog)

**Comment by kkarthik23** [comment]
Hi,
Thanks for the response, much appreciated.
I am using clean-blog and rewdy/Pico-Pagination and it is showing pagination but if I limit 4 articles to the first page and want to see the next 4 articles by clicking on the older posts then it does not show those old 4 articles and maybe i am missing something and will review it again. 
Could you please let me know what theme you are   using since pagination works fine for you?
Thanks again.

**Comment by PhrozenByte** [comment]
[`BesrourMS/clean-blog`](https://github.com/BesrourMS/clean-blog) with [`rewdy/Pico-Pagination`](https://github.com/rewdy/Pico-Pagination). However, I'm just making sure that this is neither a issue with Pico, nor an obvious issue with the theme or plugin. Please refer to the 3rd party theme and/or plugin developer for getting help.

**Comment by kkarthik23** [comment]
Hi,
Thank you so much for your help.
I found out what the problem was, when i was using the built in php web server it didnt work but when i started using apache web server pagination started working, so I think i had configured it properly but maybe there was something different in the way i was running it with the built in  php web server.

I am using BesrourMS/clean-blog with rewdy/Pico-Pagination.
It is all working fine, thanks for your time and help. 

Thanks again.
