### ISSUE TITLE
Can't change theme

### ISSUE THREAD

**Issue by Ricardosgeral** [picocms/Pico#405]
how do i change the themes?

so far i wan't able to change then!

what i've done:

1. download the theme (e.g. astral)
2. copy the astral folder into pico folder
3. change the config.php.template inside config folder and change "default" by astral

after this everything is the same

what's missing?

**Comment by PhrozenByte** [comment]
`config.php.template` is a template. Rename it to `config.php` 😉

**Comment by Ricardosgeral** [comment]
even so, it's not changing anything PhrozenByte

**Comment by PhrozenByte** [comment]
Quoting from [our website](http://picocms.org/docs/#config), Pico's sample contents and the header in the `config/config.php.template`:

> You can override the default Pico settings (and add your own custom settings) by editing `config/config.php` in the Pico directory. For a brief overview of the available settings and their defaults see `config/config.php.template`. To override a setting, copy `config/config.php.template` to `config/config.php`, uncomment the setting and set your custom value.

Did you actually uncomment the config variable (remove the `//` at the beginning of the file)?

```php
<?php

$config['theme'] = 'astral';
```

**Comment by Ricardosgeral** [comment]
ok. I feel stupid now! it was that. I'm not a programmer
thanks

**Comment by PhrozenByte** [comment]
No problem at all, you're welcome 😃 If you have any other question, don't hesitate to ask, either by creating a new Issue on GitHub or by joining us on [#picocms on Freenode IRC](https://webchat.freenode.net/?channels=%23picocms)
