### ISSUE TITLE
How to move website?

### ISSUE THREAD

**Issue by sqwoteg** [picocms/Pico#410]
I moved my website to another directory and now I see this
![image](https://user-images.githubusercontent.com/35040944/34569242-d9b7b69e-f170-11e7-9e87-15beee499e6b.png)
What is wrong?

**Comment by sqwoteg** [comment]
I downloaded clear pico cms.. 
![image](https://user-images.githubusercontent.com/35040944/34569899-d85cfd48-f172-11e7-94e9-1e31219a83fa.png)

**Comment by sqwoteg** [comment]
Probably it is a problem with my hosting provider

**Comment by PhrozenByte** [comment]
Correct. The PHP version your hosting provider uses has a known issue with this function. Update your PHP version.
