### ISSUE TITLE
How do I show folders or categories with Twig?

### ISSUE THREAD

**Issue by iagovar** [picocms/Pico#414]
Hi all. I'm looking for a way to show in the index page the folders inside /content.

Basically I'm trying to recreate a SILO structure in my site, so the index page shows the categories of the site and a list of links where template: page. When the user clicks that categories another page shows listing all the documents inside such category.

I've looked in the picocms docs but I didn't find anything suitable, and reading twig documentation I'm a bit lost to be honest.

**Comment by PiersMorgan** [comment]
https://stackoverflow.com/questions/33330112/scan-folder-with-twig#33334514

**Comment by PhrozenByte** [comment]
This is a task predestined for the page tree shipped with Pico 2.0. You can download the latest beta from https://github.com/picocms/Pico/releases (also see #401). Don't worry about Pico 2.0 being in beta, it's actually ready-to-release, we just haven't finished the docs/website updates yet.

First create a `index.md` in all folders representing categories and add a YAML header (e.g. `content/my_category/index.md`):

```yaml
---
title: My category
category: true
---
```

The Twig snippet looks like the following:

```twig
{% for category in pages["index"].tree_node.children %}
    {% if category.page and category.page.meta.category %}
        <div>
            <h3>{{ category_node.page.title }}</h3>
            ...
        </div>
    {% endif %}
{% endfor %}
```

**Comment by iagovar** [comment]
Thank you, I'll download the 2.0 version and tell you if it worked.

**Comment by iagovar** [comment]
It worked! Now I have another question. I want to put a PHP include inside a .md file. but it seems to output in plain text. Is there any way to scape the markdown interpreter for a few lines or any other way to do something similar?

**Comment by PhrozenByte** [comment]
This is not possible (on purpose). Use a Twig template instead (e.g. add `Template: special_page` to the YAML header of `content/special_page.md` and create a `themes/my_theme/special_page.twig`). If Twig really isn't sufficient, you'll have to create a Pico plugin instead (refer to the plugins section in the user docs, the (unfinished, **help is highly appreciated**) dev docs at http://picocms.org/development/ and Pico's [`DummyPlugin`](https://github.com/picocms/Pico/tree/pico-1.1/plugins/DummyPlugin.php)).

**Comment by iagovar** [comment]
Well, if someone has the same problem, I'm doing it throug jquery:

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script> 
$(function(){
    $("#tabla-webs").load("path/tabla-webs.html"); 
});
</script> 


<div id="tabla-webs"></div>

**Comment by iagovar** [comment]
@PhrozenByte what if I change the documents format from .md to .html in the config file? Will that allow me to use php include?

**Comment by PhrozenByte** [comment]
No

**Comment by iagovar** [comment]
:(
