### ISSUE TITLE
Theme creation

### ISSUE THREAD

**Issue by PiersMorgan** [picocms/Pico#415]
Hi do you have a link to your documentation for developing themes for Pico. I am a web designer and developer and would be interested in coding a fresh theme!

**Comment by PhrozenByte** [comment]
There isn't much to consider specially for Pico, creating themes is mostly just Twig (https://twig.sensiolabs.org/doc/1.x/). Pico's default theme (at least starting with Pico 2.0, however, you shouldn't develop a theme for Pico 1.0 at this point anymore anyway; see https://github.com/picocms/pico-theme) is a good starting point. There's also a small themes section in the user docs (http://picocms.org/docs/#themes). We're unfortunately lacking a bit of docs, help improving this situation is **highly appreciated**. Many questions have been asked before here on GitHub (use the search function) and if you can't find an answer, don't hesitate to ask (either using a new Issue or, if it's just a small question, using Freenode IRC) 😄

**Comment by PiersMorgan** [comment]
I will work on the documentation if that is what is required! And if required i can work on Pico 2.0 themes when required.

**Comment by PhrozenByte** [comment]
Looking forward to it, thanks! 👍

**Comment by PiersMorgan** [comment]
I have modified the Docs and i am continuing to do so i am certain i have forked the correct one and made edits accordingly, would you be able to check for me?

**Comment by PhrozenByte** [comment]
Yes, looks good! 👍

**Comment by PiersMorgan** [comment]
I have opened a pull request.
