### ISSUE TITLE
pico cms by  webhosting

### ISSUE THREAD

**Issue by wergin** [picocms/Pico#416]
Hello,
my sites are by a webhoster. There i can not use a shell, f.e. I cannot use a command like "install".  Do I have a possibility to install pico-cms in another way (f.e. like wordpress installing on the browser-window)?
Greetings - wergin

**Comment by PhrozenByte** [comment]
Please refer to the install section in Pico's [`README.md`](https://github.com/picocms/Pico#install), or our [user docs](http://picocms.org/docs/#install), or the [download page](http://picocms.org/download/#install):

> Just [download the latest Pico release](https://github.com/picocms/Pico/releases/latest) and upload all files to the `httpdocs` directory (e.g. `/var/www/html`) of your server.

**Comment by wergin** [comment]
Thanks for the quick answer.
what is with step 2?
`tep 2

Download composer and run it with the install option:
$ curl -sS https://getcomposer.org/installer | php
$ php composer.phar install`

**Comment by PhrozenByte** [comment]
There's no second step when using a pre-bundled release, that's it 😄 `composer` is a completely different installation method.

> You can install Pico either using a pre-bundled release or with composer.

**Comment by wergin** [comment]
Thank you very much!
Now I will start :-)
Greetings wergin
