### ISSUE TITLE
use pico 2.0 in a symfony4 project

### ISSUE THREAD

**Issue by AndreZH** [picocms/Pico#426]
I am trying to incorporate pico 2 into a symfony 4 project to deal with the content and twig templates but i to add it as a bundle or tried to copy the files to the vendor directory but i can't get it running. 
Any ideas or installation instructions anyone?

**Comment by PhrozenByte** [comment]
Refer to Pico's `README.md` for installation instructions. If you need help in how to create a Symfony bundle (i.e. how to use Symfony), you should ask the awesome guys from Symfony. If you have any *concrete* question about Pico, please don't hesitate to ask.
