### ISSUE TITLE
How can I show the Description in Metadata on the top of my page?

### ISSUE THREAD

**Issue by Tyxiang** [picocms/Pico#428]
Just like the [official website](http://picocms.org/about/). Thank you.

**Comment by PhrozenByte** [comment]
Unfortunately I'm not sure what you're trying to achieve, can you please further describe what you're trying to do?

**Comment by PhrozenByte** [comment]
You can access a page's meta data (e.g. the page's description) in your Twig template using `{{ meta.description }}``.

**Comment by Tyxiang** [comment]
I see!
