### ISSUE TITLE
Documentation improvement proposal on URL-Rewrite for Apache, allow .htaccess

### ISSUE THREAD

**Issue by loloyd** [picocms/Pico#435]
Please excuse me for my being a novice in GitHub, PicoCMS and the open-source scene in general but I would like to propose a very little improvement on the documentation regarding the URL-Rewrite feature, especially for self-hosted or locally hosted installations with Apache.  Currently, there's no mention of specifying that .htaccess should be enabled.  I propose that this specification be included in the documentation for completeness.  This is related to version 1.0.6 but may also relate to other versions that did not mention this specification.

For self-installed Apache installations, the option "AllowOverride All" enables .htaccess per-directory overrides in the appropriate Apache conf file.  Example taken from https://www.linode.com/docs/web-servers/apache/how-to-set-up-htaccess-on-apache/

File: `/etc/apache2/sites-available/example.com.conf`
Config snippet:
```
<Directory /var/www/html/example.com/public_html>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
```

The following resources may need to be updated regarding this proposal:
- index.md (on a new installation)
- http://picocms.org/docs/

The following change is therefore proposed:

From:
```
If you're using the Apache web server, URL rewriting probably already is
enabled - try it yourself, click on the [second URL](%base_url%/sub/page). If
you get an error message from your web server, please make sure to enable the
[`mod_rewrite` module][ModRewrite]. Assuming the second URL works, but Pico
still shows no rewritten URLs, force URL rewriting by setting
`$config['rewrite_url'] = true;` in your `config/config.php`.
```
To:
```
If you're using the Apache web server, URL rewriting probably already is
enabled - try it yourself, click on the [second URL](%base_url%/sub/page). If
you get an error message from your web server, please make sure to enable the
[`mod_rewrite` module][ModRewrite] and ensure that .htaccess overrides are
enabled ("AllowOverride All" as an appropriate Directory section option).
Assuming the second URL works, but Pico still shows no rewritten URLs,
force URL rewriting by setting `$config['rewrite_url'] = true;` in your
`config/config.php`.
```

You can probably do better than what I proposed here.  Thank you for your consideration.

**Comment by PhrozenByte** [comment]
Good point, thank you for bringing this up! Fixed in https://github.com/picocms/picocms.github.io/commit/76cb3981e87ac8b4e5104934d994d906683d4bb7 (the docs will be synced later), the changes will go live together with Pico 2.0 (hopefully this or next weekend).
