### ISSUE TITLE
debug mode how to enable, what should I see. Pico 2.0 Beta 3

### ISSUE THREAD

**Issue by omniperspective** [picocms/Pico#436]
I have a problem in my Pico 2.0 Beta-3 system as it will read .twig templates but won't read the pages
in /content except for the index.md file.
https://domain.xyz/ wil get the info from /content.md
but
https://domain.xyz/index will give an error like
+++
Not Found

The requested URL /index was not found on this server.
---

I want to use the debug facility as we had with zz_debug in 1.0.6 and see
in the config file for 2.0 beta 3 this: and put it to "True"
debug: true                    # Enable Twig's debugging mod

But nothing happening? 
Please help me to enable is feature, what can I expect from this feature?

regards Henk.

**Comment by PhrozenByte** [comment]
I'd guess that you've forced Pico into using URL rewriting (`rewrite_url: true` in your `config/config.yml`), even though you haven't configured your webserver proberly. Try https://domain.xyz/?index - it shoulw work fine. You can now either remove `rewrite_url: true` from your `config/config.yml` or refer to the ["URL Rewriting" section](http://picocms.org/docs/#url-rewriting) in Pico's docs to actually make URL rewriting work with your webserver.

`twig_config: { debug: true }` enables **Twig's** debug mode. It isn't relevant here.
