### ISSUE TITLE
Picocms.org is broken when using https

### ISSUE THREAD

**Issue by zingmars** [picocms/Pico#437]
Your site has an invalid SSL certificate and your websites forces all of the assets to be loaded over http no matter which protocol is used when the page is loaded, which breaks the page if no-mixed-content policy is enabled.

![image](https://user-images.githubusercontent.com/917126/41655152-9502c500-7494-11e8-8777-b403e658a3c2.png)

![image](https://user-images.githubusercontent.com/917126/41655255-06fbe902-7495-11e8-8d94-7b76314a5c59.png)

**Comment by PhrozenByte** [comment]
picocms.org unfortunately doesn't support HTTPS yet, but enabling HTTPS is planned though. HTTP support for custom pages is a new feature of GitHub Pages

**Comment by M4rtine** [comment]
HTTPS Work for me. I'm using this

https://github.com/alejandroliu/ForceHttpsPlugin

**Comment by zingmars** [comment]
This is an issue with picocms.org (the website for this project) and not picoCMS itself.

**Comment by M4rtine** [comment]
:D i'm sorry

**Comment by jannejava** [comment]
This is still broken, unfortunately.
