### ISSUE TITLE
.htaccess not getting cloned from git 

### ISSUE THREAD

**Issue by rick4470** [picocms/Pico#45]
The .htaccess is not getting cloned from the git repository not sure if that file is getting ignored, also im having routing issues, i added that .htaccess from the repository to my test server but only the main page is working www.abc.com/ works but www.abc.com/sub/ does not work im sure its related to the .htaccess here is my configs. 
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . index.php [L]
</IfModule>

# Prevent file browsing
Options -Indexes

**Comment by chwilson93** [comment]
I know it's an old issue but just dropping in to say that I had this problem too. Manually grabbed the .htaccess from the repo and all works fine.
