### ISSUE TITLE
Export TWIG from PatternLab and import it in Pico

### ISSUE THREAD

**Issue by RO-ny9** [picocms/Pico#453]
I would like to make atoms, molecules...pages in Twig in PatternLab. Then I want to take these pages and use it in Pico.

Will that atoms (made in PatternLab) still be function in Pico?

**Comment by PhrozenByte** [comment]
Disclaimer: I don't know anything about PatternLab and never used it. I just did about 2 minutes of investigation (i.e. just a quick peek) here...

PatternLab seems to be a static website generator. If you can hook into PatternLab's execution, it *might* be possible the create components that can be used by Pico. At least I can't see a *obvious* reason why it shouldn't be possible. So you should simply try it yourself. Naturally there might be some obstacles and I'm pretty sure there's some (development) work to do, you'll have to take yourself. In the end it might even turn out to be impossible. Nevertheless, it would be great if you share your experience and work with others, and document possible/common problems and obstacles.
