### ISSUE TITLE
Content other than index.md not found

### ISSUE THREAD

**Issue by TimotheeMathieu** [picocms/Pico#456]
Hi,

I am beginner at Pico, I installed picos on a local computer and whenever I want to use a content page other than content/index.md I get the apache not found page (the default page content/index.md works just fine)
"Not Found

The requested URL /home/***/wwwdoc/TEST/index.php was not found on this server.
Apache/2.4.10 (Debian) Server at www.***.fr Port 443"

which is normal because in fact  /home/***/wwwdoc/TEST/index.php doesn't exist (it is the absolute path on the local computer from which I installed pico, but due to unmount & remount things it is not a real absolute path). How can I make pico redirect to an url instead of this absolute path ?

Thank you

**Comment by PhrozenByte** [comment]
If Pico fails to guess the installation's `base_url` due to a complex server config, simply set it manually by adding the following to your `config/config.yml`:

```yml
base_url: https://www.***.fr/TEST
```

Just refer to Pico's `config/config.yml.template` for more info about Pico's config options.

**Comment by TimotheeMathieu** [comment]
Thanks for the fast answer,
I already saw this configuration and I already did that but the error is still the same.

config.yml is 
`
site_title: Test                    # The title of your website
base_url: https://www.math.u-psud.fr/~mathieu/TEST/                
theme: default    `

**Comment by PhrozenByte** [comment]
So, the URL is correct (e.g. https://www.***.fr/TEST/the-name-of-some-page)?

In this case it's the webserver's fault with a inproberly configured `DocumentRoot`, making it impossible to use `RewriteRule`. Please refer to your server admin for further assistance.

In the meantime you can disable URL rewriting by adding the following to your `config/config.yml`:

```yml
rewrite_url: false
```
