### ISSUE TITLE
Update Wiki for Pico 2

### ISSUE THREAD

**Issue by dixonge** [picocms/Pico#458]
When I go to the Wiki page for plugins or themes, the latest list is all for Pico 1 - Pico 2 was released four months ago - are there no themes or plugins for it yet? Will the v1 themes/plugins still work?

**Comment by wlabarron** [comment]
Speaking mainly as a user, I've not done any heavy testing of themes and plugins in the Wiki, however in my experience Pico Menu Hiding, Pico Minify and Pico Placing are all working OK, along with my custom theme (although I am having some trouble with a custom plugin). There are some backwards incompatible changes to Pico in 2.0 according to the [Upgrading](http://picocms.org/in-depth/upgrade-pico-20/) page, but I'd think most Pico 1.0 themes should work OK, maybe with a little modification, until the Wiki is updated with some 2.0 stuff.

**Comment by PhrozenByte** [comment]
Most plugins and themes written for both Pico 0.x and Pico 1.0 should work fine with Pico 2.0. There were some BC-breaking changes indeed, but they affect just a rather small number of use cases, thus it's expected that most "old" plugins and themes work.

Pico's wiki is completely user editable and we don't really maintain the contents there. We'd love to see if you test some plugins and themes (i.e. check whether they work with Pico 2.0) and create a distinct Pico 2.0. Help is highly appreciated! :+1:
