### ISSUE TITLE
path (bis)

### ISSUE THREAD

**Issue by zounp** [picocms/Pico#460]
Hello,
I have read the documentation in installing.
I uploaded pico 2.0.2 to my shared hosting: /domains/somedomainname.something/public_html/subdomainname
Then I loaded in the browser somedomainname.something/subdomainname
Then I got on the page: path (bis) 
If I go to somedomainname.something/subdomainname/index.php I get
Parse error: syntax error, unexpected 'testen' (T_STRING), expecting ',' or ';' in /home/username/domains/somedomainname.something/public_html/subdomainname/index.php on line 36
On a second (and third) attempt I got (no changes made on the server) Cannot find 'vendor/autoload.php'. Run `composer install`.
What to do?
Thanks.

**Comment by PhrozenByte** [comment]
Please strictly follow the installation instructions as stated in Pico's `README.md`, or on our website. You'll have to download a release archive, no source code archive.

**Comment by zounp** [comment]
Hello  PhrozenByte,
Thanks for your help. As I wrote I read the documentation on installing. Especcially this part:
"
I want to use a pre-bundled release

Do you know the feeling: You want to install a new website, so you upload all files of your favorite CMS and run the setup script - just to find out that you forgot about creating the SQL database first? Later the setup script tells you that the file permissions are wrong. Heck, what does this even mean? Forget about it, Pico is different!
Step 1

Download the latest Pico release and upload all files to the httpdocs directory (e.g. /var/www/html) of your server.
Step 2

Okay, here’s the catch: There’s no catch. That’s it! Open your favorite web browser and navigate to your brand new, stupidly simple, blazing fast, flat file CMS! Pico’s default contents will explain how to create your own contents. 😊
"
From (the link from the above text)
     https://github.com/picocms/Pico/releases/tag/v2.0.2
I downloaded
     https://github.com/picocms/Pico/releases/download/v2.0.2/pico-release-v2.0.2.tar.gz
I extracted that gz file and uploaded the contents via FTP to the webserver at the hostingprovider as described before.
The README.md file I found in pico-release-v2.0.2.tar.gz is about the "Pico Deprecated Plugin". It is in /. I think the README.md you refer to is in /pico. It has the same text as above.
I still do not have a clue how to resolve the issue.
What to do?

**Comment by PhrozenByte** [comment]
Please make sure to correctly upload all of Pico's files to your webserver. Double and triple check this. Both errors indicate that something went wrong while uploading Pico's files.

**Comment by zounp** [comment]
Thanks. I counted files with Filezilla. Both the extracted pico-release-v2.0.2.tar.gz file and the files and folders have the same amount of files and folders.
I downloaded the pico files from the webserver to a different folder on my PC and ran diff -r on that folder and the folder with the extracted pico-release-v2.0.2.tar.gz file. No differences were found.
Also, when uploading picocms with Filezilla no errors were encounterd.
The server has Php 5.6.38 Installed and Php 7.1.23 Installed (php2)
What to do?

**Comment by zounp** [comment]
Hello  PhrozenByte,
picocms is running now. I removed the local extraction directory and all the files on the server and extracted again and uploaded agian. Now I have a different set of files and folders. See attachments
[picocms.newset.txt](https://github.com/picocms/Pico/files/2545283/picocms.newset.txt)
[picocms.oldset.txt](https://github.com/picocms/Pico/files/2545284/picocms.oldset.txt)
picocms.newset.txt is working now although there was a catch:
www.domainname.something/subdomainname does not work. I had to enter
 www.domainname.something/subdomainname/index.php in the addressbar
I do not understand why the files in the oldset got extracted and uploaded the way they were. I can not reproduce it.
Thanks for the quick help :-), Zounp

**Comment by PhrozenByte** [comment]
> www.domainname.something/subdomainname does not work. I had to enter
> www.domainname.something/subdomainname/index.php in the addressbar

Check your webserver config, it must be configured to use `index.php` as index file. If you're using Apache, use the `DirectoryIndex` directive. If you're using nginx, use the `index` directive.
