### ISSUE TITLE
Newbie questions

### ISSUE THREAD

**Issue by ctuxboy** [picocms/Pico#467]
Hello,

I'm experimenting with twig variables in pico themes.
Reading this [document](http://picocms.org/docs/#themes)

So trying this:
`<p>{{ page.intro.title }}</p>`
Doesn't work!

`<p>{{ pages.intro.title }}</p>`
Shows the title from the intro.md file!

So if i understand, filter the right page, when the first parameter needs pluralize page**s** ?

In the docs, the variables:
`page.id`
`page.url`
`page.title`
...
are singular.

It is confusing.

**Comment by PhrozenByte** [comment]
The Twig variable `pages` is a list of all pages, indexed by page ID. There's no Twig variable `page` (without `s`), unless you define it; `page.title` refers to the pages loop shown below:

```twig
{% for page in pages if not page.hidden %}
    <p>{{ page.title }}</p>
{% endfor %}
```

This snippet tells Twig to iterate the `pages` list and assign the currently iterated item to the `page` variable.

If you want to access the current page, use `current_page` instead, e.g. `{{ current_page.title }}`.

**Comment by ctuxboy** [comment]
@PhrozenByte thanks for your help!
The reason trying this is building a theme with a 'hidden' md-file:
`_social.md`

Trying out for show in a current page, the only way i found is this:
`{{ pages._social.meta.icon }}`

Is this the right way, for doing this?

**Comment by PhrozenByte** [comment]
Yes.

I'd just recommend using a slightly different syntax. The current syntax doesn't allow you to access pages in sub dirs (like `sub/page.md`). Use `{{ pages["_social"].meta.icon }}` instead.

**Comment by ctuxboy** [comment]
Oh okay, now i understand.
Thanks a lot for your help!
Looking in several themes; but couldn't find a good example.

Thanks a lot man :)
