### ISSUE TITLE
Simple-blog does not work and maintainer is not replying

### ISSUE THREAD

**Issue by iagovar** [picocms/Pico#470]
Hi, I've tried to use the simple-blog theme, as it's _officially supported_ but it doesn't work. I'm not a developer so I don't really understand what happens.

Here's the instance where it's installed: http://iagovar.com/pico/cierre-foros-vogue-histeria-social

The documentation of the theme seems to be old, but I've tried to adapt it to pico 2.0 and configure everything that comes in the README files. Still unsuccessful.

Is this an issue than can be solved from here? thx.

Edit: I forgot to mention that I submitted the issue in the simple-blog github but the guy seems busy with other stuff.

**Comment by PhrozenByte** [comment]
The Clean Blog theme (not "simple-blog") is not a official theme, it's just *promoted*. Both are expected to work with Pico's latest version nevertheless. Official plugins/themes were made by Pico developers and are treated the same way as Pico itself, i.e. if something is broken, we will fix it. If a promoted plugin/theme is broken, it's up to the third-party developer to fix it; if he doesn't, we will remove it from the promoted plugins/themes list.

Anyway, there was some confusion about how to use this theme in the past, so I guess it's the same issue as before: You must add `Template: post` to the YAML Front Matter of all your posts. It's kinda unintuitive I guess... See https://github.com/BesrourMS/clean-blog/blob/master/content-sample/post.md

**Comment by iagovar** [comment]
> Template: post

Well, hope you don't want to kill me but I imported posts from Wordpress to Markdown and I had _layout: post_ instead of _template: post_. It's not even the first time that I do this and I already knew that I had to change it, but somehow I just forgot about it.

Sorry.
