### ISSUE TITLE
Show dates from md-files

### ISSUE THREAD

**Issue by ctuxboy** [picocms/Pico#475]
Hello,
Building my first blog with this awesome CMS.
The homepage shows a list of blogposts.
Adding manual a date in the yml-header of every md-file, then print with twig.
Is it possible or is there a twig filter that can print the original md-file date, without adding a date meta in the header?

**Comment by PhrozenByte** [comment]
We recommend using Pico's default `Date` meta header. Also see #455

**Comment by ctuxboy** [comment]
Hi @PhrozenByte,

Thanks for your fast answer.
Interesting issue (#455)
