### ISSUE TITLE
DOM not loaded error

### ISSUE THREAD

**Issue by kc0dxf** [picocms/Pico#477]
I'm trying to install Pico 2.0.4 on KDE Neon 5.14.  When I go to the Pico site I get the DOM warning:
Pico requires the PHP extension 'dom' to run.  Any ideas how to resolve this?  I've tried putting extension = dom.sa in the php.ini (using php v7.2) but that doesn't work.

**Comment by PhrozenByte** [comment]
You must install the PHP DOM extension. Correct me if I'm wrong, but KDE Neon is based on Ubuntu, right? If this is true, the PHP DOM extension is in the [`php7.2-dom` virtual package](https://packages.ubuntu.com/bionic/php7.2-dom), which is provided by the [`php7.2-xml` package](https://packages.ubuntu.com/bionic/php7.2-xml). Install the `php7.2-xml` package on your system, e.g. by opening a shell and running:

```
$ sudo apt-get install php7.2-xml
```

**Comment by kc0dxf** [comment]
Yes, that package is installed but I still get the message.
