### ISSUE TITLE
Pivo CMS 2.0 sorting menu

### ISSUE THREAD

**Issue by CodeTipsy** [picocms/Pico#481]
Hello,
how to sort menu items in the Pico 2.0 ?

Best regards

**Comment by PhrozenByte** [comment]
Please check Pico's [`config/config.yml.template`](https://github.com/picocms/Pico/blob/master/config/config.yml.template).

**Comment by CodeTipsy** [comment]
My menu: Home, Contact, About us, Impressum, Poducts concert in Home, Products, About us, Contact, Impressum.

config.yml
pages_order_by_meta: ?
pages_order_by: ?
pages_order: ?

What should I do?

Thank you.

**Comment by PhrozenByte** [comment]
Add `nav: 1`, `nav: 2`, `nav: 3`, … to the YAML Front Matter of your pages (use the numbers to define the order of the pages) and use the following `pages_order` config in your `config/config.yml`:

```yml
pages_order_by_meta: nav
pages_order_by: meta
pages_order: asc
```

**Comment by CodeTipsy** [comment]
That's exactly what I was looking for. Works great!
Many thanks PhrozenByte.
