### ISSUE TITLE
Php contact form script in picocms

### ISSUE THREAD

**Issue by CodeTipsy** [picocms/Pico#484]
Hello,
php mail script included picocms - how can I achieve this? 
Insert  html form in contact.md and mail.php?
Thanks for your help.

**Comment by Nepose** [comment]
Hi :smiley: 
The way you propose is possible, though you will have to place `mail.php` in `assets/` folder. Any other location may cause 500 error or requesting script will return 404 error rendered by Pico. In fact, non-Pico-logic PHP should be avoided everywhere outside those assets.
You can also try writing your script like plugin, using Pico events. There is a `getFormParameter` method which gets value of particular POST variables. My idea is, for instance, to post mail to `http://yourwebsite.com/mail`. When loading website, your PHP will look by `onRequestUrl` method for URL - if it is `/mail`, than the form parameters will be read by `getFormParameter` and mail will be sent.
Of course there is also non-PHP, but the simplest Formspree :wink:

**Comment by PhrozenByte** [comment]
You can either use a 3rd-party contact form service (just search for "Contact Form Services", but please keep privacy in mind when using such services) or a plugin for Pico to keep full control. If you choose to use a plugin, please refer to the [Plugins page in our Wiki](https://github.com/picocms/Pico/wiki/Pico-Plugins); it currently lists the following contact form plugins:

- [`nliautaud/p01contact`](https://github.com/nliautaud/p01contact)
- [`ufgum/PicoContactModal`](https://github.com/ufgum/PicoContactModal)
- [`gidlov/pico-contact`](https://github.com/gidlov/pico-contact)

Please note that our Wiki is fully community-driven and all plugins listed there were developed by 3rd-party developers. Unfortunately we can't provide support for them.

**Comment by CodeTipsy** [comment]
Thank you very much for the information!
 That makes me happy.  ;o)
