### ISSUE TITLE
Latest posts at the start page

### ISSUE THREAD

**Issue by CodeTipsy** [picocms/Pico#485]
Hello,
for all posts:
`{% for page in pages|sort_by("time")|reverse %}
    {% if page.id starts with "blog/" and not page.hidden %}
        <div class="post">
            <h3><a href="{{ page.url }}">{{ page.title }}</a></h3>
            <p class="date">{{ page.date_formatted }}</p>
            <p class="excerpt">{{ page.description }}</p>
        </div>
    {% endif %}
{% endfor %}`

And for last post at the start page?
Can you please tell me?

Regards

**Comment by PhrozenByte** [comment]
Try `{% set latest_page = pages|sort_by("time")|last %}` (it's the same as `pages|sort_by("time")|reverse|first`, but skips the `reverse` filter, so that the latest post is actually the last item in the sorted pages list)

**Comment by CodeTipsy** [comment]
`{% for page in pages|sort_by("time")|last %}
                    {% if page.id starts with "blog/" and not page.hidden %}
                        <a href="{{ page.url }}">{{ page.title }}</a>
                        <p>{{ page.date_formatted }}</p>
                    {% endif %}
                {% endfor %}`

Thank you very much for the information.

**Comment by PhrozenByte** [comment]
Sorry, I'm not sure what the exact question is. After setting the latest page's data to the `latest_page` variable, you can access it as usual:

```twig
{% set latest_page = pages|sort_by("time")|last %}
<a href="{{ latest_page.url }}">{{ latest_page.title }}</a> <p>{{ latest_page.date_formatted }}</p>
```

**Comment by CodeTipsy** [comment]
`{% for page in pages|sort_by("time")|last %} {% if page.id starts with "blog/" and not page.hidden %} <a href="{{ page.url }}">{{ page.title }}</a> <p>{{ page.date_formatted }}</p> {% endif %} {% endfor %}`

This code is perfect for my website!
 I just wanted to say thank you for the fantastic service.
