### ISSUE TITLE
Looking for dropdown menu examples

### ISSUE THREAD

**Issue by jtc242** [picocms/Pico#487]
I am not a coder but can cobble together pieces of code to generally do what I want. I am looking for example sites and/or code using pico and drop down menus. I need samples plus the location of the files I need to edit. I have top navigation with upwards of 10 sub pages I want shown in a drop down style. Any help/pointers are appreciated.

**Comment by PhrozenByte** [comment]
The best way to create a recursive page menu is [Pico's page tree feature](http://picocms.org/in-depth/features/page-tree/). You can add the following Twig snippet to your `themes/my_theme/index.twig`:

```twig
{% macro tree(parent) %}
    {% import _self as utils %}
    {% for child in parent.children %}
        <li>
            {% if child.page %}
                <div>{{ child.page.title }}</div>
            {% endif %}
            {% if child.children %}
                <ul>
                    {{ utils.tree(child) }}
                </ul>
            {% endif %}
        </li>
    {% endfor %}
{% endmacro %}

<ul>
    <li>
        <div>{{ pages["index"].title }}</div>
    </li>

    {% import _self as utils %}
    {{ utils.tree(pages["index"].tree_node) }}
</ul>
```
