### ISSUE TITLE
H1 heading for mobile layout to long

### ISSUE THREAD

**Issue by CodeTipsy** [picocms/Pico#488]
`<div id="header><h1><a href="{{ "index"|link }}"><span id="mt">XXX</span><span id="ea">YYY</span><span id="mql">ZZZ</span</a></h1></div>`
My h1 headline is too long.
How can i adjust the size of smartphone layout?

Thanks

**Comment by PhrozenByte** [comment]
This question is rather unrelated to Pico, but HTML/CSS. If the default theme doesn't meet your needs (what's rather expected, Pico's default theme is intended as a starting point for creating a own theme), you can choose to use one of our great 3rd-party themes. You can find a selection of excellent themes [on our website](http://picocms.org/themes/) and a even greater list of themes [in our Wiki](https://github.com/picocms/Pico/wiki/Pico-Themes).

**Comment by CodeTipsy** [comment]
Thanks for the tip.

**Comment by CodeTipsy** [comment]
`@media (max-width: 360px) 
{ 
    #mt { font-size: 0.7em; }
    #ea {  font-size: 1.2em; }
    #mql { font-size: 0.7em; }
}`

Perfect for mobile screen.
