### ISSUE TITLE
Search plugin not working

### ISSUE THREAD

**Issue by paulomorais1981** [picocms/Pico#495]
hi everyone.

i'm using pico cms 2.0 and trying to make 40-pico-search plugin work

i'm using a localhost php server and if i type "localhost:8000/?search" it loads the search page with all pages. seems like the plugin is working (until here it does work), but if I type localhost:8000/?search&q=something, it changes to localhost:8000/search/something and gives me back to homepage.

if i type directly localhost:8000/search/something it gives me back to homepage too. as the form take me to localhost:8000/search/something, it does not work too.

any idea what's going on?

**Comment by PhrozenByte** [comment]
Can you provide a link to the plugin? We'll try our best to help you, but in the end we unfortunately can't provide support for 3rd party plugins.

Since PHP's built-in web server is supposed to be used for short tests only, the first thing to do is installing a "complete" web server like Apache, nginx or Lighttpd and trying again.

**Comment by paulomorais1981** [comment]
Well, i'm using this plugin: https://github.com/PontusHorn/Pico-Search

I understand here is not the place for 3rd-party plugin's support, and I apologize but PicoCMS doesn't have a big community even a forum like stackoverflow...

Anyway, I'll try also to test it in a apache server.

Thanks.

**Comment by paulomorais1981** [comment]
Update: trying to use my picocms install with apache, and when i try `localhost/search/something` i got `not found: 404 error`.

**Comment by PhrozenByte** [comment]
Looks like the plugin requires URL rewriting to be enabled. Please refer to http://picocms.org/docs/#url-rewriting to enable URL rewriting.

**Comment by paulomorais1981** [comment]
Hmmmm, it now worked! There were several days trying to fix it. Thank you!
