### ISSUE TITLE
{{ page.raw_content }} not accessible

### ISSUE THREAD

**Issue by paulomorais1981** [picocms/Pico#497]
Hi,

I'm using Pico 2.0 and trying to access the {{ page.raw_content }} variable in twig, but it's getting empty content.

Is this variable really workable?

Thx.

**Comment by PhrozenByte** [comment]
The `page` variable is for illustration purposes, you still need to define that variable. If you want to access the current page's raw contents, use

```twig
{{ current_page.raw_content }}
```

If you're within a iteration of the `{{ pages }}` list, you can use it like:

```twig
{% for page in pages %}
    {{ page.raw_content }}
{% endfor %}
```

Also see the [Twig documentation](https://twig.symfony.com/doc/1.x/).

**Comment by paulomorais1981** [comment]
Nice. It worked. Need correction on Pico Docs.
