### ISSUE TITLE
parsedown-extra not initializing

### ISSUE THREAD

**Issue by imnjs** [picocms/Pico#498]
I am using the most current master branch of Pico so I could use HTML5 data attributes through parse-down extra. Everything was working fine last night and then suddenly today everything broke and it's showing the `{data-whatever}`s on each page now. It's not doing classes or IDs either. Was there anything that changed recently?

**Comment by imnjs** [comment]
Just FYI, I rolled back to the 2.0.5-beta.1 and same issue.

**Comment by PhrozenByte** [comment]
Did you solve your issue @imnjs? What was the solution?
