### ISSUE TITLE
If the page is save, the symbol disappears

### ISSUE THREAD

**Issue by SciCrea** [picocms/Pico#501]
Pico 2.0.4+Pico Content Editor
Hello! I have a strange case. When I save a document, the same symbol disappears from it. Cyrillic letter - x.

**Comment by PhrozenByte** [comment]
I'm sorry but I just don't understand what your issue is. Please try to elaborate.

**Comment by SciCrea** [comment]
I use plugins Pico Content Editor. When I save the text, some symbols disappear from it. I hope someone else has encountered such a problem and knows the way to solve it.
