### ISSUE TITLE
Plugin proposal: a better support for images

### ISSUE THREAD

**Issue by anasram** [picocms/Pico#504]
Recently I found a _Parsedown_ extension wraps single-image lines in `<figure>` element instead of `<p>`: [FigureExtParsedown.class.php](https://gist.github.com/kantoniak/b1a5c7889e5583824487dc78d93da7cd).

Any one here interested to build a Pico plugin based on it?

Notice that this gist still lacks several features:

* Auto-generate `height` and `width` attributes and values.
* Image might be warped in a link.
* Someday, it should be smart enough to use `<picture>` too in some cases.

**Comment by PhrozenByte** [comment]
Try creating a plugin like the following:

```php
class FigureExtParsedownPicoPlugin extends AbstractPicoPlugin
{
    public function onParsedownRegistered(Parsedown &$parsedown)
    {
        $config = $this->getPico()->getConfig();

        $parsedown = new FigureExtParsedown();
        $parsedown->setBreaksEnabled((bool) $config['content_config']['breaks']);
        $parsedown->setMarkupEscaped((bool) $config['content_config']['escape']);
        $parsedown->setUrlsLinked((bool) $config['content_config']['auto_urls']);
    }
}
```

**Comment by anasram** [comment]
Okay? then? 😕

Actually, I don't speak PHP 😳

Maybe I had to write this issue in a different way:

> **Plugin Proposal**
>
> Any one here interested to build a Pico plugin based on [FigureExtParsedown Class](<https://gist.github.com/kantoniak/b1a5c7889e5583824487dc78d93da7cd>) gist?

**Comment by PhrozenByte** [comment]
Not sure whether someone is going to create a "real" plugin for it and particularly implement the additional features you were asking for, however, the code I provided should do at least the basic job of wrapping images in `<figure>`.

Simply create a `plugins/FigureExtParsedownPicoPlugin/` folder, copy the `FigureExtParsedown.php` from the gist to this folder and create a `FigureExtParsedownPicoPlugin.php` with the following contents:

```php
class FigureExtParsedownPicoPlugin extends AbstractPicoPlugin
{
    public function __construct(Pico $pico)
    {
        parent::__construct($pico);
        require_once(__DIR__ . '/FigureExtParsedown.php');
    }

    public function onParsedownRegistered(Parsedown &$parsedown)
    {
        $config = $this->getPico()->getConfig();

        $parsedown = new FigureExtParsedown();
        $parsedown->setBreaksEnabled((bool) $config['content_config']['breaks']);
        $parsedown->setMarkupEscaped((bool) $config['content_config']['escape']);
        $parsedown->setUrlsLinked((bool) $config['content_config']['auto_urls']);
    }
}
```

**Comment by anasram** [comment]
Here's it so far: [FigureExtParsedownPicoPlugin.zip](https://github.com/picocms/Pico/files/3528936/FigureExtParsedownPicoPlugin.zip).

Didn't work; still wrapping images in `<p>`.

**Comment by PhrozenByte** [comment]
Whoops, there's the API version missing...

```php

class FigureExtParsedownPicoPlugin extends AbstractPicoPlugin
{
    const API_VERSION = 2;

    public function __construct(Pico $pico)
    {
        parent::__construct($pico);
        require_once(__DIR__ . '/FigureExtParsedown.php');
    }

    public function onParsedownRegistered(Parsedown &$parsedown)
    {
        $config = $this->getPico()->getConfig();

        $parsedown = new FigureExtParsedown();
        $parsedown->setBreaksEnabled((bool) $config['content_config']['breaks']);
        $parsedown->setMarkupEscaped((bool) $config['content_config']['escape']);
        $parsedown->setUrlsLinked((bool) $config['content_config']['auto_urls']);
    }
}
```

**Comment by anasram** [comment]
Great, Thank you so much!

It works properly now. 

After considering [a `figcaption` bug](https://gist.github.com/kantoniak/b1a5c7889e5583824487dc78d93da7cd#gistcomment-3013321), here's the final work: [FigureExtParsedownPicoPlugin.zip](https://github.com/picocms/Pico/files/3562242/FigureExtParsedownPicoPlugin.zip).

I think it will be nice if you could publish it officially, with the following TODO list:

* Auto-generate `height` and `width` attributes and values.
* Image might be warped in a link.
* Someday, it should be smart enough to use `<picture>` too in some cases.

**Comment by PhrozenByte** [comment]
I've published it in [our Wiki](https://github.com/picocms/Pico/wiki/Pico-Plugins), see [here](https://github.com/picocms/Pico/wiki/Pico-Plugins/_compare/231c22af0824d001897d359c8eed54f6e231c0c1...affadc0113a5f6a807279dac07e02a718c030cb8)

**Comment by anasram** [comment]
Thanx!
