### ISSUE TITLE
Suggestion: Add .zip version to each release

### ISSUE THREAD

**Issue by versluis** [picocms/Pico#505]
Ahoy, mateys! First time Pico user here. Like many, I got confused and downloaded the source code instead of the release files, which threw up an error on first load. I did what ya'll suggested (many times) and used the release files instead, and everything worked great.
However, my particular server didn't want to let me unTAR the tar.gz file directly. I managed to do it by using another system to unTAR, then ZIP all files and upload to my server, but to cut down on confusion for other first time users, I suggest simply offering two versions of the release files in the future, in addition to the source code (which is already available as ZIP). 
So this is not an issue, just a suggestion (please forgive me if this is posted in the wrong forum).

**Comment by PhrozenByte** [comment]
Hmmm... Weird, are you running a Windows server? `tar` should be available on any Linux system. Anyway, sure, why not, `.zip` definitely got better cross-OS support. We'll create `.zip` archives starting with the next release. :+1:

**Comment by versluis** [comment]
Great! It was a CentOS server actually, and I could have used TAR on the command line. Sadly I only had (easy) access to Plesk at the time, and for some reason it only uses ZIP for extraction from the file manager. I might get in touch with them and ask them to implement tarball support.
