### ISSUE TITLE
Install on GH Pages?

### ISSUE THREAD

**Issue by TheTechRobo** [picocms/Pico#508]
I tried to unpack the release targz file into my thetechrobo.github.io repo and when I tried to type the link to index.php, Waterfox asked me if I want to download the file! NO! I clicked cancel and just a blank screen. please help :)

**Comment by TheTechRobo** [comment]
Nevermind you just don't add index.php at the end :)

Sorry for the dumb question

**Comment by TheTechRobo** [comment]
Oh actually, that loads readme.md 

How do I do thus?

**Comment by Lomanic** [comment]
Pico is not a static site generator (needs a php runtime to render webpages on each access), gh-pages is only able (and only permits) to host static files, not dynamic webpages generated with php for example.

**Comment by TheTechRobo** [comment]
Index.php is included though!

Sent from TtR's iPhone 4

Le 3 sept. 2019 à 15:47, "Lomanic" <notifications@github.com<mailto:notifications@github.com>> a écrit :


Pico is not a static site generator (needs a php runtime to render webpages on each access), gh-pages is only able (and only permits) to host static files, not dynamic webpages generated with php for example.

**Comment by PhrozenByte** [comment]
Just as @Lomanic said, GitHub Pages doesn't support PHP. You'll have to install Pico locally and fetch the output of the resulting website using e.g. `wget -r` (i.e. using Pico as a static website generator). The resulting static `.html` files can then be uploaded to GitHub Pages.

**Comment by TheTechRobo** [comment]
So every time I type another .md file I'll need to do it again?

**Comment by Elte156** [comment]
> So every time I type another .md file I'll need to do it again?

Yes. Every change you make, you'll need to generate the `.html` files again.

**Comment by PhrozenByte** [comment]
It is possible to automatize the necessary steps with a simple script or with tools like Travis CI, however, please keep in mind that GitHub Pages is no classic "webhoster". Pico has extremely low system requirements, you just need PHP - it especially requires no database. You'll find suitable webhosters online starting from below $ 1 per month or even free-of-charge webhosters on which a small Pico website will run just fine.
