### ISSUE TITLE
mbstring error on Debian Buster.

### ISSUE THREAD

**Issue by kc0dxf** [picocms/Pico#509]
I'm migrating to Debian Buster.  I have php version 7.3 and also the php-mbstring package installed.  When I try to go to a fresh pico install I get this error: 
Pico requires the PHP extension 'mbstring' to run

What must I do to get it to work?
Thanks!

**Comment by kc0dxf** [comment]
Thanks for the help.  What happened is that I upgraded Debian Stretch to Debian Buster.  Stretch must have had php 7.0 and when I upgraded to Buster, php 7.3 was installed.  However, Apache was still using php 7.0.  I simply did the following:
a2dismod php7.0
a2enmod php7.3
systemctl restart apache2

Now Pico is working fine!  Thanks for the suggestions.

**Comment by JamesTheAwesomeDude** [comment]
I had this error as well (on the UAH webpages server, which I, obviously do not have administrative access to, thus could not [fix](https://stackoverflow.com/q/8266396) this at a system level)

My solution, which I'm noting here for posterity, was to include an [mbstring polyfill](https://github.com/symfony/polyfill-mbstring)

or, in a nutshell:

	php ~/composer.phar create-project picocms-pico-composer ./blog
	php ~/composer.phar require symfony/polyfill-mbstring -d ./blog

I have a fork created to include this require OOTB; I'm not sure how broad this case is. I'm sure there's lots of people on budget webhosts who'd love/appreciate such an inclusion. (Also, apparently some web frameworks explicitly require said administrative changes NOT to be set; this polyfill at a directory-level allows Pico to coexist on the same server as such frameworks.)
