### ISSUE TITLE
FigureExtParsedownPicoPlugin & markdown IDs & definition lists

### ISSUE THREAD

**Issue by anasram** [picocms/Pico#516]
Pico version: 2.1.0-beta.1

When I use [`FigureExtParsedownPicoPlugin`](https://gist.github.com/PhrozenByte/4977cbb2aae750487d3532cf3715c40a), elements' IDs in markdown don't be converted to HTML ones.

For example:

```markdown
## About {#about}
```

doesn't look in HTML like this:

```html
<h2 id="about">About</h2>
```

rather, it remains like this:

 ```html
<h2>About {#about}</h2>
```

However, when I remove `FigureExtParsedownPicoPlugin`, it works properly.

Definition lists have the same problem.

Is it Pico's fault? or Parsedown's, or it is the plugin itself?

**Comment by PhrozenByte** [comment]
It's the Parsedown extension, it's extending from `Parsedown`, not from `ParsedownExtra`, consequently you can't use any of `ParsedownExtra`'s features. Try replacing the line

```php
class FigureExtParsedown extends Parsedown {
```

by

```php
class FigureExtParsedown extends ParsedownExtra {
```

However, no guarantees, I haven't tested this, Pico 2.1 includes Parsedown 1.8, which changed some internal functions which might break existing Parsedown extensions.

**Comment by anasram** [comment]
Thanks! It solved the IDs' problem.

However, for definition lists, the problem persists.

**Comment by PhrozenByte** [comment]
```
Lorem ipsum dolor sit amet
: Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
```

results in

![Bildschirmfoto von 2019-11-09 10-58-07](https://user-images.githubusercontent.com/920356/68526799-da339e80-02df-11ea-8189-60ddb19cc3bb.png)

in Pico 2.1.0-beta.1 when using `ParsedownExtra`, so it looks like the Parsedown extension somehow prevents `ParsedownExtra` from properly handling the definition lists. Contact the Parsedown extension's developer.
