### ISSUE TITLE
Order the page_tree

### ISSUE THREAD

**Issue by wlabarron** [picocms/Pico#522]
Is it possible to sort the order of the results in the `page_tree`? I'd like to sort my navigation menu in a particular order but using the `sort_by` filter doesn't seem to work.

Using Pico v2.1.0.

**Comment by PhrozenByte** [comment]
Sorting pages in Pico's page tree is virtually the same as sorting Pico's pages list, you just have to keep in mind that you often just sort the pages of a particular branch in Pico's page tree.

The first option to change the order of pages in Pico's page tree is Pico's `pages_order_by` config. It not just affects Pico's pages list, but also Pico's page tree.

You can also use Pico's `sort_by` Twig filter when accessing Pico's page tree via a page's `tree_node`. However, keep in mind that your sort parameter must consider that you're dealing with an tree node, not an page. So you'll have to use something like `{% for child_node in current_page.tree_node.children|sort_by([ "page", "meta", "nav" ], fallback="remove") %}<h2>{{ child_node.page.title }}</h2>{% endfor %}`

However, the best alternative is probably Pico's new `pages()` function. Pico's `pages()` function returns  Just refer to http://picocms.org/in-depth/features/pages-function/ for more details. Use it together with Pico's `sort_by` Twig filter, e.g. `{% for child_page in pages(current_page.id)|sort_by([ "meta", "nav" ]) %}<h2>{{ child_page.title }}</h2>{% endfor %}`
