### ISSUE TITLE
Formatting of menu links

### ISSUE THREAD

**Issue by Zarxrax** [picocms/Pico#524]
I just simultaneously upgraded to Pico 2.1 while switching hosting providers for my site, so I'm not sure which of those things might have caused this change.

My links in the menu used to be formatted like "site.com/?main" but now they are formatted like "site.com/main".

I'm not sure what might have happened to change to cause the question marks to be removed, but it seems to be causing some issues with some of my pages. Any ideas what I might need to look at to get this back to the old behavior?

**Comment by PhrozenByte** [comment]
You enabled URL rewriting, see http://picocms.org/docs/#url-rewriting

You can force-disable it by adding the following to your `config/config.yml`:

```yml
rewrite_url: false
```

**Comment by Zarxrax** [comment]
Thanks, that did the trick. Apparently it enabled by default on my new server but not on the old one.
