### ISSUE TITLE
ssl problem http://page:80

### ISSUE THREAD

**Issue by lollita** [picocms/Pico#526]
I have a problem with port in a https web site.
I solved adding:
} else {$port='';
to line 2201 of Pico.php
after
if ($hostPortPosition !== false) {

**Comment by PhrozenByte** [comment]
Fix your webserver config. Your `HTTP_HOST` environment variable tells PHP contradictory data on which port it's running.

**Comment by lollita** [comment]
I not have access to server and then I have to forecast in my script.

**Comment by PhrozenByte** [comment]
In this case you should report this webserver misconfiguration to your webserver administrator. As an alternative you should manually configure Pico's `base_url` in `config/config.yml` instead of editing Pico's source code.
