### ISSUE TITLE
List of all articles divided by month, with if condition

### ISSUE THREAD

**Issue by stefanocpp** [picocms/Pico#527]
Hello,

my Pico installation runs a small blog I have fun writing on.
The `Archive` page of my website has a list of all published articles, divided by month, and is updated manually by me every time I post a new article. This is how it [looks like](https://www.bitingapples.com/archive) right now.
For about one year now, I've tried to automate this process, with mixed fortunes, by using Twig. Here's what I've come up with so far

```
{% for i in range(0, 60) %}  
{% set prev_month = "now"|date("F y")%}  
	{% set prev_month = prev_month|date_modify("-" ~i~ "month")|date("F y") %}  
		<h2>{{prev_month}}</h2>
	{% for page in pages|sort_by("time")|reverse if page.time and not page.meta.unlisted %}
              {% if page.time|date("F y") == prev_month %}
                   <a href="{{page.url}}" title="{{page.meta.description}}">{{ page.title }}</a><br>
             {% endif %}
     {% endfor %}
{% endfor %}
```
this works, and I was very proud of having made it so far, but there are some issues, namely:
- months print out even if no page exists in that month
- I cannot format the date as I want because the whole routine stops.

I have tried several different things with months of trial-and-error learning, plus some looking around, but haven't found a solution yet and I'm not explaining all of them here just for brevity sake.
I'm asking it directly, in the end, because I think it could benefit somebody else too and could even be added to the cookbook if considered to be valuable enough.

I'd like to leverage only on page.time as a parameter, as all articles I've written so far have it. Going through all existing pages to add something in the YAML header would overcome the usefulness of automating this process.

Thank you very much, I've always learned something new reading issues ;)

**Comment by PhrozenByte** [comment]
You're actually pretty close. Simply use the (sorted) `pages` list (by the way: you should think about using Pico's new `pages` function instead, see http://picocms.org/in-depth/features/pages-function/) for your loop and print new months as soon as they occur for the first time.

The following snippet is untested:

```twig
{% set current_month = "" %}
{% for page in pages|sort_by("time")|reverse if page.time and not page.meta.unlisted %}
    {% if page.time|date("Y-m") != current_month %}
        {% set current_month = page.time|date("Y-m") %}
        <h2>{{ page.time|date("F 'y") }}</h2>
    {% endif %}
    <a href="{{ page.url }}" title="{{ page.meta.description }}">{{ page.title }}</a><br>
{% endfor %}
```

**Comment by stefanocpp** [comment]
Thank you, it works!
I love how elegant and succinct your code is with respect to mine. I'll study your snippet and ask if I don't understand something (if I may).
I tried to read the linked pages months ago, but couldn't understand much. I'll give it another try, but how would the above code change if I were to use the new `pages()` function? So that I can study that too to understand the new function :)
Thank you again <3

**Comment by PhrozenByte** [comment]
Assuming all pages you wanna list on that page are in folders like `content/archive/<year>/<month>`, you could use `pages("archive", depth=2, depthOffset=2)` instead of the raw `pages` list (i.e. `{% for page in pages("archive", depth=2, depthOffset=2)|sort_by("time")|reverse %}`).

**Comment by stefanocpp** [comment]
Thank you very much once again!

If you think it could be valuable, we could add this to the cookbook...
