### ISSUE TITLE
How to merge strings?

### ISSUE THREAD

**Issue by Roman1001** [picocms/Pico#531]
Hi,

In PHP, you can merge two strings like this:
When `$username` = `John`,  `"Hello " . $username . "!"` produces `Hello John!`.

Can we do that also in Twig?

**Comment by marcus-at-localhost** [comment]
`{{ 'http://' ~ app.request.host }}`

https://stackoverflow.com/a/7704889/814031

**Comment by Roman1001** [comment]
Thank you very much!
