### ISSUE TITLE
Enable plugin only for one page?

### ISSUE THREAD

**Issue by ohnonot** [picocms/Pico#533]
Is this possible?
Maybe like this:
- disable it in `config.yaml`
- explicitely enable it either through the page's YAML header or by using a specific template, and enable it inside the twig template

AFAICS, it would require the usage of something like `config.PluginName.enabled: true`?

**Comment by PhrozenByte** [comment]
You'll have to write a plugin to accomplish this. If you want to go with the YAML header solution, you'd have to hook into the `onMetaParsed` event, check for your variable and possibly enable said plugin using `$this->getPico()->getPlugin('name_of_plugin')->setEnabled(true);`
