### ISSUE TITLE
How to set favicon on your Pico site?

### ISSUE THREAD

**Issue by Alepod** [picocms/Pico#536]
How to set favicon on your Pico site?

**Comment by PhrozenByte** [comment]
Like always: Add `<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">` to your theme's `<head>`.

**Comment by Alepod** [comment]
Where should I place .ico file in this situation?

**Comment by KoljaL** [comment]
in the root folder of your webspace.
probably there, where the index.php of picoCMS is.

**Comment by Steve-K9** [comment]
has anyone managed to achieve this on a Raspberry Pi Pico W ?
