### ISSUE TITLE
Preferable way to force HTTPS connection?

### ISSUE THREAD

**Issue by Alepod** [picocms/Pico#537]
Preferable way to force HTTPS connection?

**Comment by KoljaL** [comment]
maybe this way: https://github.com/alejandroliu/ForceHttpsPlugin

**Comment by PhrozenByte** [comment]
You shouldn't leave this up to a application, but rather configure your webserver accordingly. HTTPS is no application-level setting. For example, if you're using Apache, your virtual host config for HTTP/port 80 shouldn't contain a `DocumentRoot` directive at all, but a `Redirect` directive. HSTS headers should be added using Apache's `mod_header` module. Just google for `<your webserver> force ssl`.
