### ISSUE TITLE
Export everything to static html

### ISSUE THREAD

**Issue by ArsNeurochirurgica** [picocms/Pico#539]
Hi together,

I came across PicoCMS and I am converting my Worpdress site to PicoCMS right now. It looks really great and I am a big fan of its simplicity! However is there a way in the current release or in one of the upcoming releases to export everything as a static html site? Right now I don't need the search function and it seems the only reason not to export everything to a static html site would be the need of a search function.

Thank you very much in advance and great job on this project!

**Comment by KoljaL** [comment]
this workes for me: https://github.com/glumb/pico_cache
and many more: https://github.com/picocms/Pico/wiki/Pico-Plugins

**Comment by PhrozenByte** [comment]
Pico is no static website generator, so there's currently no built-in feature to export the contents of a Pico website to static HTML pages. However, exporting ("crawling") a website is no big deal in general. You could use e.g. `wget -r` to create a local static copy of your website. Try something like the following:

```sh
wget -r -l inf -N -k "http://localhost/pico/"
```

**Comment by ArsNeurochirurgica** [comment]
Thank you very much for your quick help guys, these are great approaches !

**Comment by Croydon** [comment]
Would it be a reasonable feature request to add an export to a static site as a default feature?
