### ISSUE TITLE
PicoCMS - NextCloud - Access content folder images secured

### ISSUE THREAD

**Issue by nunomdmgoncalves** [picocms/Pico#541]
Hi All, I have a picoCMS running on nextcloud real smooth. Although, I am experiencing an issue with group permissions on images and md files on picoCMS app (1.0.3) for nextcloud, folders. 
Specifying access on md header files I can control which group can see or not an md file on a web browser, this is cool !! 

But then, I also want to control the local images on the same folder as the md file, also to that same group, and I want to reference the image on the filesystem in order to automatically change the image with a cron job on linux. 

I already achieve that using the assets folder, but in that folder I can't get the control to a specific group working on the assets sub folder. I Tried the share option on nextcloud folder system and it was no good. Any image on the assets folder or sub folder are viewed by everybody.

The ideal setup is to upload a image to the filesystem (with an scp for example), have the permissions changed in order to the apache webserver can read it, and that way only the folder group can access it image as well as the md file.

The md file load the image by something like ! [alt text] (content/folder/images/image.png)
And the md file would stay on the path (content/folder)

Does anyone know how to do that ? 
thanks you very much for your time reading this.
Nuno

**Comment by PhrozenByte** [comment]
Please refer to https://help.nextcloud.com/c/apps/cms-pico/128 for getting help about Pico CMS for Nextcloud. This is the repository of Pico. You can find the app's repository here: https://github.com/nextcloud/cms_pico. Since I can't transfer issues from this repo to the `cms_pico` repo, please open a new issue there.
