### ISSUE TITLE
Enhancement request: include Smartypants option

### ISSUE THREAD

**Issue by dajare** [picocms/Pico#542]
It would add to the refinement of Pico to have content passed through a typography filter. The standard accompaniment to Markdown is [Smartypants][s], but there is also [PHP SmartyPants][p].

I enquired about this on [the Parsedown repo issue list][i], and got a quick response that is hopeful. I'm not sufficiently familiar with Pico's architecture to know where such an additional filter should be placed.

This is probably a fairly easy enhancement ... if you know what you're doing! 😉  I don't. 🤷‍♂️ Any thoughts from the Pico devs? Thanks!

[i]: https://github.com/erusev/parsedown/issues/766
[s]: https://daringfireball.net/projects/smartypants/
[p]: https://michelf.ca/projects/php-smartypants/

**Comment by PhrozenByte** [comment]
You might wanna create a plugin to hook into Pico's [`onContentLoaded`](https://github.com/picocms/Pico/blob/master/plugins/DummyPlugin.php#L219), [`onContentPrepared`](https://github.com/picocms/Pico/blob/master/plugins/DummyPlugin.php#L270) or [`onContentParsed`](https://github.com/picocms/Pico/blob/master/plugins/DummyPlugin.php#L284) events.
