### ISSUE TITLE
Option (or plugin) to change titles level

### ISSUE THREAD

**Issue by raspbeguy** [picocms/Pico#543]
Hello,

I think it would be great to have an option enabling to automatically change title levels.

For now, markdown title levels can only be matched to equivalent HTML levels: `#` to `h1`, `##` to `h2`, etc...

But on some cases, with some special templates, we might want to shift down the title levels.

Let's say we have a (weird) template like this:

```html
<h1>{{ meta.title }}</h1>
  <h2>Metadatas</h2>
    <h3>Author</h3>
{{ meta.author }}
    <h3>Tags</h3>
{{ meta.tags }}
  <h2>Content</h2>
{{ content }}
```

It would make no sense that `#` in the markdown should become `h1`. The only solution would be to be aware, as the writer, that you shouldn't use `#` or `##` levels, which I find not very handy, especially if the writers are different people than the webmasters and have no idea how it works.

In this scenario, the feature I dream of would shift `#` to `h3`, `##` to `h4`, etc...

It could be materialized with a setting `titleshift`, which default is 0. In the example I gave, it would be 2.

Thanks for your attention.

**Comment by PhrozenByte** [comment]
This would require you to write a [Parsedown](https://github.com/erusev/parsedown) plugin. You can then hook into Pico's `onParsedownRegistered` event to load the plugin.

**Comment by raspbeguy** [comment]
I'm not at ease with PHP so that's why I ask here. Else I would have done it already.

**Comment by raspbeguy** [comment]
Also, I don't see how it would help me...
