### ISSUE TITLE
Deprecated warningin PHP7.4

### ISSUE THREAD

**Issue by softon** [picocms/Pico#548]
Deprecated
: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in
F:\laragon\www\picocms\vendor\twig\twig\lib\Twig\Node.php
on line
42

Deprecated
: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in
F:\laragon\www\picocms\vendor\twig\twig\lib\Twig\Node.php
on line
198

**Comment by PhrozenByte** [comment]
Duplicate of #534 

You can either hide this error or give [Pico `v3.0.0-alpha.1`](https://github.com/picocms/Pico/releases/tag/v3.0.0-alpha.1) (see #535) a try, see https://github.com/picocms/Pico/issues/534#issuecomment-605638655
