### ISSUE TITLE
Pages plugin incompatible?

### ISSUE THREAD

**Issue by youcantryreachingme** [picocms/Pico#551]
New to picocms. Downloaded the pages plugin, modified my template to reference 

`for page in pages_pages|sort_by("time")|reverse`

and got the error: 

Fatal error: Uncaught exception 'Twig_Error_Runtime' with message 'The sort_by filter only works with arrays or "Traversable", got "NULL"' 

Of course, removing the filter doesn't solve it, because the call is returning null.

I note in the plugin's documentation it includes the below note:

```
For reference, these values are set in config.php using the following format:

$config['pagination_limit'] = 10;
$config['pagination_output_format'] = "list"

```
I saw this reference to $config['some value'] in another plugin's documentation too - but it doesn't correlate with the syntax I find in my config file. I am guessing these plugins were developed for version 1 of picocms (and I am using version 2)?

If so, perhaps the picoCMS website should be cleaned up, with regard to the plugins page, to clarify exactly which plugins are/aren't available for the latest version of the CMS?

**Comment by Lomanic** [comment]
Looks like you are talking about this plugin https://github.com/rewdy/Pico-Pagination

The wiki is more explicit about the versions plugins support https://github.com/picocms/Pico/wiki/Pico-Plugins

Did you remove or disable the [PicoDeprecated plugin](https://github.com/picocms/pico-deprecated)?

**Comment by PhrozenByte** [comment]
> `for page in pages_pages|sort_by("time")|reverse`

I assume it's supposed to be:

```php
{% for page in paged_pages|sort_by("time")|reverse %}
```

**Comment by youcantryreachingme** [comment]
> Did you remove or disable the [PicoDeprecated plugin](https://github.com/picocms/pico-deprecated)?

Thanks for the wiki link - I will take a look around. There are certainly more plugins here than listed on the picocms homepage - and a few look very useful from their names..

My plugins folder has a folder named PicoDeprecated which contains several files. I actually didn't know what it was until I started reading the info following your link. The two plugins I've tried have both said to simply drop a single PHP file into the plugins folder - but I had issues getting either to work. Was I doing this correctly (ie. even though this PicoDeprecated pugin has a folder within the plugins directory)?

**Comment by youcantryreachingme** [comment]
> I assume it's supposed to be:
> 
> ```
> {% for page in paged_pages|sort_by("time")|reverse %}
> ```
Yes - I meant the opening and closing characters as implied.

**Comment by PhrozenByte** [comment]
> > I assume it's supposed to be:
> > ```
> > {% for page in paged_pages|sort_by("time")|reverse %}
> > ```
> 
> Yes - I meant the opening and closing characters as implied.

This was rather about your typo, `pages_pages` instead of `paged_pages` :wink:

**Comment by Lomanic** [comment]
I would suggest to use my own fork of the Pico-Pagination plugin as my pull request https://github.com/rewdy/Pico-Pagination/pull/14 was never merged. Otherwise, even non-existing pages will be served with a 200 HTTP status.
