### ISSUE TITLE
How to change locale

### ISSUE THREAD

**Issue by Discostu36** [picocms/Pico#552]
I'm not sure how to set my locale in Pico. At the moment all weekdays and months are written in English. If I understand it correctly, PHP would write them in German with the command `setlocale (LC_TIME, "de_DE");` But how can i do so in Pico?

**Comment by PhrozenByte** [comment]
It's a PHP setting, i.e. required changing your `php.ini`. However, @asdfuser opened a pull request (#546) to include a `locale` config option in Pico's `config/config.yml` that wasn't released yet. I just released [Pico v2.1.3](https://github.com/picocms/Pico/releases/tag/v2.1.3) which includes said option.

**Comment by Discostu36** [comment]
I don't think my webhoster allows me to edit php.ini, so this is perfect timing. Will try it out, thanks!

**Comment by Discostu36** [comment]
It works, thanks again!
