### ISSUE TITLE
Want to contribute, don't have time to commit fully

### ISSUE THREAD

**Issue by HLSiira** [picocms/Pico#553]
Hello,

I want to know if there was a way I could pass on some of the plugins I've made for the most recent release of Pico. 
So far I've made/remade: An RSS Feed, A PageCount/Popular Posts, a Pagination, an updated PicoOutput, and soon I'm going to try to knock out the Search plugin, and BreadCrumbs, maybe even a ContactWidget.

I'm a big fan of Pico, however I'm super finicky about the software I use so I've been hacking away at Pico to make it smaller and to meet my needs. As a result, I have the plugins above working on an install without the PicoDepreciated Plugin running that  I think someone else might want to use on their blog or whatever.

Sadly, I have a lot on my plate right now and I can't spend a lot of time refining them / documentation, but the core code and logic is pretty strong and easy to take on. If you have any suggestions on what you recommend I do, I would really appreciate it. If nothing else, I might just drop them all into a single repo and try to get that repo added to the wiki list for reference.

Thank you, Pico is pretty awesome.

**Comment by PhrozenByte** [comment]
Sure, looking forward to it! Simply add your plugins to [Pico's wiki](https://github.com/picocms/Pico/wiki/Pico-Plugins) :+1: 

One repo per plugin is preferable. We don't really have any demands on plugins listed in Pico's wiki (in contrary to plugins recommended on Pico's website), however, documentation should at least tell users how to use your plugins. But that's it :smiley:

**Comment by HLSiira** [comment]
Alright so I made a repo to hold all the plugins I've made and short explanations for each but for now, that's all I can commit.

I went to edit the wiki page to add my plugins, but wasn't sure how you'd like me to add them. I decided to add a Pico Collection to the third party section.

Let me know if that doesn't work for you.

Thank you again for making a pretty cool CMS.
