### ISSUE TITLE
What is debug mode?

### ISSUE THREAD

**Issue by Discostu36** [picocms/Pico#554]
[This option in `config.yml`](https://github.com/picocms/Pico/blob/master/config/config.yml.template#L8) needs documentation:
```` 
debug: ~                            # Set this to true to enable Pico's debug mode
````
I couldn't find any information about what debug mode does. Enabling it doesn't seem to change anything for me.

**Comment by PhrozenByte** [comment]
It enables Twig's debug mode.

**Comment by Discostu36** [comment]
If it should do what [this website is describing](https://befused.com/drupal/twig-debug), it doesn't. I don't have any comments in my source code.

**Comment by PhrozenByte** [comment]
If you think this is useful in general and not just for Drupal, you should suggest this to [`twigphp/Twig`](https://github.com/twigphp/Twig).

**Comment by Discostu36** [comment]
Sorry, I still don't get it. My question still is: What does Twig's debug mode do in Pico CMS? If it's not writing comments into the DOM like in Drupal, what does it do instead?

**Comment by PhrozenByte** [comment]
Pico is not Drupal, so you can't assume random Drupal features to be supported in Pico. This is a Drupal-specific feature. If you think that Twig should include such debug comments when Twig's debug mode is enabled, you should suggest the Twig developers to add such a feature to Twig. Pico just enables Twig's debug mode, no more, no less. See https://twig.symfony.com/doc/1.x/api.html#environment-options and https://twig.symfony.com/doc/1.x/functions/dump.html

**Comment by Discostu36** [comment]
I'm more confused than ever not that I have seen that the file also has this in [line 24](https://github.com/picocms/Pico/blob/master/config/config.yml.template#L24):

```
twig_config:                        # Twig template engine config
    [...]
    debug: ~                        # Enable Twig's debug mode
```

Do both options do the same? Or is the debug option we talked about above something else than Twig's debug mode?

And one thing about the Label for this issue: Sure, somehow this is a question. But what I actually want to archive is that the documentation gets improved.

**Comment by dcrobertson01** [comment]
So how *do* we debug pico?
