### ISSUE TITLE
404.md doesn't give a 404

### ISSUE THREAD

**Issue by Discostu36** [picocms/Pico#556]
If I open a page that doesn't exist, the 404 page is opened. But the server does not give a 404 response but a 200. Is this a problem in my installation?

**Comment by Lomanic** [comment]
Are you using @rewdy's [Pagination plugin](https://github.com/rewdy/Pico-Pagination) by any chance? In this case, see my comment here https://github.com/picocms/Pico/issues/551#issuecomment-652521872

**Comment by Discostu36** [comment]
> 
> 
> Are you using @rewdy's [Pagination plugin](https://github.com/rewdy/Pico-Pagination) by any chance? In this case, see my comment here [#551 (comment)](https://github.com/picocms/Pico/issues/551#issuecomment-652521872)

Actually, I do. The problem disappeared with your version. Thank you very much! I think that your fork should be listed on the plugin page instead of the original.

**Comment by Discostu36** [comment]
I still think the plugin page should be changed

**Comment by PhrozenByte** [comment]
A pull request is welcome :+1:

**Comment by Lomanic** [comment]
No need to change anything as the MR is now merged. This issue should be closed.
