### ISSUE TITLE
Updated config.yml.template with 'locale' changes did not make it into 2.1.3 release archive file(s)

### ISSUE THREAD

**Issue by ghost** [picocms/Pico#557]
Looking at the 2.1.3 release.

The tagged 2.1.3 tag archives have the correct config.yml.template file with 'locale' changes.

https://github.com/picocms/Pico/archive/v2.1.3.tar.gz
https://github.com/picocms/Pico/archive/v2.1.3.zip

The release archives i.e.:

https://github.com/picocms/Pico/releases/download/v2.1.3/pico-release-v2.1.3.tar.gz
https://github.com/picocms/Pico/releases/download/v2.1.3/pico-release-v2.1.3.zip

Do not have the 'locale' changes in config.yml.template.

**Comment by PhrozenByte** [comment]
Fixed with [`v2.1.4`](https://github.com/picocms/Pico/releases/tag/v2.1.4)

Thank you for reporting this! :+1:
