### ISSUE TITLE
German umlauts in page titles

### ISSUE THREAD

**Issue by kellerfrau** [picocms/Pico#561]
When using German umlauts in page titles, e.g. "Über mich", the link is not displayed on the menu. "Ueber mich" works, of course, but is only usable with the file name (uebermich.md) but not proper German for any navigation. Replacing the Ü with

```&Uuml;```  

breaks the display as well, then "Über mich" is displayed just as "mich".

This is tested locally using a fresh install with the default theme.

**Comment by PhrozenByte** [comment]
Wrong repo :wink: 

Make sure to save your files in UTF-8 encoding. Usually there's a appropriate setting below "Edit" in your editor's window menu. You can't use Windows' built-in notepad editor, because it only saves files in Windows-1252 encoding.
