### ISSUE TITLE
contact form plugin guidance

### ISSUE THREAD

**Issue by smpcasgit** [picocms/Pico#562]
hi there,
i know it is possible to use external services for sending emails, but i would prefer a plugin.

at the beginning of pico there were contact form plugins but they are now out of date and no longer work with the new pico version. 

is there any instruction somewhere for a contact form plugin with e.g. phpmailer.

you say it's easy to create plugins, would that be so where are they then. maybe someone has a plugin in the basement or has some easy instructions for an contact form. i would like to help but i'm a noob in coding.

thank you

**Comment by PhrozenByte** [comment]
Check out our wiki to get a more extensive list of 3rd party plugins available: https://github.com/picocms/Pico/wiki/Pico-Plugins

`p01contact` is a fully-featured contact plugin for Pico: https://github.com/nliautaud/p01contact
