### ISSUE TITLE
Incompatible plugin: Plugins for Pico CMS for Nextcloud must use one of the API versions 1, 2, 3, but this plugin uses API version 0.

### ISSUE THREAD

**Issue by GeneriumMadness** [picocms/Pico#565]
In your [plugins wiki](https://github.com/picocms/Pico/wiki/Pico-Plugins) I found [pico-redirect](https://github.com/nebman/pico-redirect) plugin, but when I installed it into my Nextcloud instance I got only this error
![Error](https://user-images.githubusercontent.com/29273152/91770040-22161000-ebe9-11ea-8e65-2de5854614b1.png)

I have not changed the files of this plugin, i don't know how to change it and make it work. I need only working redirect plugin please.

**Comment by Lomanic** [comment]
As stated in the wiki this plugin is deprecated, it is not compatible with Pico nowadays.  But this plugin is only a few lines long, [you can easily migrate it to the 1.0 API](http://picocms.org/development/#migrating-from-0x-to-10).

**Comment by PhrozenByte** [comment]
Untested, but should work: https://gist.github.com/PhrozenByte/247e65a6b11790fc304de78e105347db

Please give feedback whether it works.

**Comment by GeneriumMadness** [comment]
> Please give feedback whether it works.
![image](https://user-images.githubusercontent.com/29273152/91836823-fb40f380-ec53-11ea-9599-f7cae1d34493.png)

**Comment by GeneriumMadness** [comment]
i repaired it, but redirection didn't work

**Comment by PhrozenByte** [comment]
Updated, try again.

**Comment by GeneriumMadness** [comment]
Works perfectly, you have to put it on the first page of the best pico plugins! Thank you very much.
