### ISSUE TITLE
Symbolic links in content directory

### ISSUE THREAD

**Issue by andy47** [picocms/Pico#567]
I've got my site contents in a folder under my home directory. I have then symlinked these files to the content folder in my Pico installation under /var/www/pico 
But I get a 404 for any symlinked file. When I create a file directly in the content folder Pico works fine. 

I've checked file/link ownership and permission and everything looks OK to me.

I know that symlinking is working fine because I've linked an html file from my home directory to /var/www/html and that is appearing just fine.

This is running under Apache - initially on Mac OS but I'm having the same issue on Ubuntu 20.04.

Can anyone let me know what I need to do to get symbolic links resolved and rendered by Pico?

**Comment by PhrozenByte** [comment]
Your PHP is verly likely configured not to include arbitrary files using a `open_basedir` restriction. Check your `php.ini`. Symlinks should work just fine with Pico - as long as PHP actually has permission to read that file.

**Comment by andy47** [comment]
Thanks, it was permissions. When I granted the Apache user (www-data) permission on the directory with the .md files in it the site started working. Thanks very much for the pointers.
