### ISSUE TITLE
themes and templates in user space?

### ISSUE THREAD

**Issue by rschulzUK** [picocms/Pico#568]
I have only just started exploring Pico, under non-ideal circumstances: I am using a Hetzner Storage Share (Nextcloud 19) cloud server. It is not meant to be used for web hosting, but Pico installed just fine and the example site works. However, I have no console access to the server and no access to the folders containing Pico themes and templates via the Nextcloud web interface. So, I am currently stuck with the default theme. Can Pico use theme and template files that are stored in a user's home directory and if so, how? Much appreciated.

**Comment by PhrozenByte** [comment]
This is the repo of Pico, not for Pico CMS for Nextcloud. Please re-open a issue there; unfortunately we can't transfer the issue there.

To answer your question in a shortly: You can't use any custom themes unless you have FTP access to Nextcloud's `data` folder. This is on purpose and by design.
