### ISSUE TITLE
How to I specify ISO language code?

### ISSUE THREAD

**Issue by BenNottelling** [picocms/Pico#569]
Hello, I'm currently rebuilding my website with Pico and it's a really nice simple software, but I can't figure out how I can specify the language of the webpage?
With HTML it would just be but I can't seem to find a solution for it (other than just adding HTML)
```
<html lang="en">
```

**Comment by PhrozenByte** [comment]
Simply use a custom meta header, e.g. in Markdown files

```markdown
---
title: My example page
lang: en
---

Some content
```

and in your Twig template

```twig
<html lang="{{ meta.lang }}">
<!-- … -->
```

You could even use a config option as fallback by adding the following to your `config/config.yml`

```yaml
theme_config:
  lang: en
```

and something like the following in your Twig template

```twig
<html lang="{{ meta.lang ?? config.theme_config.lang }}">
<!-- … -->
```

This way you don't have to add the `lang` meta header to your pages, but rely on a default value.

**Comment by BenNottelling** [comment]
That perfectly answers my question. Thank you!
