### ISSUE TITLE
SmartAdCheck

### ISSUE THREAD

**Issue by raffaelmiribung** [picocms/Pico#570]
Dear Pico-Community,

Ever since I installed PicoCMS on my server, I get the following console logs:

Laden fehlgeschlagen für das <script> mit der Quelle "https://abp.smartadcheck.de/js/abpc.js?#ads/banner/ad/".
(eng.: Failed to load the script with source "...") and I get the same log, whenever I open the PicoCMS website.

I do know why it fails B) but I'd like to know where these connection attempts are coming from. The URL 'smartadcheck.de' resolves to adgoal.net, which is an affiliate marketing company and I do know that these connection attempts only happen on my site running Pico and the PicoCMS website itself. 

Does anyone know more about this?

All the best and stay safe!

**Comment by PhrozenByte** [comment]
Pico doesn't include any 3rd-party resources by default and is fully self-containing, so this is included either by your Markdown files or by your custom theme. Check your Markdown files and your theme's Twig templates, somewhere there's a `<script>` tag with this source.
