### ISSUE TITLE
Is Pico still active in terms of future development/enhancement?

### ISSUE THREAD

**Issue by tsawitzki** [picocms/Pico#571]
Wondering if this project is still in active maintainance including plans for future releases before I would recommend it for a client project. Is there any official information on the current state of the project?

**Comment by PhrozenByte** [comment]
It is. Pico has simplicity built into its core concept, less code causes less issues, requiring fewer updates. The latest v2.1.4 is from August and there's no newer release because we haven't had any new issues since. For plans about Pico 3.0 see #317 and #535. Help is appreciated :heart:
