### ISSUE TITLE
Does Pico have an admin panel?

### ISSUE THREAD

**Issue by adamrydza** [picocms/Pico#573]
Hi. I have a question. Does Pico have an admin panel? If I create a website for a client, will he have a place where he can easily and quickly change the content of the website: texts, pictures, headers, etc.? One more thing ... Can I use Pico commercially, so can I base my pages on Pico that I create for clients?

**Comment by PhrozenByte** [comment]
Please refer to http://picocms.org/plugins/ and https://github.com/picocms/Pico/wiki/Pico-Plugins, e.g. https://github.com/blocknotes/pico_edit or https://github.com/PhrozenByte/pico-admin
