### ISSUE TITLE
Plugin PicoAdmin problem

### ISSUE THREAD

**Issue by adamrydza** [picocms/Pico#574]
Hello. I downloaded Pico Admin plugin (https://github.com/PhrozenByte/pico-admin) and then copied the plugin folder to the "plugins" directory. Now after entering: "http: // localhost / cms /? Admin" something like this pops up:
Fatal error: Uncaught RuntimeException: Unable to load plugin 'PicoEdit' from 'PicoEdit/PicoEdit.php': File not found in D:\xampp\htdocs\cms\vendor\picocms\pico\lib\Pico.php:671 Stack trace: #0 D:\xampp\htdocs\cms\vendor\picocms\pico\lib\Pico.php(552): Pico->loadLocalPlugins(Array) #1 D:\xampp\htdocs\cms\vendor\picocms\pico\lib\Pico.php(424): Pico->loadPlugins() #2 D:\xampp\htdocs\cms\index.php(39): Pico->run() #3 {main} thrown in D:\xampp\htdocs\cms\vendor\picocms\pico\lib\Pico.php on line 671

How to fix it?

**Comment by PhrozenByte** [comment]
Remove the superfluous `plugins/PicoEdit` folder.
