### ISSUE TITLE
 require(/storage/ssd4/291/15903291/public_html/vendor/composer/../symfony/polyfill-ctype/bootstrap.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by adamsaputra** [picocms/Pico#580]
I create my project with codeigniter, when I hosting my system with 000webhost I get an error like this
 require(/storage/ssd4/291/15903291/public_html/vendor/composer/../symfony/polyfill-ctype/bootstrap.php): failed to open stream: No such file or directory

**Comment by PhrozenByte** [comment]
Try reinstalling Pico
