### ISSUE TITLE
Proposal: Pico skeleton package with the main plugins

### ISSUE THREAD

**Issue by anasram** [picocms/Pico#581]
I'm wondering if it's good idea to offer a version of Pico already packaged with the main plugins in your web site:

* Search
* Tags
* RSS
* Force HTTPs (after fixing [this](https://github.com/alejandroliu/ForceHttpsPlugin/issues/1) issue)
* Syntax Highlighter
* Multilanguage support (with `<lang>.yaml` files).

**Comment by PhrozenByte** [comment]
Thank you for your suggestion! I'll think about it, a optional pre-built package with some official plugins definitely isn't far-fetched.

However, keep in mind that not everybody really needs all of this. For example, I use Pico for kind a number of websites and never used a search plugin or a syntax highlighter. To enforce HTTPS I prefer a webserver-based solution. Same is true for multilanguage support. That's probably the reason why there are no official plugins for this stuff yet :smile: For RSS there's [`PicoRobots`](https://github.com/PhrozenByte/pico-robots), the most basic implementation of tags works without plugins.

Other opinions are very welcome! :heart:
