### ISSUE TITLE
Installing Pico on php5

### ISSUE THREAD

**Issue by sookoll** [picocms/Pico#582]
It is question rather than bug report. Using composer to install Pico works well on php7+, deploying site to client's server I realised, that there is still php5, probably because there is other old developments on it, that do not work with php7. So composer autoloader complain about this and Pico site will not work. Any hints, how to get Pico up and running on php5 env?

**Comment by PhrozenByte** [comment]
Simply use one of Pico's pre-built release packages, they are built on PHP 5.

**Comment by sookoll** [comment]
Thanks. Will try that. I guess I can close it.
