### ISSUE TITLE
Using custom modified date for sorting

### ISSUE THREAD

**Issue by cronhill** [picocms/Pico#583]
Hej guys,

I try to do a Last modified List with a custom meta data. The meta data is named: Changed.

The input value is in this format: 2021-05-06. I put the field in the meta section like this: Changed: 2021-05-06

I use the pages loop to get the pages:

`<ul class="list--pages list-unstyled">
		{% for page in pages("", depth=3)|sort_by("meta.changed")|reverse if not page.hidden %}
			<li>{{ page.meta.changed|date("Y/m/d") }}  <a href="{{ page.url }}">{{ page.title }}</a> </li>
		{% endfor %}	
</ul>`

And the value of changed is displayed correctly.
But I can't sort after it.

I tried different values for sort_by like page.meta.changed, meta.changed or even changed, but nothing happens.

The list is nort sorted. I would appreciate help! I am a developing designer, not a designing developer.
So I tried to find the best out of Pico Docs and Twig Docs, but it doesn't helped me, I worry.

Thanks for help and regards, Thomas

**Comment by PhrozenByte** [comment]
Until you register the YAML header using a plugin (`onMetaHeaders` event, see [DummyPlugin](https://github.com/picocms/Pico/blob/d8470f9f5cee881390103cab441aed7301dd5e15/plugins/DummyPlugin.php#L455-L467)) or your theme's `pico-theme.yml` (key `meta`, see [example](https://github.com/picocms/pico-theme/blob/cb01f6c60c1b0ec5d3bb65e0104b72600850e30b/pico-theme.yml#L3-L6)), you must use key `Changed` (note the uppercase `C`) to access this meta value. Also note that Pico's `sort_by` Twig filter expects `[ 'meta', 'Changed' ]` as parameter.

```twig
	<ul class="list--pages list-unstyled">
		{% for page in pages("", depth=3)|sort_by([ 'meta', 'Changed' ])|reverse if not page.hidden %}
			<li>{{ page.meta.Changed|date("Y/m/d") }}  <a href="{{ page.url }}">{{ page.title }}</a> </li>
		{% endfor %}	
	</ul>
```
