### ISSUE TITLE
Problem Using Custom Meta 

### ISSUE THREAD

**Issue by cssdipen** [picocms/Pico#589]
I am not able to access custom meta in my .twig file

about.twig >>
<h2>{{ pages.index.meta.about_text }}</h2>

about.md>>
about_text: This is about us text

Output >>
about_text: This is about us text

It should be in h2 tag with this text "This is about us text"

**Comment by mayamcdougall** [comment]
Hi there.

I believe you’re going to want to use:

`{{ pages['index'].meta.about_text }}`

When accessing a specific page, `index` in this case is a Key in the pages array*, not a property of `pages` itself.

\* (I have a bad habit of calling everything an “array”. Technically in Twig, it’s a “Hash”, but it’s functionally the same as a “Dictionary” in many programming languages. Each entry is identified by a unique string, or “Key”.)

Hopefully this helps you out.  I’m just waking up, so it’s possible I’ve overlooked something here.

Feel free to follow up on this thread with any other support questions you might have. 😉
