### ISSUE TITLE
php fatal error

### ISSUE THREAD

**Issue by ktpx** [picocms/Pico#605]
Sounds easy enough to fix but..should i really be getting this :D 

PHP Fatal error:  Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /data/http/pico/vendor/twig/twig/lib/Twig/Node.php on line 42

php v8.0

**Comment by PhrozenByte** [comment]
Please see https://github.com/picocms/Pico/issues/584

**Comment by ktpx** [comment]
Thanks, will use the 3.0 alpha.
