### ISSUE TITLE
Tables are not working

### ISSUE THREAD

**Issue by johnwry** [picocms/Pico#606]
There is an issue with the online editor (markdown editor). I cannot get tables to show on Nextcloud. Someone said the text editor is to blame so I disabled that only to find the markdown editor does not work without the text editor. The md editor simple does not show tables. Please verify. Thanks.

**Comment by PhrozenByte** [comment]
This is the repository of Pico itself, for issues with Pico CMS for Nextcloud please refer to https://github.com/nextcloud/cms_pico. Since you've opened a issue there already, please refer to https://github.com/nextcloud/cms_pico/issues/181.
