### ISSUE TITLE
Help Topic

### ISSUE THREAD

**Issue by dawidmachon** [picocms/Pico#610]
Hi, again me.
@mayamcdougall I created this issue simple to keep all my questions in one place, because there will be a lot but not all on once.

Do you know if it's possible in config setup multiple themes? What I mean: content /blog will use different theme, than content /main for example.

Do you have something in mind for that? Because if there is no such option to manipulate theme per folder or .md file, I will simple setup second subdomain with second pico and use on first one link to redirect.

**Comment by mayamcdougall** [comment]
You know, I *just* realized that I did the very thing you're looking for way back in my [Notepaper](http://notepaper.mayamcdougall.me) theme.

Click the links under "CSS Pages" in the sidebar.  These doesn't change the HTML structure of the page at all, they only grab a separate stylesheet (it's a little hacky).  I made it so setting `Theme: WritingDesk` on a page would use the `WritingDesk` apply the extra stylesheet.

But you could easily apply the same methods to, say, change the layout of the elements on the page if you're in a specific folder, etc.

Feel free to look at the source code, but it's really *really* overcomplicated and out-of-date.  I need to rewrite it at some point, and I don't recommend using it for reference. 😅

Just thought it might work as a "visual aid".

**Comment by dawidmachon** [comment]
@mayamcdougall - I am now solving different issue somewhere else, but I will be back to Pico in next week and take look into your theme. It is very nice!

I am right now investigating [Dimension theme](https://github.com/BesrourMS/dimension) - I am already solving a lot of issues there and probably create own repository with it and update this theme to be more modern with pico and create proper documentation for it. Because BesrourMS made amazing work, but I do not like all of his solutions (like nav is not populated automatically from content folder) [I already implemented this]. I will share everything also in upcoming weeks, but right now I am ending another project not related to Pico.

**Comment by mayamcdougall** [comment]
> but I will be back to Pico in next week

No worries.  Take your time.  The `github-actions` bot just starts to threaten to close things after they've been stale for a while, lol.  I didn't want you to feel like it was anything personal on #609. 😉

> Because BesrourMS made amazing work, but I do not like all of his solution

I know exactly what you mean.  His ports are pretty good, but they're also a little barebones and/or simple.  There are things that I would do differently too.  I've actually said before that I'd be interested in redoing them for him at some point (though that wouldn't be any time soon). 😂

He does tend to be active and quick to reply on GitHub.  If you revamp some of his work, you could try to see if he's interested in a PR to update the original repo.

If he doesn't care or isn't interested, we could also see about adding a "Forks" section to the theme in our gallery.  It hasn't happened yet, but I know *eventually* I'll have to accommodate forked themes on the website, so I'm not *that* worried about it.
