### ISSUE TITLE
Failed opening required '__DIR__/composer/autoload_real.php

### ISSUE THREAD

**Issue by chrisalbon** [picocms/Pico#65]
I uploaded Pico but I only see a blank php page of death. After turning on error reporting, I get this:

> Notice: Use of undefined constant __DIR__ - assumed '__DIR__' in /hsphere/local/home/livenoma/writemorefaster.com/vendor/autoload.php on line 5 Warning: require_once(__DIR__/composer/autoload_real.php): failed to open stream: No such file or directory in /hsphere/local/home/livenoma/writemorefaster.com/vendor/autoload.php on line 5 Fatal error: require_once(): Failed opening required '__DIR__/composer/autoload_real.php' (include_path='.:/hsphere/shared/apache/libexec/php5ext/php/') in /hsphere/local/home/livenoma/writemorefaster.com/vendor/autoload.php on line 5 

I figured I had the wrong version of PHP, but I just checked and am running 5.2.10. Any ideas?

Here is my phpinfo: http://www.writemorefaster.com/test.php

**Comment by jduerr** [comment]
Did anyone figure out how to get pico running on PHP 5.2?
I'd love to set pico up on our NAS. But an update to php 5.3 is available for that old box, sadly.
Already tried using MaxGfellers tip - get the  Unexpected character in input warning like abely.

**Comment by cwiggs** [comment]
@jduerr FYI in case anyone else has this problem.  I was having a problem with this with Dokuwiki, and found my way here.  To fix that I just installed an older version of Dokuwiki.  That same fix might work with Pico.

**Comment by ChamodyaDias** [comment]
running "composer update" command worked for me.(windows)
