### ISSUE TITLE
Self-closing img tag

### ISSUE THREAD

**Issue by hack3r3d** [picocms/Pico#650]
I don't know that this is the correct forum for this sort of question, but how to change pico so it doesn't self-close img tags?

**Comment by PhrozenByte** [comment]
What is a "self-closing img tag" (`<img />`?) and why do you want to change its behaviour?

**Comment by hack3r3d** [comment]
I don't want it to <img /> I want it to be <img></img>

**Comment by PhrozenByte** [comment]
> Why is because it's better html.

Even though `<img></img>` is valid XHTML, it actually is *invalid* HTML5:

> [Void elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements) only have a start tag; end tags must not be specified for [void elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements).
>
> – Source: https://html.spec.whatwg.org/multipage/syntax.html#elements-2

> Start tags must have the following format:
> …
> 6. Then, if the element is one of the [void elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements), or if the element is a [foreign element](https://html.spec.whatwg.org/multipage/syntax.html#foreign-elements), then there may be a single U+002F SOLIDUS character (/). This character has no effect on [void elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements), but on [foreign elements](https://html.spec.whatwg.org/multipage/syntax.html#foreign-elements) it marks the start tag as self-closing.
>
> – Source: https://html.spec.whatwg.org/multipage/syntax.html#start-tags

Simply put: `<img></img>` is *invalid* HTML5, it must either be `<img>` (i.e. without a closing tag, but this is invalid XHTML), or `<img />` (both valid XHTML and HTML5). So I'd recommend not to do stuff like that. `<img />` is perfectly fine.

Anyway, you could extend [Parsedown](https://github.com/parsedown/parsedown) to transform your Markdown to whatever you like - or simply add the plain (X)HTML in your Markdown files.

**Comment by hack3r3d** [comment]
I don't want to get into a debate about html, but the answer it to extend Parsedown? Thanks.
