### ISSUE TITLE
Initial Connection is Slow

### ISSUE THREAD

**Issue by notakoder** [picocms/Pico#651]
The initial connection to (indicated by the colourless animation on the browser tab) a Pico website during a page request is slower than the subsequent page requests. This is also seen when a Pico website is opened for a long time and then a page is requested. This behaviour is seen across all browsers and all hosting providers (I use Apache).

Is this by design?

**Comment by PhrozenByte** [comment]
This highly depends on the number of Markdown files in your website: many Markdown files makes uncached requests rather slow. We're planning major performance improvements with the next major release after the one currently in development (Pico 4.0). There are some plugins out there to improve things, but note that they have some disadvantages (check the plugin's readme).

**Comment by notakoder** [comment]
Thank you.
