### ISSUE TITLE
Deprecated: trim(): Passing null to parameter #1 ($string) Running on PHP8.1.11

### ISSUE THREAD

**Issue by sampatirage** [picocms/Pico#652]
Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in C:\Bitnami\wamp\apache2\htdocs\pico-cms\vendor\symfony\yaml\Inline.php on line 49.
Deprecated: Return type of Twig_Markup::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Bitnami\wamp\apache2\htdocs\pico-cms\vendor\twig\twig\lib\Twig\Markup.php on line 33.
Deprecated: realpath(): Passing null to parameter #1 ($path) of type string is deprecated in C:\Bitnami\wamp\apache2\htdocs\pico-cms\vendor\twig\twig\lib\Twig\Loader\Filesystem.php on line 35

Fatal error: Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in C:\Bitnami\wamp\apache2\htdocs\pico-cms\vendor\twig\twig\lib\Twig\Node.php on line 42

**Comment by Croydon** [comment]
Duplicate of #608

**Comment by sampatirage** [comment]
Thanks, Michael
