### ISSUE TITLE
Adding Image in Frontmatter

### ISSUE THREAD

**Issue by notakoder** [picocms/Pico#666]
What is the right way to add an image in YAML frontmatter?
```
Title: Page Title
Image: 
```

`http://localhost/site-name/path/to/image` works, but not in remote,
`%base_url%/path/to/image` does not work,
`{{ base_url }}/path/to/image` does not work either,
`/path/to/image` will not include the site name (localhost/path/to/image).

**Comment by PhrozenByte** [comment]
`Image: %assets_url%/path/to/image.png` is the correct syntax, but you have to pass this to Pico's `url` Twig filter in your Twig templates, e.g. `<img src="{{ meta.image|url }}" alt="" />`.

**Comment by notakoder** [comment]
Sorry. I am reopening this issue.

My `base_url` is `http://localhost/project_x`. But my `assets_dir` is outside the project directory since it is shared by various other projects. Here is my `config.yml` and frontmatter.

```
assets_dir: /var/www/cdn
assets_url: http://localhost/cdn
```
```
Image: %assets_url%/images/project_x/image.jpg
```

What I need rendered is

`<img src="http://localhost/cdn/images/project_x/image.jpg">`

Here is what I tried.

`a href="{{ page.url }}"><img src="{{ page.meta.image|link }}"><br>{{ page.title }}</a>`    
renders
`<img src="http://localhost/project_x/%25assets_url%25/images/project_x/image.jpg">`

`a href="{{ page.url }}"><img src="{{ page.meta.image }}"><br>{{ page.title }}</a>`
renders
`<img src="%assets_url%/images/project_x/image.jpg">`

`a href="{{ page.url }}"><img src="{{ meta.image }}"><br>{{ page.title }}</a>`
renders
`<img src="">`

`a href="{{ page.url }}"><img src="{{ meta.image|link }}"><br>{{ page.title }}</a>`
renders
`<img src="http://localhost/project_x/">`

**Comment by PhrozenByte** [comment]
Use Pico's `url` Twig filter; the `link` filter is for page links only.

```twig
<a href="{{ page.url }}"><img src="{{ page.meta.image|url }}"></a>
```

**Comment by notakoder** [comment]
To make sure that I didn't mistype anything from your previous comment, I had checked my code at least a couple of times against your comment... especially the filter. And yet I mistook the `url` filter for the `link` filter. Cognitive overflow I guess.

Small things indeed it is that eats up most of the productive time. Sorry about it and thanks again @PhrozenByte

**Comment by PhrozenByte** [comment]
No worries, don't hesitate to ask if you've any other question :relaxed: :+1:

**Comment by notakoder** [comment]
Sure and thank you.
That's the attitude I appreciate the most in the Pico project.
