### ISSUE TITLE
Deprecation error on Alpha-2 that I’m trying to understand… failing

### ISSUE THREAD

**Issue by lloydsargent** [picocms/Pico#668]
This is the code:

```
composer/ClassLoader.php

/**
 * Scope isolated include.
 *
 * Prevents access to $this/self from included files.
 */
function includeFile($file)
{
    include $file;
}

```

Twig calls it and I get the following:

    Exception has occurred.
    Deprecated: Optional parameter $callable declared before required parameter $arguments is implicitly treated as a required parameter

Not being a PHP expert, I know what the code does, just not what the error actually means or, better yet, how to fix it.

**Comment by PhrozenByte** [comment]
Set `error_reporting` in your `php.ini` to a value recommended for production servers, e.g. `error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT`.

**Comment by lloydsargent** [comment]
I’m puzzled how this changes the fact that it is deprecated?
