### ISSUE TITLE
Suboptimal process of process pages id

### ISSUE THREAD

**Issue by zeleznypa** [picocms/Pico#671]
The content folder (`.../content`) and extension (`.md`) is fixed for every pages, so it is not necessary to count the string length of the extension for every page.

https://github.com/picocms/Pico/blob/09aa82578710d82dd7dc482febe32991be0ea307/lib/Pico.php#L1739

It will be better to count it once before the `foreach` and use the result everytime ...

```php
$contentDirLen = strlen($contentDir);
$contentExtLen = strlen($contentExt);

foreach ($files as $i => $file) {
   // ...
   $id = substr($file, $contentDirLen, -$contentExtLen);
```

**Comment by PhrozenByte** [comment]
Interested in opening a PR against the `pico-3.0` branch?
