### ISSUE TITLE
RSS Support?

### ISSUE THREAD

**Issue by francesmothrock** [picocms/Pico#672]
Pico is wonderful, but I have been unable to find out how to implement RSS support. I followed the instructions for RSS creation here and don't get any response when I enter [mywebsite.com]/feed/ 
It just shows the same page without changing, and RSS readers say no feed is found. 
https://picocms.org/cookbook/

I am on Pico 3.0.0 Alpha 2. I had to move to Alpha to get it to work with php 8.1, so I can't know if the Stable version would work 

Are there other RSS solutions to try? RSS is a key feature for me. Forgive me if I am missing something simple, I am not a programmer.
Thank you!

**Comment by PhrozenByte** [comment]
> don't get any response when I enter [mywebsite.com]/feed/
> It just shows the same page without changing

What exactly does this mean? Is an empty page shown, is Pico's index page shown, is Pico's 404 page shown, is an error page of your webserver shown, or is the RSS feed XML shown?

**Comment by francesmothrock** [comment]
Sorry for being unclear. It just goes back to the index page and doesn't show any rss related information.

**Comment by PhrozenByte** [comment]
You did create both a `content/feed.md` with `Template: feed` in the YAML Front Matter (and otherwise empty content) and a `themes/<your theme>/feed.twig`, right? Seeing Pico's index page when accessing example.com/feed rather indicates some misconfiguration of your webserver. Did you try requesting example.com/?feed instead?

**Comment by francesmothrock** [comment]
I will have to go back and see if I made any mistakes in setting up the two feed files, but when I go to example.com/?feed, it works. So thank you! It didn't occur to me to try that syntax. Sorry for the trouble.
