### ISSUE TITLE
Reverse case sensitive declaration of meta attributes is confusing

### ISSUE THREAD

**Issue by dipohl** [picocms/Pico#684]
I tried to declare my 'lang' attribute in the pico-theme.yml and found that I had to use lower case 'lang' in the declaration:

   `meta:                           # Register meta headers used by this theme`
   `lang: de                    # Used to filter by language`

and upper case in the twig files:

`{{ page.meta.Lang }}`

to use the existing upper case declarations from the pages content header:

`Lang: de`

Other combinations didn't work.

Why is that so? And can it be changed so that it is at least consistent? The best for Usability would be case insensitive at least in the content area.

fyi & kind regards

**Comment by PhrozenByte** [comment]
In `pico-theme.yml` you declare known meta headers like in Pico's `onMetaHeaders` event, i.e. `search_string: replace_string`. In your case you want `Lang: lang` there, i.e. a `Lang` meta header is saved as `lang`, so that you can access it via lowercase.

**Comment by dipohl** [comment]
Found a new issue concerning the meta headers. Your recipe works for the index twig files. There the access 
via `{{ page.meta.lang }}` works within a loop over `% for page in pages("blog")|sort_by("time")|reverse %}`

But for a single page view (without the loop), this delivers no value. It works there when I access 
via `{{ meta.lang }}`

What is needed in the page view twig file, so that I can use the same syntax in all twig files?

**Comment by PhrozenByte** [comment]
> I propose to add there something like this:

Pull request is welcome :+1:

> What is needed in the page view twig file, so that I can use the same syntax in all twig files?

I don't really understand the question. They are different things after all? One is the current page, the other is an iteration through all pages, thus a whole different story and used in a different context for different things.

**Comment by dipohl** [comment]
> > I propose to add there something like this:
> 
> Pull request is welcome 👍

ok, I'll do

> > What is needed in the page view twig file, so that I can use the same syntax in all twig files?
> 
> I don't really understand the question. They are different things after all? One is the current page, the other is an iteration through all pages, thus a whole different story and used in a different context for different things.

ah, I see. The created field is called `meta.lang` and only because the loops cursor is called 'page' I have to set its name  before meta.lang, right?

hmm, was a stupid question then and shows my state of confusion at the time (see the subject of this issue report ;-)
