### ISSUE TITLE
Best way to add script inside <head>

### ISSUE THREAD

**Issue by killing-vodka** [picocms/Pico#689]
If I want to write a plugin that needs to integrate a script or CSS into the `<head>` of a page, is there any specific hook I should use? Or can I use something like:

```
public function onPageRendered(&$output) {

...some code...

$output = preg_replace('/\<\/head\>/', "{$mycss}\n{$myjs}\n</head>" , $output);       	

}
```

**Comment by PhrozenByte** [comment]
Just tell users to add the necessary HTML tags to the Twig templates, don't fiddle with the HTML in your plugin.

**Comment by killing-vodka** [comment]
Actually, the purpose of the plugin is precisely this, so it would have little or no reason to exist. Those who want to integrate this functionality must do it independently in their own theme, right? I'm thinking of things like Google Analytics, script for code prettifier, etc. A plugin do not make sense...

**Comment by PhrozenByte** [comment]
> Those who want to integrate this functionality must do it independently in their own theme, right? I'm thinking of things like Google Analytics, script for code prettifier, etc. A plugin do not make sense...

Correct, yes.
