### ISSUE TITLE
picocms.org is down right now

### ISSUE THREAD

**Issue by gabriel-r** [picocms/Pico#690]
FYI, www.picocms.org is down right now

https://downforeveryoneorjustme.com/picocms.org

**Comment by gabriel-r** [comment]
This is not "completed" in any way though :-/

**Comment by Croydon** [comment]
The website seems to work only without `www`

**Comment by picocms** [comment]
Apologies. The site was fixed on root, which is the default, but the www subdomain is now sorted, too.
