### ISSUE TITLE
pre-bundled release: Getting "HTTP ERROR 500"

### ISSUE THREAD

**Issue by ZuluPilgrim** [picocms/Pico#692]
Uploaded 2.1.4 to a shared server (CrazyDomains) and when I browse, I get "HTTP ERROR 500".

Not sure where to start troubleshooting.

**Comment by killing-vodka** [comment]
Check in your cPanel that the requirements for your version of Pico are met. If everything is okay, verify that the upload was successful, and if not, repeat the operation.

**Comment by ZuluPilgrim** [comment]
Requirements look fine:

![image](https://github.com/picocms/Pico/assets/111164245/448243a6-80ff-4a9c-a3b5-a291a222700e)

I re-uploaded the pre-bundle and the same thing happens: [demo.internetlinked.com](demo.internetlinked.com)

**Comment by ZuluPilgrim** [comment]
Just had a thought. Is it because Cloudflare is forcing and HTTPS connection?

**Comment by ZuluPilgrim** [comment]
Just had a thought. Is it because cloudflare is forcing and HTTPS connection?

**Comment by killing-vodka** [comment]
I recommend using version 3 of Pico. It adds support for PHP 8 and includes some other updates. Otherwise, you'll need to downgrade PHP. The link seems to be inaccessible to me with a 'Sorry, you have been blocked' message. Something seems to be wrong, but let's check it later.

**Comment by ZuluPilgrim** [comment]
Ah, I might have geoblocked the domain.. I will try v3 tomorrow and if that doesn't work, check the cloudflare geolocations.

**Comment by ZuluPilgrim** [comment]
Sorry, have not had an opportunity to try, will do so in a couple of days time.
