### ISSUE TITLE
Support for Twig extensions?

### ISSUE THREAD

**Issue by jsstaedtler** [picocms/Pico#693]
(Apologies in advance if I'm going through the wrong channel with this)

I've been doing a lot of theme work in Pico 3, and I've hit a situation that would be solved perfectly by Twig's `u` filter.  But it seems that's part of [an optional Twig extension](https://github.com/twigphp/string-extra/blob/3.x/StringExtension.php), and my failed attempts at using `u` imply that it's not included with Pico.

I don't know how Twig is integrated into Pico, so I'm curious how big a challenge it is to add such an extension?  I wish I knew more about the dev side of Pico so I could even help work that out, but I'm without a starting point on this one.

Meanwhile, thanks for this fantastic application, it's permitted me to build some great stuff so far.

**Comment by PhrozenByte** [comment]
You might create a Pico plugin that hooks into the `onTwigRegistered` event, exposing the Twig object where you can register this Twig extension. See `DummyPlugin` for how Pico plugins look like and refer to Twig's docs on how to register a Twig extension.

**Comment by jsstaedtler** [comment]
I'll give that a go, thanks!
