### ISSUE TITLE
[draft ] Autoload extra stuff

### ISSUE THREAD

**Issue by killing-vodka** [picocms/Pico#695]
If we need to deal with scripts or similar stuff, it's a good practice to manually add them into the twig file, so we can avoid string replacements. But what if we're lazy?

This plugin adds a directory with its template:
```
    public function  onPageRendering(&$twig, &$twigVariables)
    {
        global $global_array;
        $global_array[] = 'mytpl1.twig';
        $twigVariables['GlobalArray']  = $global_array;
    }    
       
    public function onTwigRegistered(Twig_Environment &$twig)
    {

        $twig->getLoader()->addPath(__DIR__ . '/theme');
    }
```
twig:
```
    <link href=.... >
```
The theme searches for all .twig files in the array and loads their content:

```
<head>
...
...
{% for key, var in GlobalArray %}
    {% include GlobalArray[key] %}
{% endfor %}
</head>
```

It's not stupid if it works. And it works. Can be a good approach?

**Comment by PhrozenByte** [comment]
Using the Twig Loader to add paths to provide default templates for a plugin's Twig templates is a good common practice, yes.

Not sure about why you're trying to solve with that `GlobalArray` though. You mean like an API to load a plugin's scripts and stylesheets dynamically? Yes, this is a good idea; it just requires a simple plugin to provide the necessary API and the custom theme to include the necessary HTML to actually include the scripts and stylesheets.

**Comment by killing-vodka** [comment]
Exactly. You can have multiple plugins (Bootstrap 5, AdSense, code prettifier, etc.). Each plugin adds its path to the appropriate Twig file, and the theme loads them with a loop:

```
plugins/PicoBoostrap5/theme/boostrap5.twig
plugins/PicoAdsense/theme/adsense.twig
plugins/Picoxxx/theme/xxx.twig
```

Or a single plugin "loader" who add a single path where the user can put the necessary staff.
```
plugins/PicoLoader/theme/put here your .twig

```

Adding a script to a template is not a difficult task, but some fancy/lazy plugins can be useful for enlarging the user base.

**Comment by PhrozenByte** [comment]
I was rather thinking about a simple PHP API like `$themeManager->registerJavascript("plugins/PicoBootstrap5/theme/js/main.js")` and `$themeManager->registerStylesheet()`, basically similar to [Grav's asset manager](https://learn.getgrav.org/17/themes/asset-manager). A single Twig template wouldn't allow one to register both JavaScript files and stylesheets.

**Comment by killing-vodka** [comment]
So, we just need to add `{{ ScriptManager }}` inside the `<head>` tags, and every plugin will load its stuff.

I will return with some strange php. :smile:

**Comment by digitalinferno** [comment]
I have developed both paths.

In the first case I can write a plugin and register an asset via:
```
$assetsManager = $this->getPico()->getPlugin('AssetsManager');
$assetsManager->registerAsset("{$dir}/styles/zero.css", 50, 'head', false, 'css');
$assetsManager->registerAsset("{$dir}/js/code.js", 50, 'head', false, 'js');
```
with the main plugin AssetsManager making the magic:
```
    /**
     * Registers an asset (CSS, JS, inline)
     * 
     * @param string $path
     * @param int $priority
     * @param string $group
     * @param bool $inline
     * @param string $type
     * @param bool $defer
     * @param bool $async
     */
    public function registerAsset(string $path, int $priority = 50, string $group = 'head', bool $inline = false, string $type = 'js', bool $defer = false, bool $async = false)
{

}
```
In the second case I can register an assets by array: 
```
    /**
     * Triggered after the theme has been loaded and assets can be registered
     *
     * @see    AssetsManager::onThemeLoaded()
     * @param  array &$assets list of assets to be registered
     * @return void
     */

    public function onAssetsLoading(array &$assets)
    {
        // CSS
        $assets[] = [
            'path' => "{$dir}/styles/zero.css",
            'priority' => 50,
            'group' => 'head',
            'inline' => false,
            'type' => 'css'
        ];
        // Js
        $assets[] = [
            'path' => "{$dir}/js/code.js",
            'priority' => 50,
            'group' => 'footer',
            'inline' => false,
            'type' => 'js'
        ];
      
    }
```
The AssetsManager reads all values:
```
    public function onThemeLoaded($theme, $themeApiVersion, array &$themeConfig)
    {
        $assets = [];

        foreach ($this->pico->getPlugins() as $plugin) {
            if (method_exists($plugin, 'onAssetsLoading')) {
                $plugin->onAssetsLoading($assets);
            }
        }

        foreach ($assets as $asset) {
            $this->registerAsset($asset);
        }
    }
```
In this case, all plugins load their assets simultaneously using the `onAssetsLoading` method, and in my opinion, the array format makes the process more intuitive and forgiving.

**Comment by PhrozenByte** [comment]
Looks great :heart:

If you wanna share your work, you might wanna add it to our wiki at https://github.com/picocms/Pico/wiki/Pico-Plugins :+1:

By the way: To call the `onAssetsLoading` event (suggestion: how about another `onAssetsLoaded`?) you might check out `Pico::triggerEvent()` - it will also work for custom events :+1:

**Comment by digitalinferno** [comment]
Thanks for the hint! Which approach do you prefer: working with an array or using a custom function?

**Comment by PhrozenByte** [comment]
That's totally up to you, your reasoning makes very much sense :+1:
