### ISSUE TITLE
[PLUGIN] XMPP: Post to PubSub [NOT CLOSED YET]

### ISSUE THREAD

**Issue by sjehuda** [picocms/Pico#696]
Greetings!

In XMPP, using PubSub(1) (XEP-0060), it is possible to store posts as Atom Syndication(2) entries into XMPP(3).

There are several XMPP extensions that apply it, namely XEP-0227 (4) and XEP-0472 (5) which make node `urn:xmpp:microblog:0` as a common choice to manage news for client accounts (e.g. `blog@picocms.org`), yet a component account (e.g. `pubsub.picocms.org`) may use all of its nodes for this purpose.

```
pubsub.picocms.org/
|
|-- updates/
    |-- Sombre
     `-- Varied
|-- releases/
 `-- events/
```
```
pubsub service/
|
|-- node/
    |-- item
     `-- item
|-- node/
 `-- node/
```

A PHP library that can be utilized would be Moxl of Movim.

I have made a script that realizes viewing PubSub node items as Atom XML feeds over HTTP.

1. [XEP-0060: Publish-Subscribe](https://xmpp.org/extensions/xep-0060.html)
2. [RFC 4287: The Atom Syndication Format](https://www.rfc-editor.org/rfc/rfc4287)
3. [Atom Over XMPP](https://datatracker.ietf.org/meeting/66/materials/slides-66-atompub-1.pdf)
4. [XEP-0277: Microblogging over XMPP](https://xmpp.org/extensions/xep-0277.html)
5. [XEP-0472: Pubsub Social Feed](https://xmpp.org/extensions/xep-0472.html)
6. [Moxl](https://github.com/movim/movim/tree/master/src/Moxl)
7. [PubSub Over HTTP](https://codeberg.org/poezio/slixmpp/issues/3526)

**Comment by PhrozenByte** [comment]
I assume you picked the wrong repo here, Pico CMS doesn't use XMPP.

**Comment by sjehuda** [comment]
Currently, Movim is the prominent platform that utilizes PubSub extensively. I advise you to check Movim so you would see a visual realization of PubSub potential.

**Comment by PhrozenByte** [comment]
I see. It didn't really emerge from your description that this is a suggested addition. This definitely isn't something for Pico's core, Pico intentionally sticks to the bare minimum. However, if you wanna create a plugin for that please go ahead, we appreciate any 3rd-party plugin! :+1: You can then add your plugin to our wiki or the website to spread the word, see https://picocms.org/plugins/#entry-zzz_contribute

I'm re-opening this for now if you have any questions about how to create such plugin. However, it will be closed in a few days by our Stale bot anyway; we don't usually keep non-bug issues open.

Happy coding! :clap: :+1:

**Comment by sjehuda** [comment]
Very well and thank you for the explanation and good will!

If this ticket is closed, will it be locked?

**Comment by PhrozenByte** [comment]
> If this ticket is closed, will it be locked?

No, we don't usually lock tickets, you can add new comments at any time :+1:

**Comment by sjehuda** [comment]
Then I will close this ticket.
I have changed the title.

I do not code in PHP often.

Is there a forum?
Are there people I can consult with in the Pico community?
