### ISSUE TITLE
PHP pages depth & offset

### ISSUE THREAD

**Issue by digitalinferno** [picocms/Pico#701]
In PHP, can I use something similar to the Twig `pages()` function?

With `foreach ($pages as $page)` in `onPagesLoaded(&$pages)`, I can filter the result with `$page["meta"]`. However, if I need only a specific node tree, I have to play with the `id`. Are there no alternatives?

**Comment by PhrozenByte** [comment]
There's no direct equivalent, however, if you want to access Pico's page tree directly, you can hook into the `onPageTreeBuilt` event or use the `Pico::getPageTree()` method (available only after said event). See https://picocms.org/in-depth/features/page-tree/ for a rather extensive explanation of Pico's page tree.
