### ISSUE TITLE
Image not loading

### ISSUE THREAD

**Issue by llorban** [picocms/Pico#704]
Greetings, 

What could be preventing an image from loading on a new pico installation on ubuntu 24 with digital ocean? Image URL is correct, image file is present, but the image on the website shows are broken/not loaded. 

Thanks, 
Levente

**Comment by digitalinferno** [comment]
Can you provide a link?

**Comment by llorban** [comment]
I found the issue. The images needed the right permissions, chmod 770 <img.jpeg> fixe it.
