### ISSUE TITLE
Contact form - how does it work

### ISSUE THREAD

**Issue by 5k18a** [picocms/Pico#705]
I'm trying to configure a contact form using a Dimension theme, and I really don't know where I can configure where te message is sent. Anyone can help me with this issue. I assume that all the forms in different themes works same way. I found that there is form.meta but where it is processed? I thought that there should be some settings in config.yml but no..

**Comment by PhrozenByte** [comment]
There's no built-in contact form support in Pico. You'll have to either add a 3rd-party plugin or use some external contact form service.

**Comment by dkyme** [comment]
At content-sample/index.md of the Dimension Theme you can find in the Meta Section a link to an 3rd Party Service (Formbucket)

**Comment by 5k18a** [comment]
Great thanks for that I actually didn't notice it :)
